"use strict";this.default_uiframehook=this.default_uiframehook||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da,ea;_.n=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.q=function(a,b){function c(){}c.prototype=b.prototype;a.I=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.nf=function(a,c,f){for(var h=Array(arguments.length-2),l=2;l<arguments.length;l++)h[l-2]=arguments[l];return b.prototype[c].apply(a,h)}};
_.fa=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.r.apply(null,arguments)};_.ga=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ia=function(a){return"function"==ea(a)};_.ja=function(a){return"number"==typeof a};
_.t=function(a){return"string"==typeof a};_.ka=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.v=function(a){return"array"==ea(a)};_.ma=function(a){a.Ga=function(){return a.Gc?a.Gc:a.Gc=new a}};_.na=function(){};_.oa=function(a){a=a.split(".");for(var b=_.k,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b};_.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}; _.q(_.pa,Error);_.pa.prototype.name="CustomError";
var sa,ua;_.ra=function(a){return/^[\s\xa0]*$/.test(a)};sa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.ta=function(a){return null==a?"":String(a)};
_.va=function(a,b){for(var c=0,d=sa(String(a)).split("."),e=sa(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var l=d[h]||"",p=e[h]||"",u=RegExp("(\\d*)(\\D*)","g"),ha=RegExp("(\\d*)(\\D*)","g");do{var la=u.exec(l)||["","",""],qa=ha.exec(p)||["","",""];if(0==la[0].length&&0==qa[0].length)break;c=ua(0==la[1].length?0:(0,window.parseInt)(la[1],10),0==qa[1].length?0:(0,window.parseInt)(qa[1],10))||ua(0==la[2].length,0==qa[2].length)||ua(la[2],qa[2])}while(0==c)}return c}; ua=function(a,b){return a<b?-1:a>b?1:0};
_.wa=Array.prototype;_.xa=_.wa.indexOf?function(a,b,c){return _.wa.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.ya=_.wa.lastIndexOf?function(a,b,c){return _.wa.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.w=_.wa.forEach?function(a,b,c){_.wa.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.za=_.wa.filter?function(a,b,c){return _.wa.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.t(a)?a.split(""):a,l=0;l<d;l++)if(l in h){var p=h[l];b.call(c,p,l,a)&&(e[f++]=p)}return e};_.Aa=_.wa.map?function(a,b,c){return _.wa.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
_.Ba=_.wa.reduce?function(a,b,c,d){d&&(b=(0,_.r)(b,d));return _.wa.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.w)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};_.Ca=_.wa.some?function(a,b,c){return _.wa.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
_.Da=function(a,b){var c;a:{c=a.length;for(var d=_.t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:_.t(a)?a.charAt(c):a[c]};_.Ea=function(a,b){return 0<=(0,_.xa)(a,b)};_.Fa=function(a,b){var c=(0,_.xa)(a,b),d;(d=0<=c)&&_.wa.splice.call(a,c,1);return d};_.Ga=function(a){return _.wa.concat.apply(_.wa,arguments)};_.Ha=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
var Ia,Ka,Ja,Na,Oa,Ma;Ia=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("c`"+a);};_.La=function(a){var b=[];Ja(new Ka,a,b);return b.join("")};Ka=function(){};
Ja=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.v(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Ja(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Ma(d,c),c.push(":"),Ja(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Ma(b,c);break;case "number":c.push((0,window.isFinite)(b)&&
!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "function":c.push("null");break;default:throw Error("d`"+typeof b);}}};Na={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};Oa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;Ma=function(a,b){b.push('"',a.replace(Oa,function(a){var b=Na[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Na[a]=b);return b}),'"')};
var Ra;_.Pa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Qa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Ra="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Sa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ra.length;f++)c=Ra[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Ta=function(a,b,c){this.g=c;this.c=a;this.h=b;this.b=0;this.a=null};Ta.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var Ua=function(a,b){a.h(b);a.b<a.g&&(a.b++,b.next=a.a,a.a=b)};var Ya;_.Va=[];_.Wa=[];_.Xa=!1;Ya=function(a){_.Va[_.Va.length]=a;if(_.Xa)for(var b=0;b<_.Wa.length;b++)a((0,_.r)(_.Wa[b].b,_.Wa[b]))};a:{var $a=_.k.navigator;if($a){var ab=$a.userAgent;if(ab){_.Za=ab;break a}}_.Za=""}_.x=function(a){return-1!=_.Za.indexOf(a)};var bb=function(){return _.x("Opera")||_.x("OPR")},cb=function(){return(_.x("Chrome")||_.x("CriOS"))&&!bb()&&!_.x("Edge")};var db=function(a){_.k.setTimeout(function(){throw a;},0)},eb,fb=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.x("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+
"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.x("Trident")&&!_.x("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.rc;c.rc=null;a()}};return function(a){d.next={rc:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in
window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}},gb=function(a){return a};Ya(function(a){gb=a});
var hb=function(){this.b=this.a=null},jb=new Ta(function(){return new ib},function(a){a.reset()},100);hb.prototype.add=function(a,b){var c=jb.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};hb.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var ib=function(){this.next=this.b=this.a=null};ib.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};ib.prototype.reset=function(){this.next=this.b=this.a=null};
var ob=function(a,b){kb||lb();mb||(kb(),mb=!0);nb.add(a,b)},kb,lb=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve(void 0);kb=function(){a.then(pb)}}else kb=function(){var a=pb,a=gb(a);!_.ia(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(eb||(eb=fb()),eb(a)):_.k.setImmediate(a)}},mb=!1,nb=new hb,pb=function(){for(var a=null;a=nb.remove();){try{a.a.call(a.b)}catch(b){db(b)}Ua(jb,a)}mb=!1};
var qb=function(){this.b="";this.a=null},rb=function(a){var b=new qb;b.b=a;b.a=0};rb("<!DOCTYPE html>");rb("");var sb="StopIteration"in _.k?_.k.StopIteration:{message:"StopIteration",stack:""},tb=function(){};tb.prototype.next=function(){throw sb;};tb.prototype.xa=function(){return this};
var ub=function(a){if(a instanceof tb)return a;if("function"==typeof a.xa)return a.xa(!1);if(_.ka(a)){var b=0,c=new tb;c.next=function(){for(;;){if(b>=a.length)throw sb;if(b in a)return a[b++];b++}};return c}throw Error("h");},vb=function(a,b){if(_.ka(a))try{(0,_.w)(a,b,void 0)}catch(c){if(c!==sb)throw c;}else{a=ub(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(d){if(d!==sb)throw d;}}},wb=function(a){if(_.ka(a))return _.Ha(a);a=ub(a);var b=[];vb(a,function(a){b.push(a)});return b};
var xb;xb=function(){return _.x("iPhone")&&!_.x("iPod")&&!_.x("iPad")};_.yb=function(){return _.x("Windows")};_.y=function(a,b){this.b={};this.a=[];this.g=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("e");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.y?(c=a.ba(),d=a.U()):(c=_.Qa(a),d=_.Pa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.y.prototype.qa=function(){return this.c};_.y.prototype.U=function(){zb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.y.prototype.ba=function(){zb(this);return this.a.concat()};
_.Bb=function(a,b){return Ab(a.b,b)};_.y.prototype.ia=function(){return 0==this.c};_.y.prototype.clear=function(){this.b={};this.g=this.c=this.a.length=0};_.y.prototype.remove=function(a){return Ab(this.b,a)?(delete this.b[a],this.c--,this.g++,this.a.length>2*this.c&&zb(this),!0):!1};
var zb=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Ab(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Ab(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.g=_.y.prototype;_.g.get=function(a,b){return Ab(this.b,a)?this.b[a]:b};_.g.set=function(a,b){Ab(this.b,a)||(this.c++,this.a.push(a),this.g++);this.b[a]=b};_.g.forEach=function(a,b){for(var c=this.ba(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.g.clone=function(){return new _.y(this)};_.g.xa=function(a){zb(this);var b=0,c=this.g,d=this,e=new tb;e.next=function(){if(c!=d.g)throw Error("i");if(b>=d.a.length)throw sb;var e=d.a[b++];return a?e:d.b[e]};return e};var Ab=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Cb=function(a){if("function"==typeof a.U)return a.U();if(_.t(a))return a.split("");if(_.ka(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return _.Pa(a)};
_.Db=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.ka(a)||_.t(a))(0,_.w)(a,b,c);else{var d;if("function"==typeof a.ba)d=a.ba();else if("function"!=typeof a.U)if(_.ka(a)||_.t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Qa(a);else d=void 0;for(var e=_.Cb(a),f=e.length,h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};
var Eb,Gb,Jb,Nb,Ob,Pb,Qb,Sb;Eb=bb();_.Fb=_.x("Trident")||_.x("MSIE");Gb=_.x("Edge");_.Hb=_.x("Gecko")&&!(-1!=_.Za.toLowerCase().indexOf("webkit")&&!_.x("Edge"))&&!(_.x("Trident")||_.x("MSIE"))&&!_.x("Edge");_.Ib=-1!=_.Za.toLowerCase().indexOf("webkit")&&!_.x("Edge");Jb=_.k.navigator||null;_.Kb=Jb&&Jb.platform||"";_.Lb=_.x("Macintosh");_.Mb=_.yb();
Nb=function(){var a=_.Za;if(_.Hb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Gb)return/Edge\/([\d\.]+)/.exec(a);if(_.Fb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Ib)return/WebKit\/(\S+)/.exec(a)};Ob=function(){var a=_.k.document;return a?a.documentMode:void 0};Pb=function(){if(Eb&&_.k.opera){var a=_.k.opera.version;return _.ia(a)?a():a}var a="",b=Nb();b&&(a=b?b[1]:"");return _.Fb&&(b=Ob(),b>(0,window.parseFloat)(a))?String(b):a}();Qb={};_.Rb=function(a){return Qb[a]||(Qb[a]=0<=_.va(Pb,a))}; Sb=_.k.document;_.Tb=Sb&&_.Fb?Ob()||("CSS1Compat"==Sb.compatMode?(0,window.parseInt)(Pb,10):5):void 0;
_.z=function(){this.R=this.R;this.D=this.D};_.z.prototype.R=!1;_.z.prototype.Wb=function(){return this.R};_.z.prototype.T=function(){this.R||(this.R=!0,this.L())};_.z.prototype.L=function(){if(this.D)for(;this.D.length;)this.D.shift()()};_.Ub=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};_.Vb=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var Yb,Zb,cc,ac,hc,fc,dc,ec,jc,ic,kc;_.Xb=function(a,b){this.a=0;this.j=void 0;this.g=this.b=this.c=null;this.h=this.D=!1;if(a!=_.na)try{var c=this;a.call(b,function(a){_.Wb(c,2,a)},function(a){_.Wb(c,3,a)})}catch(d){_.Wb(this,3,d)}};Yb=function(){this.next=this.context=this.b=this.g=this.a=null;this.c=!1};Yb.prototype.reset=function(){this.context=this.b=this.g=this.a=null;this.c=!1};Zb=new Ta(function(){return new Yb},function(a){a.reset()},100);
_.$b=function(a,b,c){var d=Zb.get();d.g=a;d.b=b;d.context=c;return d};_.Xb.prototype.then=function(a,b,c){return ac(this,_.ia(a)?a:null,_.ia(b)?b:null,c)};_.Ub(_.Xb);_.Xb.prototype.l=function(a){0==this.a&&ob(function(){var b=new _.bc(a);cc(this,b)},this)};
cc=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.c||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?cc(c,b):(f?(d=f,d.next==c.g&&(c.g=d),d.next=d.next.next):dc(c),ec(c,e,3,b)))}a.c=null}else _.Wb(a,3,b)};_.gc=function(a,b){a.b||2!=a.a&&3!=a.a||fc(a);a.g?a.g.next=b:a.b=b;a.g=b};
ac=function(a,b,c,d){var e=_.$b(null,null,null);e.a=new _.Xb(function(a,h){e.g=b?function(c){try{var e=b.call(d,c);a(e)}catch(u){h(u)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.n(e)&&b instanceof _.bc?h(b):a(e)}catch(u){h(u)}}:h});e.a.c=a;_.gc(a,e);return e.a};_.Xb.prototype.F=function(a){this.a=0;_.Wb(this,2,a)};_.Xb.prototype.v=function(a){this.a=0;_.Wb(this,3,a)};
_.Wb=function(a,b,c){if(0==a.a){a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;var d;a:{var e=c,f=a.F,h=a.v;if(e instanceof _.Xb)_.gc(e,_.$b(f||_.na,h||null,a)),d=!0;else if(_.Vb(e))e.then(f,h,a),d=!0;else{if(_.ga(e))try{var l=e.then;if(_.ia(l)){hc(e,l,f,h,a);d=!0;break a}}catch(p){h.call(a,p);d=!0;break a}d=!1}}d||(a.j=c,a.a=b,a.c=null,fc(a),3!=b||c instanceof _.bc||ic(a,c))}};
hc=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},l=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,l)}catch(p){l(p)}};fc=function(a){a.D||(a.D=!0,ob(a.w,a))};dc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.g=null);return b};_.Xb.prototype.w=function(){for(var a=null;a=dc(this);)ec(this,a,this.a,this.j);this.D=!1};
ec=function(a,b,c,d){if(3==c&&b.b&&!b.c)for(;a&&a.h;a=a.c)a.h=!1;if(b.a)b.a.c=null,jc(b,c,d);else try{b.c?b.g.call(b.context):jc(b,c,d)}catch(e){kc.call(null,e)}Ua(Zb,b)};jc=function(a,b,c){2==b?a.g.call(a.context,c):a.b&&a.b.call(a.context,c)};ic=function(a,b){a.h=!0;ob(function(){a.h&&kc.call(null,b)})};kc=db;_.bc=function(a){_.pa.call(this,a)};_.q(_.bc,_.pa);_.bc.prototype.name="cancel";
var lc=!_.Fb||9<=_.Tb,mc=_.Fb&&!_.Rb("9");!_.Ib||_.Rb("528");_.Hb&&_.Rb("1.9b")||_.Fb&&_.Rb("8")||Eb&&_.Rb("9.5")||_.Ib&&_.Rb("528");_.Hb&&!_.Rb("8")||_.Fb&&_.Rb("9");_.A=function(a,b){this.type="undefined"!=typeof _.nc&&a instanceof _.nc?String(a):a;this.b=this.target=b;this.c=!1;this.Rc=!0};_.A.prototype.h=function(){this.c=!0};_.A.prototype.g=function(){this.Rc=!1};var oc=function(a){oc[" "](a);return a};oc[" "]=_.na;_.pc=function(a,b){try{return oc(a[b]),!0}catch(c){}return!1};var qc=function(a,b){_.A.call(this,a?a.type:"");this.b=this.target=null;this.D=this.clientY=this.clientX=0;this.a=this.state=null;if(a){this.type=a.type;var c=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;var d=a.relatedTarget;d&&_.Hb&&_.pc(d,"nodeName");null===c?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY):(this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=void 0!==c.clientY?c.clientY:c.pageY);
this.D=a.keyCode||0;this.state=a.state;this.a=a;a.defaultPrevented&&this.g()}};_.q(qc,_.A);qc.prototype.h=function(){qc.I.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};qc.prototype.g=function(){qc.I.g.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,mc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var rc,tc;rc="closure_listenable_"+(1E6*Math.random()|0);_.sc=function(a){return!(!a||!a[rc])};tc=0;var uc=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.Xa=!!d;this.vb=e;this.key=++tc;this.removed=this.mb=!1},vc=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.vb=null};var wc=function(a){this.src=a;this.a={};this.b=0},xc;wc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=xc(a,b,d,e);-1<h?(b=a[h],c||(b.mb=!1)):(b=new uc(b,this.src,f,!!d,e),b.mb=c,a.push(b));return b};wc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=xc(e,b,c,d);return-1<b?(vc(e[b]),_.wa.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var yc=function(a,b){var c=b.type;c in a.a&&_.Fa(a.a[c],b)&&(vc(b),0==a.a[c].length&&(delete a.a[c],a.b--))};wc.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,vc(d[e]);delete this.a[c];this.b--}return b};_.zc=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=xc(a,c,d,e));return-1<b?a[b]:null};xc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.Xa==!!c&&f.vb==d)return e}return-1};
var Ac,Bc,Cc,Hc,Ic,Nc,Mc,Jc,Oc;Ac="closure_lm_"+(1E6*Math.random()|0);Bc={};Cc=0;_.Dc=function(a,b,c,d,e){if(_.v(b)){for(var f=0;f<b.length;f++)_.Dc(a,b[f],c,d,e);return null}c=_.Ec(c);return _.sc(a)?a.listen(b,c,d,e):_.Fc(a,b,c,!1,d,e)};
_.Fc=function(a,b,c,d,e,f){if(!b)throw Error("j");var h=!!e,l=_.Gc(a);l||(a[Ac]=l=new wc(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Hc();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,h);else if(a.attachEvent)a.attachEvent(Ic(b.toString()),d);else throw Error("k");Cc++;return c};Hc=function(){var a=Jc,b=lc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.Kc=function(a,b,c,d,e){if(_.v(b))for(var f=0;f<b.length;f++)_.Kc(a,b[f],c,d,e);else c=_.Ec(c),_.sc(a)?a.dc(b,c,d,e):a&&(a=_.Gc(a))&&(b=_.zc(a,b,c,!!d,e))&&_.Lc(b)};_.Lc=function(a){if(!_.ja(a)&&a&&!a.removed){var b=a.src;if(_.sc(b))yc(b.pa,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Xa):b.detachEvent&&b.detachEvent(Ic(c),d);Cc--;(c=_.Gc(b))?(yc(c,a),0==c.b&&(c.src=null,b[Ac]=null)):vc(a)}}};Ic=function(a){return a in Bc?Bc[a]:Bc[a]="on"+a};
Nc=function(a,b,c,d){var e=!0;if(a=_.Gc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Xa==c&&!f.removed&&(f=Mc(f,d),e=e&&!1!==f)}return e};Mc=function(a,b){var c=a.listener,d=a.vb||a.src;a.mb&&_.Lc(a);return c.call(d,b)};
Jc=function(a,b){if(a.removed)return!0;if(!lc){var c=b||_.oa("window.event"),d=new qc(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.b;f;f=f.parentNode)c.push(f);for(var f=a.type,l=c.length-1;!d.c&&0<=l;l--){d.b=c[l];var p=Nc(c[l],f,!0,d),e=e&&p}for(l=0;!d.c&&l<c.length;l++)d.b=c[l],p=Nc(c[l],f,!1,d),e=e&&p}return e}return Mc(a,new qc(b,this))}; _.Gc=function(a){a=a[Ac];return a instanceof wc?a:null};Oc="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Ec=function(a){if(_.ia(a))return a;a[Oc]||(a[Oc]=function(b){return a.handleEvent(b)});return a[Oc]};Ya(function(a){Jc=a(Jc)});
_.B=function(){_.z.call(this);this.pa=new wc(this);this.na=this;this.w=null};_.q(_.B,_.z);_.B.prototype[rc]=!0;_.B.prototype.F=function(a){this.w=a};_.B.prototype.addEventListener=function(a,b,c,d){_.Dc(this,a,b,c,d)};_.B.prototype.removeEventListener=function(a,b,c,d){_.Kc(this,a,b,c,d)};
_.C=function(a,b){var c,d=a.w;if(d)for(c=[];d;d=d.w)c.push(d);var d=a.na,e=b,f=e.type||e;if(_.t(e))e=new _.A(e,d);else if(e instanceof _.A)e.target=e.target||d;else{var h=e,e=new _.A(f,d);_.Sa(e,h)}var h=!0,l;if(c)for(var p=c.length-1;!e.c&&0<=p;p--)l=e.b=c[p],h=l.V(f,!0,e)&&h;e.c||(l=e.b=d,h=l.V(f,!0,e)&&h,e.c||(h=l.V(f,!1,e)&&h));if(c)for(p=0;!e.c&&p<c.length;p++)l=e.b=c[p],h=l.V(f,!1,e)&&h};_.g=_.B.prototype;_.g.L=function(){_.B.I.L.call(this);this.pa&&this.pa.removeAll(void 0);this.w=null};
_.g.listen=function(a,b,c,d){return this.pa.add(String(a),b,!1,c,d)};_.g.rb=function(a,b,c,d){return this.pa.add(String(a),b,!0,c,d)};_.g.dc=function(a,b,c,d){return this.pa.remove(String(a),b,c,d)};_.g.V=function(a,b,c){a=this.pa.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Xa==b){var h=f.listener,l=f.vb||f.src;f.mb&&yc(this.pa,f);d=!1!==h.call(l,c)&&d}}return d&&0!=c.Rc};
var Pc=function(){};Pc.prototype.a=null;var Rc=function(a){var b;(b=a.a)||(b={},Qc(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Sc,Tc=function(){};_.q(Tc,Pc);var Uc=function(a){return(a=Qc(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},Qc=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("l");}return a.b};Sc=new Tc;
_.Vc=function(a,b,c){if(_.ia(a))c&&(a=(0,_.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.r)(a.handleEvent,a);else throw Error("m");return 2147483647<b?-1:_.k.setTimeout(a,b||0)};_.Wc=function(a){_.k.clearTimeout(a)};var Xc,Yc,ad;Xc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.$c=function(a){if(Yc){Yc=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.Zc(c))&&c!=b.hostname)throw Yc=!0,Error();}}return a.match(Xc)};Yc=_.Ib;_.Zc=function(a){return(a=_.$c(a)[3]||null)?(0,window.decodeURI)(a):a}; ad=function(a,b){if(a)for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,h=null;0<=e?(f=c[d].substring(0,e),h=c[d].substring(e+1)):f=c[d];b(f,h?(0,window.decodeURIComponent)(h.replace(/\+/g," ")):"")}};
var cd,gd,ld,nd,md,id,od;_.bd=function(a){_.B.call(this);this.Z=new _.y;this.C=a||null;this.b=!1;this.A=this.a=null;this.N="";this.g=0;this.h="";this.c=this.K=this.l=this.G=!1;this.j=0;this.v=null;this.$="";this.W=this.ga=!1};_.q(_.bd,_.B);cd=/^https?$/i;_.dd=["POST","PUT"];_.ed=[];_.fd=function(a,b,c,d,e,f,h){var l=new _.bd;_.ed.push(l);b&&l.listen("complete",b);l.rb("ready",l.ja);f&&(l.j=Math.max(0,f));h&&(l.ga=h);l.send(a,c,d,e)};_.bd.prototype.ja=function(){this.T();_.Fa(_.ed,this)};
_.bd.prototype.send=function(a,b,c,d){if(this.a)throw Error("n`"+this.N+"`"+a);b=b?b.toUpperCase():"GET";this.N=a;this.h="";this.g=0;this.G=!1;this.b=!0;this.a=this.C?Uc(this.C):Uc(Sc);this.A=this.C?Rc(this.C):Rc(Sc);this.a.onreadystatechange=(0,_.r)(this.da,this);try{this.K=!0,this.a.open(b,String(a),!0),this.K=!1}catch(e){gd(this,e);return}a=c||"";var f=this.Z.clone();d&&_.Db(d,function(a,b){f.set(b,a)});d=_.Da(f.ba(),hd);c=_.k.FormData&&a instanceof _.k.FormData;!_.Ea(_.dd,b)||d||c||f.set("Content-Type",
"application/x-www-form-urlencoded;charset=utf-8");f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.$&&(this.a.responseType=this.$);"withCredentials"in this.a&&(this.a.withCredentials=this.ga);try{id(this),0<this.j&&((this.W=jd(this.a))?(this.a.timeout=this.j,this.a.ontimeout=(0,_.r)(this.fa,this)):this.v=_.Vc(this.fa,this.j,this)),this.l=!0,this.a.send(a),this.l=!1}catch(h){gd(this,h)}};
var jd=function(a){return _.Fb&&_.Rb(9)&&_.ja(a.timeout)&&_.n(a.ontimeout)},hd=function(a){return"content-type"==a.toLowerCase()};_.bd.prototype.fa=function(){"undefined"!=typeof _.aa&&this.a&&(this.h="Timed out after "+this.j+"ms, aborting",this.g=8,_.C(this,"timeout"),_.kd(this,8))};gd=function(a,b){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.h=b;a.g=5;ld(a);md(a)};ld=function(a){a.G||(a.G=!0,_.C(a,"complete"),_.C(a,"error"))};
_.kd=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.g=b||7,_.C(a,"complete"),_.C(a,"abort"),md(a))};_.bd.prototype.L=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),md(this,!0));_.bd.I.L.call(this)};_.bd.prototype.da=function(){this.R||(this.K||this.l||this.c?nd(this):this.O())};_.bd.prototype.O=function(){nd(this)};
nd=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.A[1]||4!=od(a)||2!=_.pd(a)))if(a.l&&4==od(a))_.Vc(a.da,0,a);else if(_.C(a,"readystatechange"),4==od(a)){a.b=!1;try{if(_.qd(a))_.C(a,"complete"),_.C(a,"success");else{a.g=6;var b;try{b=2<od(a)?a.a.statusText:""}catch(c){b=""}a.h=b+" ["+_.pd(a)+"]";ld(a)}}finally{md(a)}}};md=function(a,b){if(a.a){id(a);var c=a.a,d=a.A[0]?_.na:null;a.a=null;a.A=null;b||_.C(a,"ready");try{c.onreadystatechange=d}catch(e){}}};
id=function(a){a.a&&a.W&&(a.a.ontimeout=null);_.ja(a.v)&&(_.Wc(a.v),a.v=null)};_.qd=function(a){var b=_.pd(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=_.$c(String(a.N))[1]||null,!a&&_.k.self&&_.k.self.location&&(a=_.k.self.location.protocol,a=a.substr(0,a.length-1)),b=!cd.test(a?a.toLowerCase():"");c=b}return c};od=function(a){return a.a?a.a.readyState:0};_.pd=function(a){try{return 2<od(a)?a.a.status:-1}catch(b){return-1}}; Ya(function(a){_.bd.prototype.O=a(_.bd.prototype.O)});
var yd,Gd,zd,Bd,Ad,Ed,Cd,Hd;_.D=function(a,b){this.b=this.j=this.h="";this.g=null;this.l=this.a="";this.D=!1;var c;a instanceof _.D?(this.D=_.n(b)?b:a.D,_.rd(this,a.h),this.j=a.j,this.b=a.b,_.sd(this,a.g),_.td(this,a.a),_.ud(this,a.c.clone()),_.vd(this,a.l)):a&&(c=_.$c(String(a)))?(this.D=!!b,_.rd(this,c[1]||"",!0),this.j=_.wd(c[2]||""),this.b=_.wd(c[3]||"",!0),_.sd(this,c[4]),_.td(this,c[5]||"",!0),_.ud(this,c[6]||"",!0),_.vd(this,c[7]||"",!0)):(this.D=!!b,this.c=new _.xd(null,0,this.D))};
_.D.prototype.toString=function(){var a=[],b=this.h;b&&a.push(yd(b,zd,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(yd(b,zd,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.g,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(yd(c,"/"==c.charAt(0)?Ad:Bd,!0));(c=this.c.toString())&&a.push("?",c);(c=this.l)&&a.push("#",yd(c,Cd));return a.join("")};_.D.prototype.clone=function(){return new _.D(this)};
_.rd=function(a,b,c){a.h=c?_.wd(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};_.sd=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("p`"+b);a.g=b}else a.g=null};_.td=function(a,b,c){a.a=c?_.wd(b,!0):b};_.ud=function(a,b,c){b instanceof _.xd?(a.c=b,Dd(a.c,a.D)):(c||(b=yd(b,Ed)),a.c=new _.xd(b,0,a.D))};_.vd=function(a,b,c){a.l=c?_.wd(b):b;return a};_.Fd=function(a){return a instanceof _.D?a.clone():new _.D(a,void 0)};
_.wd=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};yd=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,Gd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};Gd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};zd=/[#\/\?@]/g;Bd=/[\#\?:]/g;Ad=/[\#\?]/g;Ed=/[\#\?@]/g;Cd=/#/g;_.xd=function(a,b,c){this.b=this.a=null;this.c=a||null;this.g=!!c};
Hd=function(a){a.a||(a.a=new _.y,a.b=0,a.c&&ad(a.c,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};_.g=_.xd.prototype;_.g.qa=function(){Hd(this);return this.b};_.g.add=function(a,b){Hd(this);this.c=null;a=Id(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b++;return this};_.g.remove=function(a){Hd(this);a=Id(this,a);return _.Bb(this.a,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};_.g.clear=function(){this.a=this.c=null;this.b=0};
_.g.ia=function(){Hd(this);return 0==this.b};var Jd=function(a,b){Hd(a);b=Id(a,b);return _.Bb(a.a,b)};_.xd.prototype.ba=function(){Hd(this);for(var a=this.a.U(),b=this.a.ba(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.xd.prototype.U=function(a){Hd(this);var b=[];if(_.t(a))Jd(this,a)&&(b=_.Ga(b,this.a.get(Id(this,a))));else{a=this.a.U();for(var c=0;c<a.length;c++)b=_.Ga(b,a[c])}return b};
_.xd.prototype.set=function(a,b){Hd(this);this.c=null;a=Id(this,a);Jd(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b++;return this};_.xd.prototype.get=function(a,b){var c=a?this.U(a):[];return 0<c.length?String(c[0]):b};_.Kd=function(a,b,c){a.remove(b);0<c.length&&(a.c=null,a.a.set(Id(a,b),_.Ha(c)),a.b+=c.length)};
_.xd.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.ba(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.U(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}return this.c=a.join("&")};_.xd.prototype.clone=function(){var a=new _.xd;a.c=this.c;this.a&&(a.a=this.a.clone(),a.b=this.b);return a}; var Id=function(a,b){var c=String(b);a.g&&(c=c.toLowerCase());return c},Dd=function(a,b){b&&!a.g&&(Hd(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.Kd(this,e,a))},a));a.g=b};
var Ld,Md,Nd,Od,Qd;Ld=_.x("Firefox");Md=xb()||_.x("iPod");Nd=_.x("iPad");Od=_.x("Android")&&!(cb()||_.x("Firefox")||bb()||_.x("Silk"));_.Pd=cb();Qd=_.x("Safari")&&!(cb()||_.x("Coast")||bb()||_.x("Edge")||_.x("Silk")||_.x("Android"))&&!(xb()||_.x("iPad")||_.x("iPod"));
var Rd;Rd=function(a){return(a=a.exec(_.Za))?a[1]:""};_.Sd=function(){if(Ld)return Rd(/Firefox\/([0-9.]+)/);if(_.Fb||Eb)return Pb;if(_.Pd)return Rd(/Chrome\/([0-9.]+)/);if(Qd&&!(xb()||_.x("iPad")||_.x("iPod")))return Rd(/Version\/([0-9.]+)/);if(Md||Nd){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Za))return a[1]+"."+a[2]}else if(Od)return(a=Rd(/Android\s+([0-9.]+)/))?a:Rd(/Version\/([0-9.]+)/);return""}();
var Td=function(a){this.b=a;this.c="empty";this.a=null};var Ud=function(){};var Vd=function(){};_.q(Vd,Ud);Vd.prototype.qa=function(){var a=0;vb(this.xa(!0),function(){a++});return a};Vd.prototype.clear=function(){var a=wb(this.xa(!0)),b=this;(0,_.w)(a,function(a){b.remove(a)})};var Wd=function(a){this.a=a};_.q(Wd,Vd);_.g=Wd.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.t(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.qa=function(){return this.a.length};_.g.xa=function(a){var b=0,c=this.a,d=new tb;d.next=function(){if(b>=c.length)throw sb;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.t(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var Xd=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.q(Xd,Wd);var Zd=function(a,b){this.c=a;this.a=[];this.b=null;b&&(this.b=new Xd);if(null!=this.b&&this.b.isAvailable()){var c=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate");if(null!=c)try{this.a=Ia(c)||[]}catch(d){}}c=!1;_.v(this.a)||(this.a=[],c=!0);for(;this.a.length>this.c;)this.a.shift(),c=!0;c&&Yd(this)},Yd=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.La(a.a))}catch(b){}};
_.$d=function(a){_.z.call(this);this.a=a;this.c=!1};_.q(_.$d,_.z);_.$d.prototype.setEnabled=function(a){this.c=a};var E=function(a){_.$d.call(this,a);this.v=100;this.j={};this.aa=null;this.l="";this.K=!0;this.g=10;this.b=null;this.F=!1};_.q(E,_.$d);E.prototype.G=function(a){this.K=a;return this};E.prototype.setUseLocalStorage=E.prototype.G;E.prototype.W=function(a){this.g=Math.min(a,100);return this};E.prototype.setMaxErrorsPerHour=E.prototype.W;E.prototype.C=function(a){this.v=a;return this};E.prototype.setGlobalSampling=E.prototype.C;E.prototype.w=function(a,b){this.j[a]=b;return this};
E.prototype.addPerErrorMessageSampling=E.prototype.w;E.prototype.Z=function(a){this.aa=a;return this};E.prototype.setCallback=E.prototype.Z;E.prototype.$=function(a){this.l=a;return this};E.prototype.setClientId=E.prototype.$;E.prototype.enable=function(){if(this.c)return!1;this.h=window.onerror;window.onerror=this.O.bind(this);this.setEnabled(!0);return!0};E.prototype.enable=E.prototype.enable;
E.prototype.A=function(a,b,c,d,e){var f=_.Fd(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.ia(this.aa)||this.aa(f.a,a,b,c,d,e)){h=Object.keys(this.j);for(var l=100,p=0;p<h.length;++p){var u=h[p];(new RegExp(u)).test(a)&&(l=this.j[u])}if(h=(100*Math.random()).toFixed(6)>=this.v*l/100?!1:!0){0<=this.g&&null===this.b&&(this.b=new Zd(this.g,this.K));if(null===this.b)h=0;else{a:{h=this.b;l=(0,_.m)();if(h.a.length==h.c)if(h.a[0]<l-36E5)h.a.shift();else{h=!1;break a}h.a.push(l);
Yd(h);h=!0}h=!h}h=!h}}h&&(h=ae(this,f,a,b,c,d),h.product=this.a.b,h.version=this.a.c,be(this,"https://clients2.google.com/webmon",ce(h),de(a,null!=e?_.ta(e.stack):"")),this.F&&(b=ae(this,f,a,b,c,d),b.prod=this.a.b,b.ver=this.a.c,be(this,"https://clients2.google.com/cr/staging_report",ce(b),de(a,null!=e?_.ta(e.stack):"")),e={product:this.a.b,url:f.a,js_errors_count:"1"},f=_.ta(this.a.a),_.ra(f)||(e.version=f),be(this,"https://clients2.google.com/cr/staging_perf",ce(e))))};E.prototype.reportError=E.prototype.A;
E.prototype.O=function(a,b,c,d,e){this.A(a,b,c,d,e);null!=this.h&&_.ia(this.h)&&this.h(a,b,c,d,e)};
var ae=function(a,b,c,d,e,f){b=b.a;var h;h="Other";Eb?h="Opera":_.Fb?h="Internet Explorer":Ld?h="Firefox":_.Pd?h="Chrome":Qd&&(h="Safari");var l=_.x("CrOS")?"Chrome OS":_.x("Linux")?"Linux":_.yb()?"Windows":_.x("Android")?"Android":xb()?"iPhone":_.x("iPad")?"iPad":_.x("iPod")?"iPod":_.x("Macintosh")?"Mac":"Unknown",p=_.Za,u="";_.yb()?(u=/Windows (?:NT|Phone) ([0-9.]+)/,u=(p=u.exec(p))?p[1]:"0.0"):xb()||_.x("iPad")||_.x("iPod")?(u=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,u=(p=u.exec(p))&&p[1].replace(/_/g,
".")):_.x("Macintosh")?(u=/Mac OS X ([0-9_.]+)/,u=(p=u.exec(p))?p[1].replace(/_/g,"."):"10"):_.x("Android")?(u=/Android\s+([^\);]+)(\)|;)/,u=(p=u.exec(p))&&p[1]):_.x("CrOS")&&(u=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,u=(p=u.exec(p))&&p[1]);c={url:b,type:"JavascriptError",error_message:c,browser:h,browser_version:_.Sd,os:l,os_version:u||""};null!=a.a.a&&(c.channel=a.a.a);_.ra(a.l)||(c.guid=a.l);null!=d&&(c.src=d);null!=e&&(c.line=e);null!=f&&(c.column=f);return c},de=function(a,b){if(_.ra(a))return b;
var c=b.split("\n");-1<c[0].indexOf(a)&&(c.splice(0,1),b=c.join("\n"));return b},ce=function(a){var b="",c;for(c in a)b+=_.ra(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},be=function(a,b,c,d){d=d||"";var e=_.ra(d)?{}:{"Content-Type":"text/plain"};_.fd(b+c,a.N.bind(a,b),"POST",d,e,6E4,!0)};E.prototype.N=function(a,b){_.qd(b.target)};
var ee=function(a){_.z.call(this);this.ca=new Td(a);this.a={}};_.q(ee,_.z);_.fa("webmonitoring.Monitoring",ee);ee.prototype.c=function(a){this.ca.c=a;return this};ee.prototype.setVersion=ee.prototype.c;ee.prototype.g=function(a){this.ca.a=a;return this};ee.prototype.setChannel=ee.prototype.g;ee.prototype.b=function(){null!=this.a[2]||(this.a[2]=new E(this.ca));return this.a[2]};ee.prototype.createJsErrorsReporter=ee.prototype.b;
var fe=function(a){ee.call(this,a)};_.q(fe,ee);fe.prototype.c=function(a){return fe.I.c.call(this,a)};fe.prototype.g=function(a){return fe.I.g.call(this,a)};fe.prototype.b=function(){var a=fe.I.b.call(this);a.F=!0;return a};_.ge=function(){ee.call(this,"ultraviolet");this.c(window.chrome.runtime.id)};_.q(_.ge,fe);_.ma(_.ge);_.he=function(){_.ge.Ga().b().G(!1).C(100).w("Script error.",0).enable()};_.ge.Ga();
}catch(e){_._DumpException(e)}
try{
_.Mh="https://support.google.com/chrome/answer/185277?hl="+window.chrome.i18n.getMessage("@@ui_locale");window.chrome.i18n.getMessage("@@ui_locale");_.Nh="https://support.google.com/hangouts/?p=chrome_desktop_app_outdated&hl="+window.chrome.i18n.getMessage("@@ui_locale");

}catch(e){_._DumpException(e)}
try{
_.fa("_DumpException",function(a){window.console.error(a.stack)});_.he();window.open("","centralRoster")._OnUiFrameReady(window);
}catch(e){_._DumpException(e)}
}).call(this,this.default_uiframehook);
// Google Inc.
