"use strict";this.default_datachannel=this.default_datachannel||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da,ea;_.n=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ud=function(a,c,f){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[c].apply(a,g)}};
_.ga=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.q=function(a,b,c){_.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.q.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==ea(a)};_.ka=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.la=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ma=function(a){return"array"==ea(a)};_.oa=function(){};_.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}; _.p(_.pa,Error);_.pa.prototype.name="CustomError";
var qa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ta=function(a,b){for(var c=0,d=qa(String(a)).split("."),e=qa(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",r=e[g]||"",D=RegExp("(\\d*)(\\D*)","g"),O=RegExp("(\\d*)(\\D*)","g");do{var fa=D.exec(l)||["","",""],Q=O.exec(r)||["","",""];if(0==fa[0].length&&0==Q[0].length)break;c=sa(0==fa[1].length?0:(0,window.parseInt)(fa[1],10),0==Q[1].length?0:(0,window.parseInt)(Q[1], 10))||sa(0==fa[2].length,0==Q[2].length)||sa(fa[2],Q[2])}while(0==c)}return c},sa=function(a,b){return a<b?-1:a>b?1:0};
_.u=Array.prototype;_.ua=_.u.indexOf?function(a,b,c){return _.u.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.va=_.u.lastIndexOf?function(a,b,c){return _.u.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.v=_.u.forEach?function(a,b,c){_.u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.wa=_.u.filter?function(a,b,c){return _.u.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var r=g[l];b.call(c,r,l,a)&&(e[f++]=r)}return e};_.xa=_.u.map?function(a,b,c){return _.u.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.ya=_.u.reduce?function(a,b,c,d){d&&(b=(0,_.q)(b,d));return _.u.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.v)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.za=_.u.some?function(a,b,c){return _.u.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Aa=function(a,b){var c=(0,_.ua)(a,b),d;(d=0<=c)&&_.u.splice.call(a,c,1);return d};
_.Ba=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Da,Fa;_.Ca=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Da=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ea=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Fa=function(a){var b=arguments.length;if(1==b&&_.ma(arguments[0]))return Fa.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var Ha;_.w=function(){};_.x=function(a,b,c,d){a.a=null;b||(b=c?[c]:[]);a.A=c?String(c):void 0;a.c=0===c?-1:0;a.P=b;a:{if(a.P.length&&(b=a.P.length-1,(c=a.P[b])&&"object"==typeof c&&!_.ma(c))){a.l=b-a.c;a.b=c;break a}a.l=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.l?(c+=a.c,a.P[c]=a.P[c]||_.Ga):a.b[c]=a.b[c]||_.Ga};_.Ga=[];_.y=function(a,b){if(b<a.l){var c=b+a.c,d=a.P[c];return d===_.Ga?a.P[c]=[]:d}d=a.b[b];return d===_.Ga?a.b[b]=[]:d};_.w.prototype.toString=function(){return this.P.toString()}; _.z=function(a,b){Ha[a]=b;b.messageId=a};Ha={};
Fa("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));var Ia=function(){this.b="";this.a=null},Ja=function(a){var b=new Ia;b.b=a;b.a=0};Ja("<!DOCTYPE html>");Ja("");_.Ka="StopIteration"in _.k?_.k.StopIteration:{message:"StopIteration",stack:""};_.La=function(){};_.La.prototype.next=function(){throw _.Ka;};_.La.prototype.ia=function(){return this};a:{var Na=_.k.navigator;if(Na){var Oa=Na.userAgent;if(Oa){_.Ma=Oa;break a}}_.Ma=""}var A=function(a){return-1!=_.Ma.indexOf(a)};var Pa=function(){return A("Opera")||A("OPR")},Qa=function(){return A("Edge")||A("Trident")||A("MSIE")},Ra=function(){return(A("Chrome")||A("CriOS"))&&!Pa()&&!Qa()};var Sa=function(){return A("Edge")};var Ta=function(){return A("iPhone")&&!A("iPod")&&!A("iPad")};_.B=function(a,b){this.b={};this.a=[];this.l=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("g");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.B?(c=a.S(),d=a.I()):(c=_.Ea(a),d=Da(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.B.prototype.Y=function(){return this.c};_.B.prototype.I=function(){Ua(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.B.prototype.S=function(){Ua(this);return this.a.concat()};
_.Wa=function(a,b){return Va(a.b,b)};_.B.prototype.T=function(){return 0==this.c};_.B.prototype.clear=function(){this.b={};this.l=this.c=this.a.length=0};_.B.prototype.remove=function(a){return Va(this.b,a)?(delete this.b[a],this.c--,this.l++,this.a.length>2*this.c&&Ua(this),!0):!1};
var Ua=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Va(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Va(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.B.prototype;_.h.get=function(a,b){return Va(this.b,a)?this.b[a]:b};_.h.set=function(a,b){Va(this.b,a)||(this.c++,this.a.push(a),this.l++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.S(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.h.clone=function(){return new _.B(this)};_.h.ia=function(a){Ua(this);var b=0,c=this.l,d=this,e=new _.La;e.next=function(){if(c!=d.l)throw Error("h");if(b>=d.a.length)throw _.Ka;var e=d.a[b++];return a?e:d.b[e]};return e};var Va=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Xa=function(a){if("function"==typeof a.I)return a.I();if(_.t(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Da(a)};
_.Ya=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.la(a)||_.t(a))(0,_.v)(a,b,c);else{var d;if("function"==typeof a.S)d=a.S();else if("function"!=typeof a.I)if(_.la(a)||_.t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Ea(a);else d=void 0;for(var e=_.Xa(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};
var bb,db,fb,gb,hb,jb,kb,lb;_.Za=Pa();_.C=Qa();_.$a=A("Gecko")&&!(-1!=_.Ma.toLowerCase().indexOf("webkit")&&!Sa())&&!(A("Trident")||A("MSIE"))&&!Sa();_.ab=-1!=_.Ma.toLowerCase().indexOf("webkit")&&!Sa();bb=_.k.navigator||null;_.cb=bb&&bb.platform||"";db=function(){var a=_.Ma;if(_.$a)return/rv\:([^\);]+)(\)|;)/.exec(a);if(_.C&&Sa())return/Edge\/([\d\.]+)/.exec(a);if(_.C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.ab)return/WebKit\/(\S+)/.exec(a)};
fb=function(){var a=_.k.document;return a?a.documentMode:void 0};gb=function(){if(_.Za&&_.k.opera){var a=_.k.opera.version;return _.ja(a)?a():a}var a="",b=db();b&&(a=b?b[1]:"");return _.C&&!Sa()&&(b=fb(),b>(0,window.parseFloat)(a))?String(b):a}();hb={};_.ib=function(a){return hb[a]||(hb[a]=0<=ta(gb,a))};jb=_.k.document;kb=fb();lb=!jb||!_.C||!kb&&Sa()?void 0:kb||("CSS1Compat"==jb.compatMode?(0,window.parseInt)(gb,10):5);
_.E=function(){this.J=this.J;this.l=this.l};_.E.prototype.J=!1;_.E.prototype.ub=function(){return this.J};_.E.prototype.K=function(){this.J||(this.J=!0,this.w())};_.G=function(a,b){_.mb(a,_.ha(_.F,b))};_.mb=function(a,b){a.J?b.call(void 0):(a.l||(a.l=[]),a.l.push(_.n(void 0)?(0,_.q)(b,void 0):b))};_.E.prototype.w=function(){if(this.l)for(;this.l.length;)this.l.shift()()};_.F=function(a){a&&"function"==typeof a.K&&a.K()};
_.nb=!_.C||_.C&&(Sa()||9<=lb);!_.$a&&!_.C||_.C&&_.C&&(Sa()||9<=lb)||_.$a&&_.ib("1.9.1");_.C&&_.ib("9");var ob=function(a){ob[" "](a);return a};ob[" "]=_.oa;_.pb=function(a,b){try{return ob(a[b]),!0}catch(c){}return!1};var qb,rb;qb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.tb=function(a){if(rb){rb=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.sb(c))&&c!=b.hostname)throw rb=!0,Error();}}return a.match(qb)};rb=_.ab;_.sb=function(a){return(a=_.tb(a)[3]||null)?(0,window.decodeURI)(a):a};
var ub=!_.C||_.C&&(Sa()||9<=lb),vb=_.C&&!_.ib("9");!_.ab||_.ib("528");_.$a&&_.ib("1.9b")||_.C&&_.ib("8")||_.Za&&_.ib("9.5")||_.ab&&_.ib("528");_.$a&&!_.ib("8")||_.C&&_.ib("9");_.H=function(a,b){this.type=a;this.a=this.target=b;this.jc=!0};_.H.prototype.b=function(){this.jc=!1};var wb=function(a,b){_.H.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&_.$a&&_.pb(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};_.p(wb,_.H); wb.prototype.b=function(){wb.C.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,vb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var xb,zb;xb="closure_listenable_"+(1E6*Math.random()|0);_.yb=function(a){return!(!a||!a[xb])};zb=0;var Ab=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.Qa=!!d;this.Xa=e;this.key=++zb;this.removed=this.Pa=!1},Bb=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Xa=null};var Cb=function(a){this.src=a;this.a={};this.b=0};Cb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Db(a,b,d,e);-1<g?(b=a[g],c||(b.Pa=!1)):(b=new Ab(b,this.src,f,!!d,e),b.Pa=c,a.push(b));return b};Cb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Db(e,b,c,d);return-1<b?(Bb(e[b]),_.u.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Eb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.Aa(a.a[c],b);d&&(Bb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};Cb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Bb(d[e]);delete this.a[c];this.b--}return b}; var Fb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Db(a,c,d,e));return-1<b?a[b]:null},Db=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.Qa==!!c&&f.Xa==d)return e}return-1};
var Gb,Hb,Ib,Ob,Pb,Ub,Tb,Qb,Nb,Vb;Gb="closure_lm_"+(1E6*Math.random()|0);Hb={};Ib=0;_.Jb=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.Jb(a,b[f],c,d,e);return null}c=_.Kb(c);return _.yb(a)?a.listen(b,c,d,e):_.Lb(a,b,c,!1,d,e)};
_.Lb=function(a,b,c,d,e,f){if(!b)throw Error("k");var g=!!e,l=Nb(a);l||(a[Gb]=l=new Cb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Ob();c.proxy=d;d.src=a;d.listener=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Pb(b.toString()),d);Ib++;return c};Ob=function(){var a=Qb,b=ub?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.Rb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)_.Rb(a,b[f],c,d,e);else c=_.Kb(c),_.yb(a)?a.Bb(b,c,d,e):a&&(a=Nb(a))&&(b=Fb(a,b,c,!!d,e))&&_.Sb(b)};_.Sb=function(a){if(_.ka(a)||!a||a.removed)return!1;var b=a.src;if(_.yb(b))return Eb(b.X,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Qa):b.detachEvent&&b.detachEvent(Pb(c),d);Ib--;(c=Nb(b))?(Eb(c,a),0==c.b&&(c.src=null,b[Gb]=null)):Bb(a);return!0};Pb=function(a){return a in Hb?Hb[a]:Hb[a]="on"+a};
Ub=function(a,b,c,d){var e=!0;if(a=Nb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Qa==c&&!f.removed&&(f=Tb(f,d),e=e&&!1!==f)}return e};Tb=function(a,b){var c=a.listener,d=a.Xa||a.src;a.Pa&&_.Sb(a);return c.call(d,b)};
Qb=function(a,b){if(a.removed)return!0;if(!ub){var c;if(!(c=b))a:{c=["window","event"];for(var d=_.k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new wb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--){c.a=e[l];var r=Ub(e[l],f,!0,c),d=d&&r}for(l=0;l<e.length;l++)c.a=e[l],r=Ub(e[l],
f,!1,c),d=d&&r}return d}return Tb(a,new wb(b,this))};Nb=function(a){a=a[Gb];return a instanceof Cb?a:null};Vb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Kb=function(a){if(_.ja(a))return a;a[Vb]||(a[Vb]=function(b){return a.handleEvent(b)});return a[Vb]};
_.Wb=function(a){_.x(this,a,"h_cc",null)};_.p(_.Wb,_.w);_.z("h_cc",_.Wb);_.Wb.prototype.ba=function(){return _.y(this,19)};_.I=function(a){_.E.call(this);this.M=a;this.h={}};_.p(_.I,_.E);var Xb=[];_.I.prototype.listen=function(a,b,c,d){return _.Yb(this,a,b,c,d)};_.Yb=function(a,b,c,d,e,f){_.ma(c)||(c&&(Xb[0]=c.toString()),c=Xb);for(var g=0;g<c.length;g++){var l=_.Jb(b,c[g],d||a.handleEvent,e||!1,f||a.M||a);if(!l)break;a.h[l.key]=l}return a};
_.I.prototype.Bb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)this.Bb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.M||this,c=_.Kb(c),d=!!d,b=_.yb(a)?Fb(a.X,String(b),c,d,e):a?(a=Nb(a))?Fb(a,b,c,d,e):null:null,b&&(_.Sb(b),delete this.h[b.key]);return this};_.I.prototype.removeAll=function(){_.Ca(this.h,_.Sb);this.h={}};_.I.prototype.w=function(){_.I.C.w.call(this);this.removeAll()};_.I.prototype.handleEvent=function(){throw Error("l");};
var Zb=function(a,b,c){this.l=c;this.c=a;this.f=b;this.b=0;this.a=null};Zb.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var $b=function(a,b){a.f(b);a.b<a.l&&(a.b++,b.next=a.a,a.a=b)};var ac,bc,cc;ac=function(a){_.k.setTimeout(function(){throw a;},0)};_.dc=function(a,b){var c=a;b&&(c=(0,_.q)(a,b));!_.ja(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(bc||(bc=cc()),bc(c)):_.k.setImmediate(c)};
cc=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!A("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.q)(function(a){if(("*"==d||
a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Qa()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Nb;c.Nb=null;a()}};return function(a){d.next={Nb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT"); b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};
var ec=function(){this.b=this.a=null},gc=new Zb(function(){return new fc},function(a){a.reset()},100);ec.prototype.add=function(a,b){var c=gc.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};ec.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var fc=function(){this.next=this.b=this.a=null};fc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};fc.prototype.reset=function(){this.next=this.b=this.a=null};
var lc=function(a,b){hc||ic();jc||(hc(),jc=!0);kc.add(a,b)},hc,ic=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve();hc=function(){a.then(mc)}}else hc=function(){_.dc(mc)}},jc=!1,kc=new ec,mc=function(){for(var a=null;a=kc.remove();){try{a.a.call(a.b)}catch(b){ac(b)}$b(gc,a)}jc=!1};
_.J=function(){_.E.call(this);this.X=new Cb(this);this.R=this;this.D=null};_.p(_.J,_.E);_.J.prototype[xb]=!0;_.h=_.J.prototype;_.h.addEventListener=function(a,b,c,d){_.Jb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Rb(this,a,b,c,d)};_.h.w=function(){_.J.C.w.call(this);this.X&&this.X.removeAll(void 0);this.D=null};_.h.listen=function(a,b,c,d){return this.X.add(String(a),b,!1,c,d)};_.h.Bb=function(a,b,c,d){return this.X.remove(String(a),b,c,d)}; _.h.ga=function(a,b,c){a=this.X.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Qa==b){var g=f.listener,l=f.Xa||f.src;f.Pa&&Eb(this.X,f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.jc};
var nc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},oc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var rc=function(a,b){this.a=0;this.h=void 0;this.l=this.b=this.c=null;this.f=this.g=!1;if(a==pc)qc(this,2,b);else try{var c=this;a.call(b,function(a){qc(c,2,a)},function(a){qc(c,3,a)})}catch(d){qc(this,3,d)}},sc=function(){this.next=this.c=this.b=this.l=this.a=null;this.f=!1},tc,uc,pc;sc.prototype.reset=function(){this.c=this.b=this.l=this.a=null;this.f=!1};tc=new Zb(function(){return new sc},function(a){a.reset()},100);uc=function(a,b,c){var d=tc.get();d.l=a;d.b=b;d.c=c;return d};pc=function(){};
_.wc=function(){var a,b=new rc(function(b){a=b});return new vc(b,a)};rc.prototype.then=function(a,b,c){return xc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};nc(rc);
var Ac=function(a){0==a.a&&lc(function(){var a=new yc(void 0);zc(this,a)},a)},zc=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.f||(d++,g.a==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.a&&1==d?zc(c,b):(f?(d=f,d.next==c.l&&(c.l=d),d.next=d.next.next):Bc(c),Cc(c,e,3,b)))}a.c=null}else qc(a,3,b)},Ec=function(a,b){a.b||2!=a.a&&3!=a.a||Dc(a);a.l?a.l.next=b:a.b=b;a.l=b},xc=function(a,b,c,d){var e=uc(null,null,null);e.a=new rc(function(a,g){e.l=b?function(c){try{var e=
b.call(d,c);a(e)}catch(D){g(D)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.n(e)&&b instanceof yc?g(b):a(e)}catch(D){g(D)}}:g});e.a.c=a;Ec(a,e);return e.a};rc.prototype.j=function(a){this.a=0;qc(this,2,a)};rc.prototype.u=function(a){this.a=0;qc(this,3,a)};
var qc=function(a,b,c){if(0==a.a){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(oc(c)){a.a=1;b=c;c=a.j;var d=a.u;b instanceof rc?Ec(b,uc(c||_.oa,d||null,a)):b.then(c,d,a);return}if(_.ia(c))try{if(d=c.then,_.ja(d)){Fc(a,c,d);return}}catch(e){b=3,c=e}}a.h=c;a.a=b;a.c=null;Dc(a);3!=b||c instanceof yc||Gc(a,c)}},Fc=function(a,b,c){a.a=1;var d=!1,e=function(b){d||(d=!0,a.j(b))},f=function(b){d||(d=!0,a.u(b))};try{c.call(b,e,f)}catch(g){f(g)}},Dc=function(a){a.g||(a.g=!0,lc(a.v,
a))},Bc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.l=null);return b};rc.prototype.v=function(){for(var a=null;a=Bc(this);)Cc(this,a,this.a,this.h);this.g=!1};
var Cc=function(a,b,c,d){if(3==c&&b.b&&!b.f)for(;a&&a.f;a=a.c)a.f=!1;if(b.a)b.a.c=null,Hc(b,c,d);else try{b.f?b.l.call(b.c):Hc(b,c,d)}catch(e){Ic.call(null,e)}$b(tc,b)},Hc=function(a,b,c){2==b?a.l.call(a.c,c):a.b&&a.b.call(a.c,c)},Gc=function(a,b){a.f=!0;lc(function(){a.f&&Ic.call(null,b)})},Ic=ac,yc=function(a){_.pa.call(this,a)};_.p(yc,_.pa);yc.prototype.name="cancel";var vc=function(a,b){this.b=a;this.a=b};
var Kc,Lc,Mc,Nc,Oc;_.Jc=A("Firefox");Kc=Ta()||A("iPod");Lc=A("iPad");Mc=A("Android")&&!(Ra()||A("Firefox")||Pa()||A("Silk"));Nc=Ra();Oc=A("Safari")&&!(Ra()||A("Coast")||Pa()||Qa()||A("Silk")||A("Android"))&&!(Ta()||A("iPad")||A("iPod"));_.Pc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Qc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.Rc=function(a,b){this.l=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.f=null;this.j=b||"u";this.a=this.h=null;this.g=[]};_.Rc.prototype.message=function(){var a={};a.i=this.a;a.m=this.g;a.r=this.j;a.o=this.h;a.s=this.b;a.st=this.c;a.d=this.f;a.dt=this.l;return a};_.Rc.prototype.message=_.Rc.prototype.message;
_.Sc=function(a,b){for(var c in b)switch(c){case "r":a.j=b[c];break;case "i":a.a=b[c];break;case "m":a.g=b[c];break;case "o":a.h=b[c];break;case "s":a.b=b[c];break;case "d":a.f=b[c];break;case "st":a.c=b[c];break;case "dt":a.l=b[c]}return a};_.Tc=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))};_.Uc=function(a,b){null!=b&&(a.a=b)};_.Vc=function(a,b){"object"==typeof b?a.g=b:a.g=[b]};_.Rc.prototype.source=function(){return this.b};_.Rc.prototype.target=function(){return this.f}; _.Rc.prototype.content=function(){return this.g};
_.Wc=function(a,b,c,d,e){_.E.call(this);this.b=a;this.Ma=b;this.a=typeof b;this.wb=c?c:!1;this.ea=!0;this.sb=d?d:!1;this.mb=e?e:!1};_.p(_.Wc,_.E);_.h=_.Wc.prototype;_.h.w=function(){_.Wc.C.w.call(this);this.b="";this.Ma=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.L=function(){return this.Ma};_.h.setEnabled=function(a){this.ea=a};
var Xc=function(a){return(a=a.exec(_.Ma))?a[1]:""},Yc=function(){if(_.Jc)return Xc(/Firefox\/([0-9.]+)/);if(_.C||_.Za)return gb;if(Nc)return Xc(/Chrome\/([0-9.]+)/);if(Oc&&!(Ta()||A("iPad")||A("iPod")))return Xc(/Version\/([0-9.]+)/);if(Kc||Lc){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Ma))return a[1]+"."+a[2]}else if(Mc)return(a=Xc(/Android\s+([0-9.]+)/))?a:Xc(/Version\/([0-9.]+)/);return""}();
_.$c=function(a){_.E.call(this);this.a=new _.B;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&_.Zc(this,a)};_.p(_.$c,_.E);_.ad=0<=ta(Yc,"23.0.1262.0")&&!_.Qc();_.$c.prototype.w=function(){_.$c.C.w.call(this);for(var a=this.a.S(),b=0;b<a.length;++b)_.F(this.a.get(a[b]));delete this.a};_.$c.prototype.getItem=function(a){return _.Wa(this.a,a)?this.a.get(a):null};
_.$c.prototype.setItem=function(a){this.a.set(a.id(),a)};_.Zc=function(a,b){for(var c in b){var d=b[c],e=null;_.Wa(a.a,c)?(e=a.a.get(c),e.Ma=d.value,d.changed&&(e.mb=d.changed)):(e=new _.Wc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.dd=function(){this.c=new _.B;this.a=null;this.b=!1;this.a=new bd;this.b=!0;_.cd(this)};_.dd.ra=function(){return _.dd.a?_.dd.a:_.dd.a=new _.dd};_.cd=function(a,b){var c=b||_.oa;a.b?c():window.chrome.storage.local.get((0,_.q)(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};_.dd.prototype.get=function(a){return this.a.get(a)};_.dd.prototype.set=function(a,b){var c=_.wc();this.a.set(a,b);c.a(void 0);return c.b};_.dd.prototype.remove=function(a){this.a.remove(a)};
_.dd.prototype.clear=function(){this.a.clear()};var bd=function(){this.a=window.localStorage};bd.prototype.clear=function(){this.a.clear()};bd.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ha[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};bd.prototype.set=function(a,b){var c=null;b instanceof _.w&&(b=b.P,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}}; bd.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
_.ed=function(a,b){this.b=a;this.a=b;this.constructor.Lb||(this.constructor.Lb={});this.constructor.Lb[this.toString()]=this};_.ed.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};_.K=function(a,b){_.ed.call(this,a,b)};_.p(_.K,_.ed);_.fd=function(a){this.a=a};_.gd=new _.fd("lib");_.L=function(a){this.a=a};_.L.prototype.toString=function(){return this.a};_.hd=new _.L("fJuxOc");_.id=new _.L("ZtVrH");_.jd=new _.L("zZa4xc");_.kd=new _.L("pVbxBc");_.ld=new _.L("byfTOb");_.md=new _.L("LEikZe");_.nd=new _.L("rJmJrc");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.od=function(a,b){this.l=[];this.D=b||null;this.b=this.a=!1;this.c=void 0;this.v=this.A=this.g=!1;this.f=0;this.j=null;this.B=0};_.od.prototype.u=function(a,b){this.g=!1;_.pd(this,a,b)};_.pd=function(a,b,c){a.a=!0;a.c=c;a.b=!b;qd(a)};_.sd=function(a){if(a.a){if(!a.v)throw new rd;a.v=!1}};_.od.prototype.h=function(a){_.sd(this);_.pd(this,!0,a)};_.td=function(a,b,c,d){a.l.push([b,c,d]);a.a&&qd(a)};
_.od.prototype.then=function(a,b,c){var d,e,f=new rc(function(a,b){d=a;e=b});_.td(this,d,function(a){"undefined"!=typeof _.ud&&a instanceof _.ud?Ac(f):e(a)});return f.then(a,b,c)};nc(_.od);
var vd=function(a){return(0,_.za)(a.l,function(a){return _.ja(a[1])})},qd=function(a){if(a.f&&a.a&&vd(a)){var b=a.f,c=wd[b];c&&(_.k.clearTimeout(c.Ta),delete wd[b]);a.f=0}a.j&&(a.j.B--,delete a.j);for(var b=a.c,d=c=!1;a.l.length&&!a.g;){var e=a.l.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var l=f.call(e||a.D,b);_.n(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);if(oc(b)||"function"===typeof _.k.Promise&&b instanceof _.k.Promise)d=!0,a.g=!0}catch(r){b=r,a.b=!0,vd(a)||(c=!0)}}a.c=b;d&&(l=(0,_.q)(a.u,
a,!0),d=(0,_.q)(a.u,a,!1),b instanceof _.od?(_.td(b,l,d),b.A=!0):b.then(l,d));c&&(b=new xd(b),wd[b.Ta]=b,a.f=b.Ta)},rd=function(){_.pa.call(this)};_.p(rd,_.pa);rd.prototype.message="Deferred has already fired";rd.prototype.name="AlreadyCalledError";var xd=function(a){this.Ta=_.k.setTimeout((0,_.q)(this.b,this),0);this.a=a};xd.prototype.b=function(){delete wd[this.Ta];throw this.a;};var wd={};

}catch(e){_._DumpException(e)}
try{
var zd;_.yd=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};zd=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.Bd=function(a){_.E.call(this);this.c={};this.j={};this.u={};this.f={};this.v={};this.B={};this.A=a?a.qa():new _.J;this.G=!a;this.g=null;a?(this.g=a,this.u=a.u,this.f=a.f,this.j=a.j,this.v=a.v):(0,_.m)();a=Ad(this);this!=a&&(a.h?a.h.push(this):a.h=[this])};_.p(_.Bd,_.E);var Ad=function(a){for(;a.g;)a=a.g;return a};_.Bd.prototype.get=function(a){var b=this.b(a);if(null==b)throw new Cd(a);return b};
_.Bd.prototype.b=function(a){for(var b=this;b;b=b.g){if(b.J)throw Error("p");if(b.c[a])return b.c[a][0];if(b.B[a])break}if(b=this.u[a]){b=b(this);if(null==b)throw Error("q`"+a);this.a(a,b);return b}return null};_.Bd.prototype.a=function(a,b,c){if(this.J)c||_.F(b);else{this.c[a]=[b,!c];b=Dd(this,this,a);for(c=0;c<b.length;c++)b[c].h(null);delete this.j[a]}};_.Bd.prototype.D=function(){var a=_.Ed;if(!this.c[a])throw Error("r`"+a);var b=this.c[a];delete this.c[a];b[1]&&_.F(b[0])};
var Dd=function(a,b,c){var d=[],e=a.f[c];e&&(zd(e,function(a){var c;a:{for(c=a.Mb;c;){if(c==b){c=!0;break a}c=c.g}c=!1}c&&(d.push(a.d),_.Aa(e,a))}),0==e.length&&delete a.f[c]);return d},Fd=function(a,b){a.f&&_.Ya(a.f,function(a,d,e){zd(a,function(d){d.Mb==b&&_.Aa(a,d)});0==a.length&&delete e[d]})};
_.Bd.prototype.w=function(){if(Ad(this)==this){var a=this.h;if(a)for(;a.length;)a[0].K()}else for(var a=Ad(this).h,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].K&&a[0].K();this.c=null;this.G&&this.A.K();Fd(this,this);this.f=null;_.F(this.F);this.B=this.F=null;_.Bd.C.w.call(this)};_.Bd.prototype.qa=function(){return this.A};var Cd=function(a){_.pa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'}; _.p(Cd,_.pa);var Gd=new _.fd("fva");new _.K(Gd,1);

}catch(e){_._DumpException(e)}
try{
var Hd,Id,Kd,Ld,Md,Nd,Od,Vd,Wd,Xd,ae,be,ee,fe,ge,he,ie,je,ke,pe;Hd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};Id=function(a,b){b.push('"',a.replace(_.Ba,function(a){var b=Hd[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Hd[a]=b);return b}),'"')};Kd=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)Kd(a,b[f],c,d,e);return null}c=_.Kb(c);return _.yb(a)?a.X.add(String(b),c,!0,d,e):_.Lb(a,b,c,!0,d,e)};Ld="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
Md=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.ma(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Md(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Id(d,c),c.push(":"),Md(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Id(b,c);break;case "number":c.push((0,window.isFinite)(b)&&
!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "function":break;default:throw Error("d`"+typeof b);}}};Nd=function(){};Od=function(a,b,c,d,e,f){if(_.ma(c))for(var g=0;g<c.length;g++)Od(a,b,c[g],d,e,f);else{b=Kd(b,c,d||a.handleEvent,e,f||a.M||a);if(!b)return a;a.h[b.key]=b}return a};_.M=function(a,b,c){b<a.l?a.P[b+a.c]=c:a.b[b]=c};
_.Pd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ld.length;f++)c=Ld[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.Qd=function(a){var b=[];Md(new Nd,a,b);return b.join("")};_.Rd=function(a,b,c){null!=b&&(a.f=b,null!=c&&(a.l=c))};
_.N=function(a,b){var c,d=a.D;if(d)for(c=[];d;d=d.D)c.push(d);var d=a.R,e=b,f=e.type||e;if(_.t(e))e=new _.H(e,d);else if(e instanceof _.H)e.target=e.target||d;else{var g=e,e=new _.H(f,d);_.Pd(e,g)}var g=!0,l;if(c)for(var r=c.length-1;0<=r;r--)l=e.a=c[r],g=l.ga(f,!0,e)&&g;l=e.a=d;g=l.ga(f,!0,e)&&g;g=l.ga(f,!1,e)&&g;if(c)for(r=0;r<c.length;r++)l=e.a=c[r],g=l.ga(f,!1,e)&&g};_.Sd=function(a,b,c,d){return Od(a,b,c,d,void 0)};
_.Td=function(a){return _.k.JSON&&_.k.JSON.stringify?_.k.JSON.stringify(a.P):_.Qd(a.P)};_.Ud=function(a,b,c){a.a||(a.a={});var d=c?c.P:c;a.a[b]=c;_.M(a,b,d)};_.P=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=_.y(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};Vd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Wd=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};
Xd=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};_.Yd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.Zd=function(a){return _.u.concat.apply(_.u,arguments)};_.$d=function(a,b,c){this.b=this.a=null;this.c=a||null;this.l=!!c};
ae=function(a){a.a||(a.a=new _.B,a.b=0,a.c&&Xd(a.c,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};_.h=_.$d.prototype;_.h.Y=function(){ae(this);return this.b};_.h.add=function(a,b){ae(this);this.c=null;a=be(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b++;return this};_.h.remove=function(a){ae(this);a=be(this,a);return _.Wa(this.a,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};_.h.clear=function(){this.a=this.c=null;this.b=0};
_.h.T=function(){ae(this);return 0==this.b};var ce=function(a,b){ae(a);b=be(a,b);return _.Wa(a.a,b)};_.$d.prototype.S=function(){ae(this);for(var a=this.a.I(),b=this.a.S(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.$d.prototype.I=function(a){ae(this);var b=[];if(_.t(a))ce(this,a)&&(b=_.Zd(b,this.a.get(be(this,a))));else{a=this.a.I();for(var c=0;c<a.length;c++)b=_.Zd(b,a[c])}return b};
_.$d.prototype.set=function(a,b){ae(this);this.c=null;a=be(this,a);ce(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b++;return this};_.$d.prototype.get=function(a,b){var c=a?this.I(a):[];return 0<c.length?String(c[0]):b};_.de=function(a,b,c){a.remove(b);0<c.length&&(a.c=null,a.a.set(be(a,b),_.Yd(c)),a.b+=c.length)};
_.$d.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.S(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.I(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}return this.c=a.join("&")};_.$d.prototype.clone=function(){var a=new _.$d;a.c=this.c;this.a&&(a.a=this.a.clone(),a.b=this.b);return a};be=function(a,b){var c=String(b);a.l&&(c=c.toLowerCase());return c};
ee=function(a,b){b&&!a.l&&(ae(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.de(this,e,a))},a));a.l=b};fe=/#/g;ge=/[\#\?@]/g;he=/[\#\?]/g;ie=/[\#\?:]/g;je=/[#\/\?@]/g;ke=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,Vd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};_.le=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36)};
_.me=function(a,b){this.c=this.j=this.f="";this.l=null;this.g=this.a="";this.h=!1;var c;"undefined"!=typeof _.me&&a instanceof _.me?(this.h=_.n(b)?b:a.h,_.ne(this,a.f),this.j=a.j,this.c=a.c,_.oe(this,a.l),this.a=a.a,pe(this,a.b.clone()),this.g=a.g):a&&(c=_.tb(String(a)))?(this.h=!!b,_.ne(this,c[1]||"",!0),this.j=Wd(c[2]||""),this.c=Wd(c[3]||"",!0),_.oe(this,c[4]),this.a=Wd(c[5]||"",!0),pe(this,c[6]||"",!0),this.g=Wd(c[7]||"")):(this.h=!!b,this.b=new _.$d(null,0,this.h))};
_.me.prototype.toString=function(){var a=[],b=this.f;b&&a.push(ke(b,je,!0),":");if(b=this.c){a.push("//");var c=this.j;c&&a.push(ke(c,je,!0),"@");a.push((0,window.encodeURIComponent)(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.l;null!=b&&a.push(":",String(b))}if(b=this.a)this.c&&"/"!=b.charAt(0)&&a.push("/"),a.push(ke(b,"/"==b.charAt(0)?he:ie,!0));(b=this.b.toString())&&a.push("?",b);(b=this.g)&&a.push("#",ke(b,fe));return a.join("")};
_.qe=function(a,b){var c=a.clone(),d=!!b.f;d?_.ne(c,b.f):d=!!b.j;d?c.j=b.j:d=!!b.c;d?c.c=b.c:d=null!=b.l;var e=b.a;if(d)_.oe(c,b.l);else if(d=!!b.a){if("/"!=e.charAt(0))if(a.c&&!a.a)e="/"+e;else{var f=c.a.lastIndexOf("/");-1!=f&&(e=c.a.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),g=[],l=0;l<f.length;){var r=f[l++];"."==r?e&&l==f.length&&g.push(""):".."==r?((1<g.length||1==g.length&&""!=g[0])&&g.pop(),
e&&l==f.length&&g.push("")):(g.push(r),e=!0)}e=g.join("/")}else e=f}d?c.a=e:d=""!==b.b.toString();d?pe(c,Wd(b.b.toString())):d=!!b.g;d&&(c.g=b.g);return c};_.me.prototype.clone=function(){return new _.me(this)};_.ne=function(a,b,c){a.f=c?Wd(b,!0):b;a.f&&(a.f=a.f.replace(/:$/,""))};_.oe=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("i`"+b);a.l=b}else a.l=null};pe=function(a,b,c){b instanceof _.$d?(a.b=b,ee(a.b,a.h)):(c||(b=ke(b,ge)),a.b=new _.$d(b,0,a.h))};
_.R=function(a,b,c){a.b.set(b,c)};_.re=function(a,b,c){_.ma(c)||(c=[String(c)]);_.de(a.b,b,c)};_.se=function(a,b){return a.b.get(b)};_.te=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.ue=function(a,b){return 0<=(0,_.ua)(a,b)};
_.ve=function(a,b,c){if(_.ja(a))c&&(a=(0,_.q)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.q)(a.handleEvent,a);else throw Error("m");return 2147483647<b?-1:_.k.setTimeout(a,b||0)};_.we=function(a){_.k.clearTimeout(a)};_.xe=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.ye=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.la(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}}; _.ze=function(a,b){var c;a:{c=a.length;for(var d=_.t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:_.t(a)?a.charAt(c):a[c]};
var De,Be,Ce,Ee;_.Ae=function(){};De=function(a){var b=a.ja,c=function(a){c.C.constructor.call(this,a);var b=this.W.length;this.a=[];for(var d=0;d<b;++d)this.W[d].vd||(this.a[d]=new this.W[d](a))};_.p(c,b);for(var d=[];a;){if(b=a.ja){b.W&&_.ye(d,b.W);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ja(e[f])&&e[f]!==b){var g=!!e[f].Bc,l=Be(f,e,d,g);(g=Ce(f,e,l,g))&&(c.prototype[f]=g)}}a=a.C&&a.C.constructor}c.prototype.W=d;return c};
Be=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e};
Ce=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.W[c[0]].prototype[a].apply(this,arguments)}:b[a].Dc?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var r=this.a[c[e]];if(r=r?r[a].apply(r,d):this.W[c[e]].prototype[a].apply(this,d)){d=r;break a}}d=!1}return d}:b[a].Cc?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var r=this.a[c[e]],r=r?r[a].apply(r,
d):this.W[c[e]].prototype[a].apply(this,d);if(null!=r){d=r;break a}}d=void 0}return d}:b[a].dc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var r=this.a[c[e]];r?r[a].apply(r,d):this.W[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],r=0;r<c.length;++r){var D=this.a[c[r]];e.push(D?D[a].apply(D,d):this.W[c[r]].prototype[a].apply(this,d))}return e}:d||b[a].Dc||b[a].Cc||b[a].dc?e=null:e=Ee;return e};Ee=function(){return[]}; _.Ae.prototype.qb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var Fe;_.Ge=function(a){if(!a.nb){var b;for(b=a.constructor;b&&!b.ja;)b=b.C&&b.C.constructor;b.ja.Qb||(b.ja.Qb=De(b));b=new b.ja.Qb(a);a.nb=b;a.qb||(a.qb=Fe)}};Fe=function(a){return this.nb.qb(a)};var He=function(){};He.prototype.a=null;var Je=function(a){var b;(b=a.a)||(b={},Ie(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Ke,Le=function(){};_.p(Le,He);var Me=function(a){return(a=Ie(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},Ie=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("s");}return a.b};Ke=new Le;
var Oe,Re,We,Ye,Xe,Te;_.Ne=function(a){_.J.call(this);this.H=new _.B;this.u=a||null;this.b=!1;this.j=this.a=null;this.B="";this.f=0;this.c=this.A=this.g=this.v=!1;this.F=0;this.h=null;this.M="";this.G=this.da=!1};_.p(_.Ne,_.J);Oe=/^https?$/i;_.Pe=["POST","PUT"];_.Qe=[];_.Ne.prototype.V=function(){this.K();_.Aa(_.Qe,this)};
_.Ne.prototype.send=function(a,b,c,d){if(this.a)throw Error("t`"+this.B+"`"+a);b=b?b.toUpperCase():"GET";this.B=a;this.f=0;this.v=!1;this.b=!0;this.a=this.u?Me(this.u):Me(Ke);this.j=this.u?Je(this.u):Je(Ke);this.a.onreadystatechange=(0,_.q)(this.N,this);try{this.A=!0,this.a.open(b,String(a),!0),this.A=!1}catch(e){Re(this);return}a=c||"";var f=this.H.clone();d&&_.Ya(d,function(a,b){f.set(b,a)});d=_.ze(f.S(),Se);c=_.k.FormData&&a instanceof _.k.FormData;!_.ue(_.Pe,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.M&&(this.a.responseType=this.M);"withCredentials"in this.a&&(this.a.withCredentials=this.da);try{Te(this),0<this.F&&((this.G=Ue(this.a))?(this.a.timeout=this.F,this.a.ontimeout=(0,_.q)(this.O,this)):this.h=_.ve(this.O,this.F,this)),this.g=!0,this.a.send(a),this.g=!1}catch(g){Re(this)}};var Ue=function(a){return _.C&&_.ib(9)&&_.ka(a.timeout)&&_.n(a.ontimeout)},Se=function(a){return"content-type"==a.toLowerCase()};
_.Ne.prototype.O=function(){"undefined"!=typeof _.aa&&this.a&&(this.f=8,_.N(this,"timeout"),_.Ve(this,8))};Re=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.f=5;We(a);Xe(a)};We=function(a){a.v||(a.v=!0,_.N(a,"complete"),_.N(a,"error"))};_.Ve=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.f=b||7,_.N(a,"complete"),_.N(a,"abort"),Xe(a))};_.Ne.prototype.w=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Xe(this,!0));_.Ne.C.w.call(this)};
_.Ne.prototype.N=function(){this.J||(this.A||this.g||this.c?Ye(this):this.Z())};_.Ne.prototype.Z=function(){Ye(this)};Ye=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.j[1]||4!=(a.a?a.a.readyState:0)||2!=_.Ze(a)))if(a.g&&4==(a.a?a.a.readyState:0))_.ve(a.N,0,a);else if(_.N(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.$e(a)?(_.N(a,"complete"),_.N(a,"success")):(a.f=6,We(a))}finally{Xe(a)}}};
Xe=function(a,b){if(a.a){Te(a);var c=a.a,d=a.j[0]?_.oa:null;a.a=null;a.j=null;b||_.N(a,"ready");try{c.onreadystatechange=d}catch(e){}}};Te=function(a){a.a&&a.G&&(a.a.ontimeout=null);_.ka(a.h)&&(_.we(a.h),a.h=null)};
_.$e=function(a){var b=_.Ze(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=_.tb(String(a.B))[1]||null,!a&&window.self.location&&(a=window.self.location.protocol,a=a.substr(0,a.length-1)),b=!Oe.test(a?a.toLowerCase():"");c=b}return c};_.Ze=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};_.af=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
_.bf=function(a){_.x(this,a,"h_icr",null)};_.p(_.bf,_.w);_.z("h_icr",_.bf);_.cf=function(a){_.x(this,a,"h_cs",null)};_.p(_.cf,_.w);_.z("h_cs",_.cf);_.cf.prototype.getState=function(){return _.y(this,1)};_.df=new _.L("HwdKC");
}catch(e){_._DumpException(e)}
try{
_.ef=function(){return window.chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_._DumpException(e)}
try{
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"}, chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"}};

}catch(e){_._DumpException(e)}
try{
var ff=function(a,b){var c,d,e,f;c=window.document;c=b||c;if(c.querySelectorAll&&c.querySelector&&a)return c.querySelectorAll(""+(a?"."+a:""));if(a&&c.getElementsByClassName){var g=c.getElementsByClassName(a);return g}g=c.getElementsByTagName("*");if(a){f={};for(d=e=0;c=g[d];d++){var l=c.className;"function"==typeof l.split&&_.ue(l.split(/\s+/),a)&&(f[e++]=c)}f.length=e;return f}return g},gf=function(a){return a instanceof _.me?a.clone():new _.me(a,void 0)},hf=function(a){_.x(this,a,0,null)};
_.p(hf,_.w);var jf=function(a){_.x(this,a,0,null)};_.p(jf,_.w);var kf=function(a){_.x(this,a,0,null)};_.p(kf,_.w);var lf=function(a){_.x(this,a,0,null)};_.p(lf,_.w);
var mf=/[?&]($|#)/,nf=/#|$/,of=function(a,b,c,d){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1},pf=function(a){if(a&&"number"==typeof a.length){if(_.ia(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.ja(a))return"function"==typeof a.item}return!1},qf={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",
role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},rf=/[\x00&<>"']/,sf=/\x00/g,tf=/'/g,uf=/"/g,vf=/>/g,wf=/</g,xf=/&/g,yf=function(a,b,c){function d(c){c&&b.appendChild(_.t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.la(f)||_.ia(f)&&0<f.nodeType?d(f):(0,_.v)(pf(f)?_.Yd(f):f,d)}},zf=function(a,b){_.Ca(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in qf?a.setAttribute(qf[d],b):0==d.lastIndexOf("aria-",
0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},Af=function(a){if(!rf.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(xf,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(wf,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(vf,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(uf,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(tf,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(sf,"&#0;"));return a},Bf={LOADING:0,pc:1,sd:2,td:3,ERROR:4,LOADED:5,oc:6},Cf=function(a,b,c){for(var d=a.search(nf),e=0,f,g=[];0<=(f=of(a,
e,b,d));)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.substr(e));a=[g.join("").replace(mf,"$1"),"&",b];null!=c&&a.push("=",(0,window.encodeURIComponent)(String(c)));a[1]&&(c=a[0],b=c.indexOf("#"),0<=b&&(a.push(c.substr(b)),a[0]=c=c.substr(0,b)),b=c.indexOf("?"),0>b?a[1]="?":b==c.length-1&&(a[1]=void 0));return a.join("")},Df=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},Ef=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,
Ff=function(a){_.J.call(this);this.f=a;this.b=Bf.LOADING;this.a=!1;this.c=new _.I(this);_.G(this,this.c);this.c.listen(this.f.qa(),"h_cs",this.g)};_.p(Ff,_.J);Ff.prototype.getState=function(){return this.b};Ff.prototype.j=function(){return this.a};Ff.prototype.g=function(a){a=new _.cf(a.Ya);var b=a.getState();null!=b&&this.b!=b&&(this.b=b,_.N(this,"d"));a=_.y(a,2);null!=a&&this.a!=a&&(this.a=a,_.N(this,"c"))};
var Gf=function(a){(a?a:function(){}).Bc=!0},Hf=function(a,b,c){var d=arguments,e=window.document,f=d[0],g=d[1];if(!_.nb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',Af(g.name),'"');if(g.type){f.push(' type="',Af(g.type),'"');var l={};_.Pd(l,g);delete l.type;g=l}f.push(">");f=f.join("")}f=e.createElement(f);g&&(_.t(g)?f.className=g:_.ma(g)?f.className=g.join(" "):zf(f,g));2<d.length&&yf(e,f,d);return f},If=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:
c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=ff(a,b)[0];return d||null},Jf=function(a){var b=_.t(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})},Kf=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
var Lf=function(a){this.a=a;_.C||(delete this.a.lpu,delete this.a.ppu)},Mf=["cn","tp"],Nf=function(a,b){var c=null,d;if(_.ja(window.document.postMessage)||_.ja(window.postMessage)||_.C&&window.postMessage)d=1;else if(_.$a)d=2;else{if(c=_.C){c=!1;try{d=window.opener,window.opener={},c=_.pb(window,"opener"),window.opener=d}catch(e){}}d=c?6:4}c=d;d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new Lf(d)};_.ga("GTalk_IFrameChannelConfig.build",Nf);
var Of=function(){if(If("talk_loading_msg")){var a=If("talk_loading_msg_error");a&&_.yd(a)}},Pf=function(a){var b=If("talk_loading_msg");if(b){Of();var c=window.document.createElement("DIV");zf(c,{"class":"talk_loading_msg_error",style:"margin: 12px 8px; font-size: 10px"});var d=window.document.createElement("DIV");a="Errors: "+a.join(", ");if("textContent"in d)d.textContent=a;else if(3==d.nodeType)d.data=a;else if(d.firstChild&&3==d.firstChild.nodeType){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild); d.firstChild.data=a}else Df(d),d.appendChild((9==d.nodeType?d:d.ownerDocument||d.document).createTextNode(String(a)));c.appendChild(d);b.appendChild(c)}};
var Qf=function(){};_.p(Qf,_.Ae);Qf.prototype.b=function(a){return a};Gf(Qf.prototype.b);Qf.prototype.c=function(){return!0};Gf(Qf.prototype.c);var Rf=function(a){_.x(this,a,0,null)};_.p(Rf,_.w);var Sf=function(a,b){var c=new Rf;_.M(c,1,b);_.M(c,2,a);return c},Tf=Sf("?",0),Uf=Sf("q",1),Vf=Sf("<",2),Wf=Sf(">",3),Xf=Sf("~",4),Yf=Sf("s",5),Zf={f:Tf,u:Uf,h:Vf,j:Wf,g:Xf,v:Yf};var $f=function(a){_.x(this,a,"ci:dc",null)};_.p($f,_.w);_.z("ci:dc",$f);var ag=function(a){_.x(this,a,"ci:ec",null)};_.p(ag,_.w);_.z("ci:ec",ag);var bg=function(a){return null!=_.y(a,2)?_.y(a,2):!1};var cg=function(a){this.a=a},dg=/\s*;\s*/;_.h=cg.prototype;_.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("u`"+a);if(/[;\r\n]/.test(b))throw Error("v`"+b);_.n(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.m)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.h.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(dg),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.h.remove=function(a,b,c){var d=_.n(this.get(a));this.set(a,"",0,b,c);return d};_.h.S=function(){return eg(this).keys};_.h.I=function(){return eg(this).values};_.h.T=function(){return!this.a.cookie};_.h.Y=function(){return this.a.cookie?(this.a.cookie||"").split(dg).length:0};
_.h.clear=function(){for(var a=eg(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};var eg=function(a){a=(a.a.cookie||"").split(dg);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var fg=function(a,b,c){_.Ge(this);var d=this.nb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(0==d.lastIndexOf("https://talkgadget.google.com/talkgadget/",0)){var e=(new cg(window.document)).get("WCSDBG",""),e=e.split(";")[0],e=e.split("|")[0],f=["plus.google.com"],g=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<e.length&&!_.ue(f,e)&&g.test(e)&&(d=gf(d),d=gf("https://"+e+d.a).toString())}this.fa=d;this.c=c||new ag;a.notificationsOnly&&_.M(this.c,1,!0);this.b="0";null!=a.authUser?
this.b=a.authUser:(c=_.se(new _.me(window.location.href),"authuser"),null!=c&&(this.b=c));this.l=a.clientUrl||"notifierclient";c=_.se(gf(this.l),"authuser");null!=c&&(this.b=c);this.h=a.propertyName||"Google Talk";this.v=a.cssUrl;this.locale=a.locale;this.g=a.debug;this.Ib=a.userJid;this.Fb=a.uiVersion;this.Ic=null!=a.rosterExpanded?a.rosterExpanded:!0;this.R=a.hostLogMinValue;this.Na=a.hideChat;this.Ac=a.refresh;this.H=a.hideProfileCard;this.O=a.hideStatusMsgs;this.N=a.hideRosterOptions;this.M=a.hideRecentConversations;
this.G=a.hideOTR;this.nc=a.hostServerMessageCallback||!1;this.Z=a.isCentralRoster;this.yc=a.isFullFrame||!1;this.Hc=a.rosterClass||"talk_roster";this.za=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.f=a.parentToken;this.Fc=b||!1;_.n(a.isRtl)||Ef.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var l in Zf)b.push(_.Td(Zf[l]))}this.B=
a.entityId;this.Gb=a.useQuasarPanels||!1;this.Db=a.silent||!1;this.rc=a.ignoreCentralRoster||!1;this.Ec=a.lazy||!1;this.qc=a.handleProfileLinks||!1;this.V=a.hostSettings;this.j=a.screen;this.A=a.docsConfig;this.da=a.jsmode;this.ya=a.moleWidth;this.xa=a.moleHeight;this.wa=a.minimizedMoleHeight||36;this.Mc=a.derp;this.Eb=window.location.protocol+"//"+window.location.host;this.F=a.optOutAllowed;this.D=a.legacyTalkSignedIn;this.Hb=a.useSpareMole;this.u=a.conversationId};Qf.C||_.p(Qf,_.Ae);fg.ja=Qf;
var gg=function(a){switch(a){case 1:case 36:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp"}};
var hg=function(a,b,c,d,e){_.E.call(this);this.a=a;this.b=d||window.document;this.c=new _.I(this);_.G(this,this.c);var f=_.Ma;d=new _.me(a.fa+a.l);bg(a.c)||(_.R(d,"ts","0"),_.R(d,"re",a.Ic),_.R(d,"ref",a.Ac));_.R(d,"client","sm");_.R(d,"prop",a.h);_.R(d,"nav","true");_.R(d,"fid",a.a);a.g&&_.R(d,"debug",a.g);_.R(d,"os",_.cb);_.R(d,"stime",c);a.Na&&_.R(d,"hc",a.Na);for(c=0;c<Mf.length;++c);b=_.Qd(b.a);_.R(d,"xpc",b);_.R(d,"ec",_.Td(a.c));a.j&&_.R(d,"screen",a.j);-1!=f.indexOf("MSIE")&&_.R(d,"ua",f);
a.f&&_.R(d,"pvt",a.f);a.nc&&_.R(d,"hsmc","true");_.n(a.R)&&_.R(d,"logl",a.R);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.R(d,"href",b.join("?")));b=new _.me(window.location.href);"false"==_.se(b,"uacheck")&&_.R(d,"uacheck",!1);(f=a.da)&&_.R(d,"jsmode",f);(f=_.se(b,"cssmode"))&&_.R(d,"cssmode",f);(f=_.se(b,"convid"))&&_.R(d,"convid",f);(f=b.b.I("convp"))&&_.re(d,"convp",f);(f=_.se(b,"smexp"))&&_.R(d,"smexp",f);f=b.b.I("mods");a.Ec&&
f.push("lazy");e&&(f=_.Zd(f,e));0<f.length&&_.R(d,"mods",f.join(","));if(!a.fa||0>a.fa.indexOf("/u/"))(e=_.se(b,"authuser"))?_.R(d,"authuser",e):null!=a.b&&_.R(d,"authuser",a.b);e=_.se(b,"eid");/^[\s\xa0]*$/.test(null==e?"":String(e))||_.R(d,"eid",e);e=this.a.B;/^[\s\xa0]*$/.test(null==e?"":String(e))||_.R(d,"eid",this.a.B);null!=this.a.position&&_.R(d,"pos",this.a.position);_.n(a.Fb)&&_.R(d,"uiv",this.a.Fb);a.v&&_.R(d,"css",a.v);e=a.locale||_.se(b,"hl");null!=e&&_.R(d,"hl",e);_.n(a.Ib)&&_.R(d,"uj",
a.Ib);null!=a.H&&_.R(d,"hpc",a.H);null!=a.O&&_.R(d,"hsm",a.O);null!=a.N&&_.R(d,"hro",a.N);null!=a.M&&_.R(d,"hrc",a.M);null!=a.G&&_.R(d,"hotr",a.G);null!=a.Z&&_.R(d,"pop",a.Z);a.Fc&&_.R(d,"pal","1");null!=a.Gb&&_.R(d,"uqp",a.Gb);null!=a.F&&_.R(d,"gooa",a.F);null!=a.D&&_.R(d,"gltsi",a.D);null!=a.Hb&&_.R(d,"gusm",a.Hb);null!=a.Db&&_.R(d,"sl",a.Db);a.rc&&_.R(d,"icr","1");a.qc&&_.R(d,"hpl","1");a.V&&_.R(d,"hs",a.V);a.A&&_.R(d,"dc",_.Td(a.A));null!=a.ya&&_.R(d,"molew",a.ya);null!=a.xa&&_.R(d,"moleh",a.xa);
null!=a.wa&&_.R(d,"mmoleh",a.wa);a.Mc&&_.R(d,"derp","1");null!=a.Eb&&_.R(d,"two",a.Eb);null!=a.u&&_.R(d,"convid",a.u);_.R(d,"host","1");_.R(d,"zx",_.le());this.f=d.toString()};_.p(hg,_.E);
var ig=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Hc,a.b.body.appendChild(e));a=(0,_.q)(function(){var a="";this.a.yc||(a="height:400px");var b=this.b.createElement("iframe");zf(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a});If("talk_loading_msg",e)||Df(e);e.appendChild(b);var l=this.b.getElementById(this.a.a);_.Sd(this.c,l,["load","error"],function(){l.contentWindow.postMessage("AllowFrame: Chat","*");d()});l.src= this.f.toString();c()},a);window.setTimeout(a,0)};
var jg=function(a){_.H.call(this,a[0]);this.Ya=a};_.p(jg,_.H);var kg=function(a){_.x(this,a,"h_ccf",null)};_.p(kg,_.w);_.z("h_ccf",kg);var lg=function(a){_.x(this,a,"h_rtp",null)};_.p(lg,_.w);_.z("h_rtp",lg);var ng=function(a,b,c){var d=mg[c];if(!d){var e=Kf(c),d=e;void 0===a.style[e]&&(e=(_.ab?"Webkit":_.$a?"Moz":_.C?"ms":_.Za?"O":null)+Jf(e),void 0!==a.style[e]&&(d=e));mg[c]=d}(c=d)&&(a.style[c]=b)},mg={},og=function(a){"number"==typeof a&&(a=Math.round(a)+"px");return a};_.C&&_.ib(12);
var pg=function(a,b){_.E.call(this);this.M=(0,_.m)();this.H=a;this.document=b||window.document;this.a=new fg(a,!0,a.endpointConfig);this.h=[];this.B=new _.J;this.g=null};_.p(pg,_.E);pg.prototype.w=function(){pg.C.w.call(this);_.we(this.g);this.b&&this.v&&this.b.parentNode.removeEventListener("DOMAttrModified",this.v,!0)};pg.prototype.f=function(a,b){this.c?this.c[a]&&this.c[a].apply(this.c,Array.prototype.slice.call(arguments,1)):this.h.push(arguments)};
pg.prototype.j=function(){var a=this.Vb().GTalkNotifier;if(a){var b=_.xe(this.H);b.endpointConfig=_.Td(this.a.c);this.c=new a(b,!0);for(a=0;a<this.h.length;a++)this.f.apply(this,this.h[a]);this.h=[];a=(0,_.q)(this.onMessage,this);this.f("_addClientMessageCallback",a);this.f("_addHostBundleMessageCallback",a)}};pg.prototype.onMessage=function(a){switch(a[0]){case "h_ccf":var b=new kg(a);_.y(b,1)}_.N(this.B,new jg(a))};var qg=function(a,b){a.f("_h",b.P)};_.h=pg.prototype;
_.h.sendMessage=function(a){qg(this,a)};_.h.qa=function(){return this.B};_.h.Vb=function(){return this.document.parentWindow||this.document.defaultView};_.h.Pc=function(a,b){if(b.target==a&&("style"==b.attrName||"class"==b.attrName)){var c=new lg;qg(this,c)}};
_.h.Qc=function(){if(If("talk_loading_msg",this.document.getElementById(this.a.za))){var a=this.document.getElementById(this.a.a),b=0,c;"undefined"!=typeof _.rg&&b instanceof _.rg?(c=b.height,b=b.width):c=0;a.style.width=og(b);a.style.height=og(c);if(_.t("overflow"))ng(a,"hidden","overflow");else for(var d in"overflow")ng(a,"overflow"[d],d);a.style.display=""}};
var sg=function(a){var b=a.a.fa+"host-js",b=Cf(b,"prop",a.a.h),c=a.a.da;c&&(b=Cf(b,"jsmode",c));bg(a.a.c)&&(b=Cf(b,"b","1"));var b=Cf(b,"zx",_.le()),d=(0,_.q)(a.j,a),e=Hf("script",{type:"text/javascript",src:b}),f=!1;e.onload=e.onreadystatechange=function(){f||e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(f=!0,d())};e.onerror=(0,_.q)(a.D,a,e);a.g&&(_.we(a.g),a.g=null);a.g=_.ve((0,_.q)(function(){null!=this.c||this.F(e)},a),25E3);a.document.body.appendChild(e)};pg.prototype.D=function(){}; pg.prototype.F=function(){};
var tg=function(a){if(a.classList)return a.classList;a=a.className;return _.t(a)&&a.match(/\S+/g)||[]},ug=function(a){return a.classList?a.classList.contains("talk_network_warning"):_.ue(tg(a),"talk_network_warning")},vg=function(a){a.classList?a.classList.remove("talk_network_warning"):ug(a)&&(a.className=(0,_.wa)(tg(a),function(a){return"talk_network_warning"!=a}).join(" "))};
var wg=function(a,b){this.b=a;this.c=b;this.a=a};wg.prototype.reset=function(){this.a=this.b};wg.prototype.L=function(){return this.a};var xg=function(a){a.a=Math.min(a.c,2*a.a)};var yg=function(a,b,c){var d={},e;e=null!=_.y(a,1)?_.y(a,1):"talkgadget.google.com";var f="";0>e.indexOf("://")&&(f="https://",0<=e.indexOf(":")&&23!=_.y(a,2)&&27!=_.y(a,2)&&(f="http://"));d.clientBaseUrl=f+e+"/talkgadget/_/";e=null!=_.y(a,8)?_.y(a,8):"0";d.authUser=e;d.clientUrl="chat";d.propertyName=gg(_.y(a,2));d.locale=_.y(a,4);d.hideProfileCard=!0;d.parentToken=_.y(a,3);e=null!=_.y(a,6)?_.y(a,6):!1;d.isRtl=e;e=null!=_.y(a,7)?_.y(a,7):!1;d.lazy=e;d.entityId=_.y(a,9);d.hostSettings=_.y(a,5);d.jsmode=
_.y(a,11);e=null!=_.y(a,13)?_.y(a,13):!1;d.isFullFrame=e;e=null!=_.y(a,12)?_.y(a,12):"talk_roster";d.rosterId=e;e=null!=_.y(a,15)?_.y(a,15):"gtn-roster-iframe-id-b";d.rosterIframeIdB=e;e=null!=_.y(a,16)?_.y(a,16):!1;d.derp=!!e;e=_.P(a,hf,14);null!=e&&(f=null!=_.y(e,1)?_.y(e,1):!1,d.isCentralRoster=f,e=null!=_.y(e,2)?_.y(e,2):!1,d.useQuasarPanels=e);e=_.P(a,lf,10);null!=e&&(d.moleManagerLeftMargin=_.y(e,1),d.moleManagerMiddleMargin=_.y(e,2),d.moleManagerRightMargin=_.y(e,3),d.moleManagerNoMoleAreaMargin=
_.y(e,4),d.moleManagerBoundingElementId=_.y(e,5),d.moleWidth=_.y(e,6),d.moleHeight=_.y(e,7),d.minimizedMoleHeight=_.y(e,8));e=_.P(a,kf,18);null!=e&&(f=null!=_.y(e,1)?_.y(e,1):!0,d.optOutAllowed=f,f=_.P(e,jf,3),null!=f&&(f=null!=_.y(f,1)?_.y(f,1):!0,d.legacyTalkSignedIn=f),e=_.y(e,4),null!=e&&(d.useSpareMole=e));d.uiVersion=2;d.hideStatusMsgs=!0;d.hideRecentConversations=!0;e=new ag;_.M(e,2,!0);_.M(e,1,!0);_.M(e,3,!1);d.endpointConfig=e;e=null!=_.y(a,17)?_.y(a,17):!1;d.ignoreAutomatedRoster=e;d.conversationId=
a.ba();d.hostCallback=c;pg.call(this,d,b);this.A=new wg(5E3,3E5);this.G=null};_.p(yg,pg);var zg=function(a,b){var c=1+.5*Math.random();a.G=_.ve(function(){null==this.c&&(_.te(this.document.body,b)&&this.document.body.removeChild(b),sg(this))},a.A.L()*c,a);xg(a.A)};yg.prototype.F=function(a){Pf(["301"]);zg(this,a)};
yg.prototype.D=function(a){var b=If("talk_loading_msg",this.document.body);b&&(b.classList?b.classList.add("talk_network_warning"):ug(b)||(b.className+=0<b.className.length?" talk_network_warning":"talk_network_warning"));Pf(["302"]);zg(this,a)};yg.prototype.j=function(){yg.C.j.call(this);var a=If("talk_loading_msg",this.document.body);a&&vg(a);Of()};yg.prototype.w=function(){yg.C.w.call(this);_.we(this.G)};
var Ag=function(a){_.J.call(this);this.c=a?a:null;this.a=null;this.f=!1;this.b=[];this.g=(0,_.q)(this.tc,this);this.h=(0,_.q)(this.Jb,this);this.j=null};_.p(Ag,_.J);var Bg=function(a){_.H.call(this,"message");this.message=a};_.p(Bg,_.H);_.h=Ag.prototype;_.h.w=function(){Ag.C.w.call(this);_.we(this.j);this.Jb(!0);for(var a=0;a<this.b.length;++a)_.F(this.b[a]);delete this.b;delete this.g;delete this.h};
_.h.sendMessage=function(a){if(null==a||null==a.message)return!1;_.Tc(a,this.c,"p");this.a&&this.f?this.a.postMessage(a.message()):this.b.push(a);return!0};_.h.connect=function(){if(null==this.c)return!1;try{if(this.a=window.chrome.runtime.connect({name:this.c}),null==this.a)return!1}catch(a){return!1}this.f=!0;this.a.onMessage.addListener(this.g);this.a.onDisconnect.addListener(this.h);for(var b=this.b.shift();null!=b;)_.Tc(b,this.c,"p"),this.a.postMessage(b.message()),b=this.b.shift();return!0};
_.h.tc=function(a){_.N(this,new Bg(_.Sc(new _.Rc,a)))};_.h.Jb=function(a){this.a&&(this.a.onMessage.removeListener(this.g),this.a.onDisconnect.removeListener(this.h),this.a.disconnect(),delete this.a);this.f=!1;a||(this.j=_.ve(this.ld,5E3,this))};_.h.ld=function(){this.connect()?_.N(this,{type:"reconnected"}):_.N(this,{type:"disconnected"})};
var Dg=function(a){_.x(this,a,"h_exts",Cg)};_.p(Dg,_.w);var Cg=[2];_.z("h_exts",Dg);var Eg=function(){_.E.call(this);this.b=" "};_.p(Eg,_.E);var Fg=function(a,b,c){a.a=c;b=new _.me(b);b=_.qe(b,new _.me("/talkgadget/_/extension-start"));a=(0,_.q)(a.c,a);c=new _.Ne;_.Qe.push(c);a&&c.listen("complete",a);c.X.add("ready",c.V,!0,void 0,void 0);c.send(b,void 0,void 0,void 0)};Eg.prototype.c=function(a){if(!this.J){this.b="";if(_.$e(a.target))try{var b=JSON.parse(_.af(a.target)),c=new Dg(b);this.b=_.y(c,1)||""}catch(d){}this.a&&(this.a(),this.a=null)}};
var Gg=function(a){_.x(this,a,"h_cp",null)};_.p(Gg,_.w);_.z("h_cp",Gg);var Hg=function(a){_.x(this,a,"rbc_d",null)};_.p(Hg,_.w);_.z("rbc_d",Hg);Hg.prototype.setTitle=function(a){_.M(this,1,a)};var Jg=function(a){_.x(this,a,"h_cd",Ig)};_.p(Jg,_.w);var Ig=[1,4,5];_.z("h_cd",Jg);Jg.prototype.ba=function(){return _.y(this,2)};var Kg=function(a){_.x(this,a,"h_hn",null)};_.p(Kg,_.w);_.z("h_hn",Kg);var Lg=function(a){_.x(this,a,"h_hs",null)};_.p(Lg,_.w);_.z("h_hs",Lg);var Ng=function(a){_.x(this,a,"h_jm",Mg)};_.p(Ng,_.w);var Mg=[2];_.z("h_jm",Ng);var Og=function(a){_.x(this,a,"h_oc",null)};_.p(Og,_.w);_.z("h_oc",Og);var Pg=function(a){_.x(this,a,"h_opc",null)};_.p(Pg,_.w);_.z("h_opc",Pg);var Qg=function(a){_.x(this,a,"h_ogc",null)};_.p(Qg,_.w);_.z("h_ogc",Qg);var Rg=function(a){_.x(this,a,"h_sc",null)};_.p(Rg,_.w);_.z("h_sc",Rg);var Tg=function(a){_.x(this,a,"h_ssc",Sg)};_.p(Tg,_.w);var Sg=[5];_.z("h_ssc",Tg);var Vg=function(a){_.x(this,a,"h_sm",Ug)};_.p(Vg,_.w);var Ug=[1,3];_.z("h_sm",Vg);var Wg=function(a){_.x(this,a,"h_po",null)};_.p(Wg,_.w);_.z("h_po",Wg);var Xg=function(a){_.J.call(this);this.a=a};_.p(Xg,_.J);var Yg=new _.L("O9EQob");var Zg=function(a){_.x(this,a,"capi:f_cfr",null)};_.p(Zg,_.w);_.z("capi:f_cfr",Zg);var $g=function(a){_.x(this,a,"capi:f_cvr",null)};_.p($g,_.w);_.z("capi:f_cvr",$g);var ah=function(a){_.x(this,a,"capi:f_vsm",null)};_.p(ah,_.w);_.z("capi:f_vsm",ah);var bh=function(a){_.x(this,a,"capi:f_ccr",null)};_.p(bh,_.w);_.z("capi:f_ccr",bh);var ch=function(a){_.x(this,a,"capi:f_csm",null)};_.p(ch,_.w);_.z("capi:f_csm",ch);var dh=function(a){_.x(this,a,0,null)};_.p(dh,_.w);
var eh=function(a){_.x(this,a,"capi:f_var",null)};_.p(eh,_.w);_.z("capi:f_var",eh);eh.prototype.getState=function(){return _.P(this,dh,1)};var fh=function(a){_.x(this,a,"capi:f_van",null)};_.p(fh,_.w);_.z("capi:f_van",fh);fh.prototype.getState=function(){return _.P(this,dh,1)};var gh=function(a){_.x(this,a,0,null)};_.p(gh,_.w);var hh=function(a){_.x(this,a,"capi:f_vcr",null)};_.p(hh,_.w);_.z("capi:f_vcr",hh);hh.prototype.getState=function(){return _.P(this,gh,1)};
var ih=function(a){_.x(this,a,"capi:f_vcn",null)};_.p(ih,_.w);_.z("capi:f_vcn",ih);ih.prototype.getState=function(){return _.P(this,gh,1)};var jh=function(a){_.x(this,a,0,null)};_.p(jh,_.w);var kh=function(a){_.x(this,a,"capi:f_vcor",null)};_.p(kh,_.w);_.z("capi:f_vcor",kh);kh.prototype.getState=function(){return _.P(this,jh,1)};var lh=function(a){_.x(this,a,"capi:f_vcon",null)};_.p(lh,_.w);_.z("capi:f_vcon",lh);lh.prototype.getState=function(){return _.P(this,jh,1)};
var mh=function(a){_.x(this,a,0,null)};_.p(mh,_.w);var nh=function(a){_.x(this,a,"capi:f_vfr",null)};_.p(nh,_.w);_.z("capi:f_vfr",nh);nh.prototype.getState=function(){return _.P(this,mh,1)};var oh=function(a){_.x(this,a,"capi:f_vfn",null)};_.p(oh,_.w);_.z("capi:f_vfn",oh);oh.prototype.getState=function(){return _.P(this,mh,1)};var ph=function(a){_.x(this,a,0,null)};_.p(ph,_.w);var qh=function(a){_.x(this,a,"capi:f_vmr",null)};_.p(qh,_.w);_.z("capi:f_vmr",qh);
qh.prototype.getState=function(){return _.P(this,ph,1)};var rh=function(a){_.x(this,a,"capi:f_vmn",null)};_.p(rh,_.w);_.z("capi:f_vmn",rh);rh.prototype.getState=function(){return _.P(this,ph,1)};var sh=function(a){_.x(this,a,0,null)};_.p(sh,_.w);var th=function(a){_.x(this,a,"capi:f_vpr",null)};_.p(th,_.w);_.z("capi:f_vpr",th);th.prototype.getState=function(){return _.P(this,sh,1)};var uh=function(a){_.x(this,a,"capi:f_vpn",null)};_.p(uh,_.w);_.z("capi:f_vpn",uh);
uh.prototype.getState=function(){return _.P(this,sh,1)};var vh=function(a){_.x(this,a,"capi:f_vsr",null)};_.p(vh,_.w);_.z("capi:f_vsr",vh);var wh=function(a){_.x(this,a,"capi:f_vsn",null)};_.p(wh,_.w);_.z("capi:f_vsn",wh);var xh=function(a){_.x(this,a,"capi:f_vtr",null)};_.p(xh,_.w);_.z("capi:f_vtr",xh);xh.prototype.setTitle=function(a){_.Ud(this,1,a)};var yh=function(a){_.x(this,a,"capi:f_vtn",null)};_.p(yh,_.w);_.z("capi:f_vtn",yh);yh.prototype.setTitle=function(a){_.Ud(this,1,a)};
var zh=function(a){_.x(this,a,0,null)};_.p(zh,_.w);var Ah=function(a){_.x(this,a,"capi:f_vvr",null)};_.p(Ah,_.w);_.z("capi:f_vvr",Ah);Ah.prototype.getState=function(){return _.P(this,zh,1)};var Bh=function(a){_.x(this,a,"capi:f_vvn",null)};_.p(Bh,_.w);_.z("capi:f_vvn",Bh);Bh.prototype.getState=function(){return _.P(this,zh,1)};var Ch=function(a){_.x(this,a,0,null)};_.p(Ch,_.w);var Dh=function(a){_.x(this,a,"capi:f_vpnr",null)};_.p(Dh,_.w);_.z("capi:f_vpnr",Dh);
Dh.prototype.getState=function(){return _.P(this,Ch,1)};var Eh=function(a){_.x(this,a,"capi:f_vpnn",null)};_.p(Eh,_.w);_.z("capi:f_vpnn",Eh);Eh.prototype.getState=function(){return _.P(this,Ch,1)};var Fh=function(a){_.x(this,a,0,null)};_.p(Fh,_.w);var Gh=function(a){_.x(this,a,"capi:f_vpsr",null)};_.p(Gh,_.w);_.z("capi:f_vpsr",Gh);Gh.prototype.getState=function(){return _.P(this,Fh,1)};var Hh=function(a){_.x(this,a,"capi:f_vpsn",null)};_.p(Hh,_.w);_.z("capi:f_vpsn",Hh);
Hh.prototype.getState=function(){return _.P(this,Fh,1)};var Ih=function(a){_.x(this,a,0,null)};_.p(Ih,_.w);var Jh=function(a){_.x(this,a,"capi:f_vdr",null)};_.p(Jh,_.w);_.z("capi:f_vdr",Jh);Jh.prototype.getState=function(){return _.P(this,Ih,1)};var Kh=function(a){_.x(this,a,"capi:f_vdn",null)};_.p(Kh,_.w);_.z("capi:f_vdn",Kh);Kh.prototype.getState=function(){return _.P(this,Ih,1)};var Lh=function(a){_.x(this,a,0,null)};_.p(Lh,_.w);var Mh=function(a){_.x(this,a,"capi:f_sp",null)};_.p(Mh,_.w); _.z("capi:f_sp",Mh);Mh.prototype.getState=function(){return _.P(this,Lh,1)};var Nh=function(a){_.x(this,a,"capi:f_spn",null)};_.p(Nh,_.w);_.z("capi:f_spn",Nh);Nh.prototype.getState=function(){return _.P(this,Lh,1)};
var Oh=function(a){_.x(this,a,"uvc",null)};_.p(Oh,_.w);_.z("uvc",Oh);var Ph=function(a){_.x(this,a,"capi:clstup",null)};_.p(Ph,_.w);_.z("capi:clstup",Ph);var Qh=function(a){_.x(this,a,"capi:r_clre",null)};_.p(Qh,_.w);_.z("capi:r_clre",Qh);var Rh=function(a){_.x(this,a,"capi:r_rrst",null)};_.p(Rh,_.w);_.z("capi:r_rrst",Rh);var Sh=function(a){_.x(this,a,"capi:r_rers",null)};_.p(Sh,_.w);_.z("capi:r_rers",Sh);var Th=function(a){_.x(this,a,"capi:r_recl",null)};_.p(Th,_.w);_.z("capi:r_recl",Th);var Uh=function(a){_.x(this,a,"capi:r_rstr",null)};_.p(Uh,_.w); _.z("capi:r_rstr",Uh);
var Vh=new _.L("nED8Yb"),Wh=new _.L("xclgJb");var Xh=function(a){_.x(this,a,"h_ec",null)};_.p(Xh,_.w);_.z("h_ec",Xh);var Yh=function(a){_.x(this,a,"h_fr",null)};_.p(Yh,_.w);_.z("h_fr",Yh);var Zh=function(a){_.x(this,a,"capii_c_cel",null)};_.p(Zh,_.w);_.z("capii_c_cel",Zh);var $h=function(a){_.x(this,a,"capi:rfc",null)};_.p($h,_.w);_.z("capi:rfc",$h);var ai=function(a){_.x(this,a,"capii_c_ucmc",null)};_.p(ai,_.w);_.z("capii_c_ucmc",ai);var bi=function(a){_.x(this,a,"capii_c_rc",null)};_.p(bi,_.w);_.z("capii_c_rc",bi);bi.prototype.ba=function(){return _.y(this,1)};
var ci=function(a){_.J.call(this);this.c=a.get(Vh);this.a=this.g=0;this.f=this.b=!1;a=new _.I(this);_.G(this,a);a.listen(this.c.qa(),"capii_c_ucmc",this.h);this.c.sendMessage(new ai)};_.p(ci,_.J);ci.prototype.h=function(a){a=new ai(a.Ya);this.b||(this.b=!0,this.f&&(_.M(a,5,!0),this.f=!1));var b=this.g!=_.y(a,1);this.g=Number(_.y(a,1));var c=this.a!=_.y(a,2);this.a=Number(_.y(a,2));_.y(a,5)?_.N(this,"h"):(b&&_.N(this,"j"),c&&_.N(this,"i"))};
var di=function(a){_.x(this,a,"h_rha",null)};_.p(di,_.w);_.z("h_rha",di);var ei=function(a){_.x(this,a,"h_ssf",null)};_.p(ei,_.w);_.z("h_ssf",ei);var fi=function(a,b){_.E.call(this);this.a=new _.I(this);_.G(this,this.a);this.a.listen(a.qa(),"h_ssf",function(a){a=new ei(a.Ya);a=_.y(a,1);var c;if(null!=a&&JSON&&JSON.parse)try{c=JSON.parse(a)}catch(f){}b(c)});var c=new di;_.M(c,1,1);qg(a,c)};_.p(fi,_.E);
var gi=function(a){_.x(this,a,"h_ext",null)};_.p(gi,_.w);_.z("h_ext",gi);var hi=function(a){_.x(this,a,"h_sru",null)};_.p(hi,_.w);_.z("h_sru",hi);var ki=function(){_.I.call(this);this.b=new _.Bd;_.G(this,this.b);this.v=this.g=this.u=this.a=null;this.B=_.Pc("quasar",""+(new Date).getTime());this.c=[];this.f=new Ag(this.B);_.G(this,this.f);this.j=null;this.f.connect();_.Yb(this,this.f,"message",this.N,!0,this);this.A=new Eg;_.G(this,this.A);this.listen(window,"unload",this.K);this.listen(window,"load",this.F);ii(this,(0,_.q)(function(){ji(this,["onHostReady"],"extensionLibrary")},this))},li;_.p(ki,_.I);var ii=function(a,b){null==a.c?b():a.c.push(b)};
ki.prototype.F=function(){var a=new _.$c(_.dd.ra().get("settings"));this.j=a.b[0];_.F(a);Fg(this.A,this.j,(0,_.q)(function(){if(!this.J&&-1!=this.j.lastIndexOf("talkgadget/")){var a=new ag;_.M(a,2,!0);var a=new _.Wb,c=this.A.b;if(c){_.M(a,3,c);var c=gf(this.j),d=c.c;null!=c.l&&(d+=":"+c.l);_.M(a,1,d);_.M(a,2,23);d=window.chrome.i18n.getMessage("@@ui_locale");_.M(a,4,d);_.M(a,13,!0);_.M(a,17,!0);c=_.se(c,"jsmode");null!=c&&_.M(a,11,c);c=new hf;_.M(c,2,!0);_.M(c,1,!0);_.Ud(a,14,c);a=new yg(a,void 0,
(0,_.q)(this.H,this));_.t(void 0)&&(a.a.f=void 0);c=a.a;var e=a.a.fa,d=a.a.b,f=gf(e),g=f.a;if(0<=g.indexOf("/u/"))d=e;else{e=g.lastIndexOf("_/");if(0>e||e!=g.length-2)g+="_/";f.a="/u/"+d+g;d=f.toString()}c.fa=d;a.a.l=a.a.l.replace("notifierclient","chat");a.u||(c=Nf(a.a.fa,a.a.a),a.u=new hg(a.a,c,a.M,a.document,void 0),_.G(a,a.u));ig(a.u,a.a.za,(0,_.q)(a.Qc,a),(0,_.q)(a.f,a,"_rosterIframeLoaded"));_.Jc&&(a.b=a.document.createElement("IFRAME"),a.b.id="gth-talk-plugin-frame-id",a.b.name="gth-talk-plugin-frame-id",
a.b.src=a.a.fa+"blank",a.b.style.cssText="width: 0px; height: 0px; position: absolute; top: 0px; left: 0px; visibility:hidden;",a.document.documentElement.appendChild(a.b),a.v=(0,_.q)(a.Pc,a,a.b.parentNode),a.b.parentNode.addEventListener("DOMAttrModified",a.v,!0));sg(a);this.a=a;this.b.a(Vh,this.a);this.u=new Ff(this.a);this.b.a(_.df,this.u);this.listen(this.u,"d",this.G);this.g=new Xg(this.a);this.b.a(Yg,this.g);this.v=new ci(this.b);this.b.a(Wh,this.v);this.listen(this.v,"i",this.D);this.D();a=
new fi(this.a,(0,_.q)(this.O,this));_.G(this,a);this.listen(this.a.qa(),"h_sru",this.R)}else ji(this,["changeDesktop",3],"desktopManager")}for(;this.c.length;)this.c.shift()();this.c=null},this))};ki.prototype.H=function(a,b){if("extensionMessage"==a)if("__reload__"==b)window.chrome.runtime.reload();else{var c=new _.Rc;_.Sc(c,JSON.parse(b)||{});this.f.sendMessage(c)}};
ki.prototype.G=function(){var a;switch(this.u.getState()){case Bf.LOADING:a=2;break;case Bf.pc:a=4;break;case Bf.oc:a=3;break;default:return}ji(this,["changeDesktop",a],"desktopManager")};
ki.prototype.N=function(a){ii(this,(0,_.q)(function(){var b=a.message;switch(b.a){case "onSendHostMessage":var c=new gi,b=b.content().toString();_.M(c,1,b);this.a&&this.a.sendMessage(c);break;case "onOpenConversation":var b=b.content()[0],c=this.g,d=new Og;_.M(d,1,b);qg(c.a,d);d=new Jg;_.M(d,1,[b]);b=new Pg;_.Ud(b,1,d);qg(c.a,b);break;case "h_icr":c=b.content()[0],this.g&&(b=this.g,d=new _.bf,_.M(d,1,c),qg(b.a,d))}},this))};
var ji=function(a,b,c){var d=new _.Rc;_.Tc(d,a.B,"p");_.Rd(d,"","e");_.Vc(d,b);null!=c&&(d.h=c);_.Uc(d,""+(0,_.m)());a.f.sendMessage(d)};ki.prototype.O=function(){var a=_.ef();window.open(a)};ki.prototype.R=function(a){a=new hi(a.Ya);ji(this,["setRosterUrl",_.y(a,2)],"dataChannelManager")};ki.prototype.D=function(){ji(this,["setUnreadIndicator",!!this.v.a],"desktopManager")};
if(!_.n(li)||null==li||li.J)li=new ki;
}catch(e){_._DumpException(e)}
}).call(this,this.default_datachannel);
// Google Inc.
