"use strict";this.default_feedback=this.default_feedback||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da,ea;_.n=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ud=function(a,c,f){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[c].apply(a,g)}};
_.ga=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.q=function(a,b,c){_.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.q.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==ea(a)};_.ka=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.la=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ma=function(a){return"array"==ea(a)};_.oa=function(){};_.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}; _.p(_.pa,Error);_.pa.prototype.name="CustomError";
var qa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ta=function(a,b){for(var c=0,d=qa(String(a)).split("."),e=qa(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",r=e[g]||"",D=RegExp("(\\d*)(\\D*)","g"),O=RegExp("(\\d*)(\\D*)","g");do{var fa=D.exec(l)||["","",""],Q=O.exec(r)||["","",""];if(0==fa[0].length&&0==Q[0].length)break;c=sa(0==fa[1].length?0:(0,window.parseInt)(fa[1],10),0==Q[1].length?0:(0,window.parseInt)(Q[1], 10))||sa(0==fa[2].length,0==Q[2].length)||sa(fa[2],Q[2])}while(0==c)}return c},sa=function(a,b){return a<b?-1:a>b?1:0};
_.u=Array.prototype;_.ua=_.u.indexOf?function(a,b,c){return _.u.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.va=_.u.lastIndexOf?function(a,b,c){return _.u.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.v=_.u.forEach?function(a,b,c){_.u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.wa=_.u.filter?function(a,b,c){return _.u.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var r=g[l];b.call(c,r,l,a)&&(e[f++]=r)}return e};_.xa=_.u.map?function(a,b,c){return _.u.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.ya=_.u.reduce?function(a,b,c,d){d&&(b=(0,_.q)(b,d));return _.u.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.v)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.za=_.u.some?function(a,b,c){return _.u.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Aa=function(a,b){var c=(0,_.ua)(a,b),d;(d=0<=c)&&_.u.splice.call(a,c,1);return d};
_.Ba=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Da,Fa;_.Ca=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Da=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ea=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Fa=function(a){var b=arguments.length;if(1==b&&_.ma(arguments[0]))return Fa.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var Ha;_.w=function(){};_.x=function(a,b,c,d){a.a=null;b||(b=c?[c]:[]);a.A=c?String(c):void 0;a.c=0===c?-1:0;a.P=b;a:{if(a.P.length&&(b=a.P.length-1,(c=a.P[b])&&"object"==typeof c&&!_.ma(c))){a.l=b-a.c;a.b=c;break a}a.l=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.l?(c+=a.c,a.P[c]=a.P[c]||_.Ga):a.b[c]=a.b[c]||_.Ga};_.Ga=[];_.y=function(a,b){if(b<a.l){var c=b+a.c,d=a.P[c];return d===_.Ga?a.P[c]=[]:d}d=a.b[b];return d===_.Ga?a.b[b]=[]:d};_.w.prototype.toString=function(){return this.P.toString()}; _.z=function(a,b){Ha[a]=b;b.messageId=a};Ha={};
Fa("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));var Ia=function(){this.b="";this.a=null},Ja=function(a){var b=new Ia;b.b=a;b.a=0};Ja("<!DOCTYPE html>");Ja("");_.Ka="StopIteration"in _.k?_.k.StopIteration:{message:"StopIteration",stack:""};_.La=function(){};_.La.prototype.next=function(){throw _.Ka;};_.La.prototype.ia=function(){return this};a:{var Na=_.k.navigator;if(Na){var Oa=Na.userAgent;if(Oa){_.Ma=Oa;break a}}_.Ma=""}var A=function(a){return-1!=_.Ma.indexOf(a)};var Pa=function(){return A("Opera")||A("OPR")},Qa=function(){return A("Edge")||A("Trident")||A("MSIE")},Ra=function(){return(A("Chrome")||A("CriOS"))&&!Pa()&&!Qa()};var Sa=function(){return A("Edge")};var Ta=function(){return A("iPhone")&&!A("iPod")&&!A("iPad")};_.B=function(a,b){this.b={};this.a=[];this.l=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("g");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.B?(c=a.S(),d=a.I()):(c=_.Ea(a),d=Da(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.B.prototype.Y=function(){return this.c};_.B.prototype.I=function(){Ua(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.B.prototype.S=function(){Ua(this);return this.a.concat()};
_.Wa=function(a,b){return Va(a.b,b)};_.B.prototype.T=function(){return 0==this.c};_.B.prototype.clear=function(){this.b={};this.l=this.c=this.a.length=0};_.B.prototype.remove=function(a){return Va(this.b,a)?(delete this.b[a],this.c--,this.l++,this.a.length>2*this.c&&Ua(this),!0):!1};
var Ua=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Va(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Va(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.B.prototype;_.h.get=function(a,b){return Va(this.b,a)?this.b[a]:b};_.h.set=function(a,b){Va(this.b,a)||(this.c++,this.a.push(a),this.l++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.S(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.h.clone=function(){return new _.B(this)};_.h.ia=function(a){Ua(this);var b=0,c=this.l,d=this,e=new _.La;e.next=function(){if(c!=d.l)throw Error("h");if(b>=d.a.length)throw _.Ka;var e=d.a[b++];return a?e:d.b[e]};return e};var Va=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Xa=function(a){if("function"==typeof a.I)return a.I();if(_.t(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Da(a)};
_.Ya=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.la(a)||_.t(a))(0,_.v)(a,b,c);else{var d;if("function"==typeof a.S)d=a.S();else if("function"!=typeof a.I)if(_.la(a)||_.t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Ea(a);else d=void 0;for(var e=_.Xa(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};
var bb,db,fb,gb,hb,jb,kb,lb;_.Za=Pa();_.C=Qa();_.$a=A("Gecko")&&!(-1!=_.Ma.toLowerCase().indexOf("webkit")&&!Sa())&&!(A("Trident")||A("MSIE"))&&!Sa();_.ab=-1!=_.Ma.toLowerCase().indexOf("webkit")&&!Sa();bb=_.k.navigator||null;_.cb=bb&&bb.platform||"";db=function(){var a=_.Ma;if(_.$a)return/rv\:([^\);]+)(\)|;)/.exec(a);if(_.C&&Sa())return/Edge\/([\d\.]+)/.exec(a);if(_.C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.ab)return/WebKit\/(\S+)/.exec(a)};
fb=function(){var a=_.k.document;return a?a.documentMode:void 0};gb=function(){if(_.Za&&_.k.opera){var a=_.k.opera.version;return _.ja(a)?a():a}var a="",b=db();b&&(a=b?b[1]:"");return _.C&&!Sa()&&(b=fb(),b>(0,window.parseFloat)(a))?String(b):a}();hb={};_.ib=function(a){return hb[a]||(hb[a]=0<=ta(gb,a))};jb=_.k.document;kb=fb();lb=!jb||!_.C||!kb&&Sa()?void 0:kb||("CSS1Compat"==jb.compatMode?(0,window.parseInt)(gb,10):5);
_.E=function(){this.J=this.J;this.l=this.l};_.E.prototype.J=!1;_.E.prototype.ub=function(){return this.J};_.E.prototype.K=function(){this.J||(this.J=!0,this.w())};_.G=function(a,b){_.mb(a,_.ha(_.F,b))};_.mb=function(a,b){a.J?b.call(void 0):(a.l||(a.l=[]),a.l.push(_.n(void 0)?(0,_.q)(b,void 0):b))};_.E.prototype.w=function(){if(this.l)for(;this.l.length;)this.l.shift()()};_.F=function(a){a&&"function"==typeof a.K&&a.K()};
_.nb=!_.C||_.C&&(Sa()||9<=lb);!_.$a&&!_.C||_.C&&_.C&&(Sa()||9<=lb)||_.$a&&_.ib("1.9.1");_.C&&_.ib("9");var ob=function(a){ob[" "](a);return a};ob[" "]=_.oa;_.pb=function(a,b){try{return ob(a[b]),!0}catch(c){}return!1};var qb,rb;qb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.tb=function(a){if(rb){rb=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.sb(c))&&c!=b.hostname)throw rb=!0,Error();}}return a.match(qb)};rb=_.ab;_.sb=function(a){return(a=_.tb(a)[3]||null)?(0,window.decodeURI)(a):a};
var ub=!_.C||_.C&&(Sa()||9<=lb),vb=_.C&&!_.ib("9");!_.ab||_.ib("528");_.$a&&_.ib("1.9b")||_.C&&_.ib("8")||_.Za&&_.ib("9.5")||_.ab&&_.ib("528");_.$a&&!_.ib("8")||_.C&&_.ib("9");_.H=function(a,b){this.type=a;this.a=this.target=b;this.jc=!0};_.H.prototype.b=function(){this.jc=!1};var wb=function(a,b){_.H.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&_.$a&&_.pb(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};_.p(wb,_.H); wb.prototype.b=function(){wb.C.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,vb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var xb,zb;xb="closure_listenable_"+(1E6*Math.random()|0);_.yb=function(a){return!(!a||!a[xb])};zb=0;var Ab=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.Qa=!!d;this.Xa=e;this.key=++zb;this.removed=this.Pa=!1},Bb=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Xa=null};var Cb=function(a){this.src=a;this.a={};this.b=0};Cb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Db(a,b,d,e);-1<g?(b=a[g],c||(b.Pa=!1)):(b=new Ab(b,this.src,f,!!d,e),b.Pa=c,a.push(b));return b};Cb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Db(e,b,c,d);return-1<b?(Bb(e[b]),_.u.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Eb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.Aa(a.a[c],b);d&&(Bb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};Cb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Bb(d[e]);delete this.a[c];this.b--}return b}; var Fb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Db(a,c,d,e));return-1<b?a[b]:null},Db=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.Qa==!!c&&f.Xa==d)return e}return-1};
var Gb,Hb,Ib,Ob,Pb,Ub,Tb,Qb,Nb,Vb;Gb="closure_lm_"+(1E6*Math.random()|0);Hb={};Ib=0;_.Jb=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.Jb(a,b[f],c,d,e);return null}c=_.Kb(c);return _.yb(a)?a.listen(b,c,d,e):_.Lb(a,b,c,!1,d,e)};
_.Lb=function(a,b,c,d,e,f){if(!b)throw Error("k");var g=!!e,l=Nb(a);l||(a[Gb]=l=new Cb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Ob();c.proxy=d;d.src=a;d.listener=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Pb(b.toString()),d);Ib++;return c};Ob=function(){var a=Qb,b=ub?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.Rb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)_.Rb(a,b[f],c,d,e);else c=_.Kb(c),_.yb(a)?a.Bb(b,c,d,e):a&&(a=Nb(a))&&(b=Fb(a,b,c,!!d,e))&&_.Sb(b)};_.Sb=function(a){if(_.ka(a)||!a||a.removed)return!1;var b=a.src;if(_.yb(b))return Eb(b.X,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Qa):b.detachEvent&&b.detachEvent(Pb(c),d);Ib--;(c=Nb(b))?(Eb(c,a),0==c.b&&(c.src=null,b[Gb]=null)):Bb(a);return!0};Pb=function(a){return a in Hb?Hb[a]:Hb[a]="on"+a};
Ub=function(a,b,c,d){var e=!0;if(a=Nb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Qa==c&&!f.removed&&(f=Tb(f,d),e=e&&!1!==f)}return e};Tb=function(a,b){var c=a.listener,d=a.Xa||a.src;a.Pa&&_.Sb(a);return c.call(d,b)};
Qb=function(a,b){if(a.removed)return!0;if(!ub){var c;if(!(c=b))a:{c=["window","event"];for(var d=_.k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new wb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--){c.a=e[l];var r=Ub(e[l],f,!0,c),d=d&&r}for(l=0;l<e.length;l++)c.a=e[l],r=Ub(e[l],
f,!1,c),d=d&&r}return d}return Tb(a,new wb(b,this))};Nb=function(a){a=a[Gb];return a instanceof Cb?a:null};Vb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Kb=function(a){if(_.ja(a))return a;a[Vb]||(a[Vb]=function(b){return a.handleEvent(b)});return a[Vb]};
_.Wb=function(a){_.x(this,a,"h_cc",null)};_.p(_.Wb,_.w);_.z("h_cc",_.Wb);_.Wb.prototype.ba=function(){return _.y(this,19)};_.I=function(a){_.E.call(this);this.M=a;this.h={}};_.p(_.I,_.E);var Xb=[];_.I.prototype.listen=function(a,b,c,d){return _.Yb(this,a,b,c,d)};_.Yb=function(a,b,c,d,e,f){_.ma(c)||(c&&(Xb[0]=c.toString()),c=Xb);for(var g=0;g<c.length;g++){var l=_.Jb(b,c[g],d||a.handleEvent,e||!1,f||a.M||a);if(!l)break;a.h[l.key]=l}return a};
_.I.prototype.Bb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)this.Bb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.M||this,c=_.Kb(c),d=!!d,b=_.yb(a)?Fb(a.X,String(b),c,d,e):a?(a=Nb(a))?Fb(a,b,c,d,e):null:null,b&&(_.Sb(b),delete this.h[b.key]);return this};_.I.prototype.removeAll=function(){_.Ca(this.h,_.Sb);this.h={}};_.I.prototype.w=function(){_.I.C.w.call(this);this.removeAll()};_.I.prototype.handleEvent=function(){throw Error("l");};
var Zb=function(a,b,c){this.l=c;this.c=a;this.f=b;this.b=0;this.a=null};Zb.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var $b=function(a,b){a.f(b);a.b<a.l&&(a.b++,b.next=a.a,a.a=b)};var ac,bc,cc;ac=function(a){_.k.setTimeout(function(){throw a;},0)};_.dc=function(a,b){var c=a;b&&(c=(0,_.q)(a,b));!_.ja(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(bc||(bc=cc()),bc(c)):_.k.setImmediate(c)};
cc=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!A("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.q)(function(a){if(("*"==d||
a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Qa()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Nb;c.Nb=null;a()}};return function(a){d.next={Nb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT"); b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};
var ec=function(){this.b=this.a=null},gc=new Zb(function(){return new fc},function(a){a.reset()},100);ec.prototype.add=function(a,b){var c=gc.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};ec.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var fc=function(){this.next=this.b=this.a=null};fc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};fc.prototype.reset=function(){this.next=this.b=this.a=null};
var lc=function(a,b){hc||ic();jc||(hc(),jc=!0);kc.add(a,b)},hc,ic=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve();hc=function(){a.then(mc)}}else hc=function(){_.dc(mc)}},jc=!1,kc=new ec,mc=function(){for(var a=null;a=kc.remove();){try{a.a.call(a.b)}catch(b){ac(b)}$b(gc,a)}jc=!1};
_.J=function(){_.E.call(this);this.X=new Cb(this);this.R=this;this.D=null};_.p(_.J,_.E);_.J.prototype[xb]=!0;_.h=_.J.prototype;_.h.addEventListener=function(a,b,c,d){_.Jb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Rb(this,a,b,c,d)};_.h.w=function(){_.J.C.w.call(this);this.X&&this.X.removeAll(void 0);this.D=null};_.h.listen=function(a,b,c,d){return this.X.add(String(a),b,!1,c,d)};_.h.Bb=function(a,b,c,d){return this.X.remove(String(a),b,c,d)}; _.h.ga=function(a,b,c){a=this.X.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Qa==b){var g=f.listener,l=f.Xa||f.src;f.Pa&&Eb(this.X,f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.jc};
var nc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},oc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var rc=function(a,b){this.a=0;this.h=void 0;this.l=this.b=this.c=null;this.f=this.g=!1;if(a==pc)qc(this,2,b);else try{var c=this;a.call(b,function(a){qc(c,2,a)},function(a){qc(c,3,a)})}catch(d){qc(this,3,d)}},sc=function(){this.next=this.c=this.b=this.l=this.a=null;this.f=!1},tc,uc,pc;sc.prototype.reset=function(){this.c=this.b=this.l=this.a=null;this.f=!1};tc=new Zb(function(){return new sc},function(a){a.reset()},100);uc=function(a,b,c){var d=tc.get();d.l=a;d.b=b;d.c=c;return d};pc=function(){};
_.wc=function(){var a,b=new rc(function(b){a=b});return new vc(b,a)};rc.prototype.then=function(a,b,c){return xc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};nc(rc);
var Ac=function(a){0==a.a&&lc(function(){var a=new yc(void 0);zc(this,a)},a)},zc=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.f||(d++,g.a==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.a&&1==d?zc(c,b):(f?(d=f,d.next==c.l&&(c.l=d),d.next=d.next.next):Bc(c),Cc(c,e,3,b)))}a.c=null}else qc(a,3,b)},Ec=function(a,b){a.b||2!=a.a&&3!=a.a||Dc(a);a.l?a.l.next=b:a.b=b;a.l=b},xc=function(a,b,c,d){var e=uc(null,null,null);e.a=new rc(function(a,g){e.l=b?function(c){try{var e=
b.call(d,c);a(e)}catch(D){g(D)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.n(e)&&b instanceof yc?g(b):a(e)}catch(D){g(D)}}:g});e.a.c=a;Ec(a,e);return e.a};rc.prototype.j=function(a){this.a=0;qc(this,2,a)};rc.prototype.u=function(a){this.a=0;qc(this,3,a)};
var qc=function(a,b,c){if(0==a.a){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(oc(c)){a.a=1;b=c;c=a.j;var d=a.u;b instanceof rc?Ec(b,uc(c||_.oa,d||null,a)):b.then(c,d,a);return}if(_.ia(c))try{if(d=c.then,_.ja(d)){Fc(a,c,d);return}}catch(e){b=3,c=e}}a.h=c;a.a=b;a.c=null;Dc(a);3!=b||c instanceof yc||Gc(a,c)}},Fc=function(a,b,c){a.a=1;var d=!1,e=function(b){d||(d=!0,a.j(b))},f=function(b){d||(d=!0,a.u(b))};try{c.call(b,e,f)}catch(g){f(g)}},Dc=function(a){a.g||(a.g=!0,lc(a.v,
a))},Bc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.l=null);return b};rc.prototype.v=function(){for(var a=null;a=Bc(this);)Cc(this,a,this.a,this.h);this.g=!1};
var Cc=function(a,b,c,d){if(3==c&&b.b&&!b.f)for(;a&&a.f;a=a.c)a.f=!1;if(b.a)b.a.c=null,Hc(b,c,d);else try{b.f?b.l.call(b.c):Hc(b,c,d)}catch(e){Ic.call(null,e)}$b(tc,b)},Hc=function(a,b,c){2==b?a.l.call(a.c,c):a.b&&a.b.call(a.c,c)},Gc=function(a,b){a.f=!0;lc(function(){a.f&&Ic.call(null,b)})},Ic=ac,yc=function(a){_.pa.call(this,a)};_.p(yc,_.pa);yc.prototype.name="cancel";var vc=function(a,b){this.b=a;this.a=b};
var Kc,Lc,Mc,Nc,Oc;_.Jc=A("Firefox");Kc=Ta()||A("iPod");Lc=A("iPad");Mc=A("Android")&&!(Ra()||A("Firefox")||Pa()||A("Silk"));Nc=Ra();Oc=A("Safari")&&!(Ra()||A("Coast")||Pa()||Qa()||A("Silk")||A("Android"))&&!(Ta()||A("iPad")||A("iPod"));_.Pc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Qc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.Rc=function(a,b){this.l=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.f=null;this.j=b||"u";this.a=this.h=null;this.g=[]};_.Rc.prototype.message=function(){var a={};a.i=this.a;a.m=this.g;a.r=this.j;a.o=this.h;a.s=this.b;a.st=this.c;a.d=this.f;a.dt=this.l;return a};_.Rc.prototype.message=_.Rc.prototype.message;
_.Sc=function(a,b){for(var c in b)switch(c){case "r":a.j=b[c];break;case "i":a.a=b[c];break;case "m":a.g=b[c];break;case "o":a.h=b[c];break;case "s":a.b=b[c];break;case "d":a.f=b[c];break;case "st":a.c=b[c];break;case "dt":a.l=b[c]}return a};_.Tc=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))};_.Uc=function(a,b){null!=b&&(a.a=b)};_.Vc=function(a,b){"object"==typeof b?a.g=b:a.g=[b]};_.Rc.prototype.source=function(){return this.b};_.Rc.prototype.target=function(){return this.f}; _.Rc.prototype.content=function(){return this.g};
_.Wc=function(a,b,c,d,e){_.E.call(this);this.b=a;this.Ma=b;this.a=typeof b;this.wb=c?c:!1;this.ea=!0;this.sb=d?d:!1;this.mb=e?e:!1};_.p(_.Wc,_.E);_.h=_.Wc.prototype;_.h.w=function(){_.Wc.C.w.call(this);this.b="";this.Ma=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.L=function(){return this.Ma};_.h.setEnabled=function(a){this.ea=a};
var Xc=function(a){return(a=a.exec(_.Ma))?a[1]:""},Yc=function(){if(_.Jc)return Xc(/Firefox\/([0-9.]+)/);if(_.C||_.Za)return gb;if(Nc)return Xc(/Chrome\/([0-9.]+)/);if(Oc&&!(Ta()||A("iPad")||A("iPod")))return Xc(/Version\/([0-9.]+)/);if(Kc||Lc){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Ma))return a[1]+"."+a[2]}else if(Mc)return(a=Xc(/Android\s+([0-9.]+)/))?a:Xc(/Version\/([0-9.]+)/);return""}();
_.$c=function(a){_.E.call(this);this.a=new _.B;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&_.Zc(this,a)};_.p(_.$c,_.E);_.ad=0<=ta(Yc,"23.0.1262.0")&&!_.Qc();_.$c.prototype.w=function(){_.$c.C.w.call(this);for(var a=this.a.S(),b=0;b<a.length;++b)_.F(this.a.get(a[b]));delete this.a};_.$c.prototype.getItem=function(a){return _.Wa(this.a,a)?this.a.get(a):null};
_.$c.prototype.setItem=function(a){this.a.set(a.id(),a)};_.Zc=function(a,b){for(var c in b){var d=b[c],e=null;_.Wa(a.a,c)?(e=a.a.get(c),e.Ma=d.value,d.changed&&(e.mb=d.changed)):(e=new _.Wc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.dd=function(){this.c=new _.B;this.a=null;this.b=!1;this.a=new bd;this.b=!0;_.cd(this)};_.dd.ra=function(){return _.dd.a?_.dd.a:_.dd.a=new _.dd};_.cd=function(a,b){var c=b||_.oa;a.b?c():window.chrome.storage.local.get((0,_.q)(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};_.dd.prototype.get=function(a){return this.a.get(a)};_.dd.prototype.set=function(a,b){var c=_.wc();this.a.set(a,b);c.a(void 0);return c.b};_.dd.prototype.remove=function(a){this.a.remove(a)};
_.dd.prototype.clear=function(){this.a.clear()};var bd=function(){this.a=window.localStorage};bd.prototype.clear=function(){this.a.clear()};bd.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ha[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};bd.prototype.set=function(a,b){var c=null;b instanceof _.w&&(b=b.P,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}}; bd.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
_.ed=function(a,b){this.b=a;this.a=b;this.constructor.Lb||(this.constructor.Lb={});this.constructor.Lb[this.toString()]=this};_.ed.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};_.K=function(a,b){_.ed.call(this,a,b)};_.p(_.K,_.ed);_.fd=function(a){this.a=a};_.gd=new _.fd("lib");_.L=function(a){this.a=a};_.L.prototype.toString=function(){return this.a};_.hd=new _.L("fJuxOc");_.id=new _.L("ZtVrH");_.jd=new _.L("zZa4xc");_.kd=new _.L("pVbxBc");_.ld=new _.L("byfTOb");_.md=new _.L("LEikZe");_.nd=new _.L("rJmJrc");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.od=function(a,b){this.l=[];this.D=b||null;this.b=this.a=!1;this.c=void 0;this.v=this.A=this.g=!1;this.f=0;this.j=null;this.B=0};_.od.prototype.u=function(a,b){this.g=!1;_.pd(this,a,b)};_.pd=function(a,b,c){a.a=!0;a.c=c;a.b=!b;qd(a)};_.sd=function(a){if(a.a){if(!a.v)throw new rd;a.v=!1}};_.od.prototype.h=function(a){_.sd(this);_.pd(this,!0,a)};_.td=function(a,b,c,d){a.l.push([b,c,d]);a.a&&qd(a)};
_.od.prototype.then=function(a,b,c){var d,e,f=new rc(function(a,b){d=a;e=b});_.td(this,d,function(a){"undefined"!=typeof _.ud&&a instanceof _.ud?Ac(f):e(a)});return f.then(a,b,c)};nc(_.od);
var vd=function(a){return(0,_.za)(a.l,function(a){return _.ja(a[1])})},qd=function(a){if(a.f&&a.a&&vd(a)){var b=a.f,c=wd[b];c&&(_.k.clearTimeout(c.Ta),delete wd[b]);a.f=0}a.j&&(a.j.B--,delete a.j);for(var b=a.c,d=c=!1;a.l.length&&!a.g;){var e=a.l.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var l=f.call(e||a.D,b);_.n(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);if(oc(b)||"function"===typeof _.k.Promise&&b instanceof _.k.Promise)d=!0,a.g=!0}catch(r){b=r,a.b=!0,vd(a)||(c=!0)}}a.c=b;d&&(l=(0,_.q)(a.u,
a,!0),d=(0,_.q)(a.u,a,!1),b instanceof _.od?(_.td(b,l,d),b.A=!0):b.then(l,d));c&&(b=new xd(b),wd[b.Ta]=b,a.f=b.Ta)},rd=function(){_.pa.call(this)};_.p(rd,_.pa);rd.prototype.message="Deferred has already fired";rd.prototype.name="AlreadyCalledError";var xd=function(a){this.Ta=_.k.setTimeout((0,_.q)(this.b,this),0);this.a=a};xd.prototype.b=function(){delete wd[this.Ta];throw this.a;};var wd={};

}catch(e){_._DumpException(e)}
try{
var Hd,Id,Kd,Ld,Md,Nd,Od,Vd,Wd,Xd,ae,be,ee,fe,ge,he,ie,je,ke,pe;Hd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};Id=function(a,b){b.push('"',a.replace(_.Ba,function(a){var b=Hd[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Hd[a]=b);return b}),'"')};Kd=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)Kd(a,b[f],c,d,e);return null}c=_.Kb(c);return _.yb(a)?a.X.add(String(b),c,!0,d,e):_.Lb(a,b,c,!0,d,e)};Ld="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
Md=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.ma(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Md(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Id(d,c),c.push(":"),Md(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Id(b,c);break;case "number":c.push((0,window.isFinite)(b)&&
!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "function":break;default:throw Error("d`"+typeof b);}}};Nd=function(){};Od=function(a,b,c,d,e,f){if(_.ma(c))for(var g=0;g<c.length;g++)Od(a,b,c[g],d,e,f);else{b=Kd(b,c,d||a.handleEvent,e,f||a.M||a);if(!b)return a;a.h[b.key]=b}return a};_.M=function(a,b,c){b<a.l?a.P[b+a.c]=c:a.b[b]=c};
_.Pd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ld.length;f++)c=Ld[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.Qd=function(a){var b=[];Md(new Nd,a,b);return b.join("")};_.Rd=function(a,b,c){null!=b&&(a.f=b,null!=c&&(a.l=c))};
_.N=function(a,b){var c,d=a.D;if(d)for(c=[];d;d=d.D)c.push(d);var d=a.R,e=b,f=e.type||e;if(_.t(e))e=new _.H(e,d);else if(e instanceof _.H)e.target=e.target||d;else{var g=e,e=new _.H(f,d);_.Pd(e,g)}var g=!0,l;if(c)for(var r=c.length-1;0<=r;r--)l=e.a=c[r],g=l.ga(f,!0,e)&&g;l=e.a=d;g=l.ga(f,!0,e)&&g;g=l.ga(f,!1,e)&&g;if(c)for(r=0;r<c.length;r++)l=e.a=c[r],g=l.ga(f,!1,e)&&g};_.Sd=function(a,b,c,d){return Od(a,b,c,d,void 0)};
_.Td=function(a){return _.k.JSON&&_.k.JSON.stringify?_.k.JSON.stringify(a.P):_.Qd(a.P)};_.Ud=function(a,b,c){a.a||(a.a={});var d=c?c.P:c;a.a[b]=c;_.M(a,b,d)};_.P=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=_.y(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};Vd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Wd=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};
Xd=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};_.Yd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.Zd=function(a){return _.u.concat.apply(_.u,arguments)};_.$d=function(a,b,c){this.b=this.a=null;this.c=a||null;this.l=!!c};
ae=function(a){a.a||(a.a=new _.B,a.b=0,a.c&&Xd(a.c,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};_.h=_.$d.prototype;_.h.Y=function(){ae(this);return this.b};_.h.add=function(a,b){ae(this);this.c=null;a=be(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b++;return this};_.h.remove=function(a){ae(this);a=be(this,a);return _.Wa(this.a,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};_.h.clear=function(){this.a=this.c=null;this.b=0};
_.h.T=function(){ae(this);return 0==this.b};var ce=function(a,b){ae(a);b=be(a,b);return _.Wa(a.a,b)};_.$d.prototype.S=function(){ae(this);for(var a=this.a.I(),b=this.a.S(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.$d.prototype.I=function(a){ae(this);var b=[];if(_.t(a))ce(this,a)&&(b=_.Zd(b,this.a.get(be(this,a))));else{a=this.a.I();for(var c=0;c<a.length;c++)b=_.Zd(b,a[c])}return b};
_.$d.prototype.set=function(a,b){ae(this);this.c=null;a=be(this,a);ce(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b++;return this};_.$d.prototype.get=function(a,b){var c=a?this.I(a):[];return 0<c.length?String(c[0]):b};_.de=function(a,b,c){a.remove(b);0<c.length&&(a.c=null,a.a.set(be(a,b),_.Yd(c)),a.b+=c.length)};
_.$d.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.S(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.I(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}return this.c=a.join("&")};_.$d.prototype.clone=function(){var a=new _.$d;a.c=this.c;this.a&&(a.a=this.a.clone(),a.b=this.b);return a};be=function(a,b){var c=String(b);a.l&&(c=c.toLowerCase());return c};
ee=function(a,b){b&&!a.l&&(ae(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.de(this,e,a))},a));a.l=b};fe=/#/g;ge=/[\#\?@]/g;he=/[\#\?]/g;ie=/[\#\?:]/g;je=/[#\/\?@]/g;ke=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,Vd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};_.le=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36)};
_.me=function(a,b){this.c=this.j=this.f="";this.l=null;this.g=this.a="";this.h=!1;var c;"undefined"!=typeof _.me&&a instanceof _.me?(this.h=_.n(b)?b:a.h,_.ne(this,a.f),this.j=a.j,this.c=a.c,_.oe(this,a.l),this.a=a.a,pe(this,a.b.clone()),this.g=a.g):a&&(c=_.tb(String(a)))?(this.h=!!b,_.ne(this,c[1]||"",!0),this.j=Wd(c[2]||""),this.c=Wd(c[3]||"",!0),_.oe(this,c[4]),this.a=Wd(c[5]||"",!0),pe(this,c[6]||"",!0),this.g=Wd(c[7]||"")):(this.h=!!b,this.b=new _.$d(null,0,this.h))};
_.me.prototype.toString=function(){var a=[],b=this.f;b&&a.push(ke(b,je,!0),":");if(b=this.c){a.push("//");var c=this.j;c&&a.push(ke(c,je,!0),"@");a.push((0,window.encodeURIComponent)(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.l;null!=b&&a.push(":",String(b))}if(b=this.a)this.c&&"/"!=b.charAt(0)&&a.push("/"),a.push(ke(b,"/"==b.charAt(0)?he:ie,!0));(b=this.b.toString())&&a.push("?",b);(b=this.g)&&a.push("#",ke(b,fe));return a.join("")};
_.qe=function(a,b){var c=a.clone(),d=!!b.f;d?_.ne(c,b.f):d=!!b.j;d?c.j=b.j:d=!!b.c;d?c.c=b.c:d=null!=b.l;var e=b.a;if(d)_.oe(c,b.l);else if(d=!!b.a){if("/"!=e.charAt(0))if(a.c&&!a.a)e="/"+e;else{var f=c.a.lastIndexOf("/");-1!=f&&(e=c.a.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),g=[],l=0;l<f.length;){var r=f[l++];"."==r?e&&l==f.length&&g.push(""):".."==r?((1<g.length||1==g.length&&""!=g[0])&&g.pop(),
e&&l==f.length&&g.push("")):(g.push(r),e=!0)}e=g.join("/")}else e=f}d?c.a=e:d=""!==b.b.toString();d?pe(c,Wd(b.b.toString())):d=!!b.g;d&&(c.g=b.g);return c};_.me.prototype.clone=function(){return new _.me(this)};_.ne=function(a,b,c){a.f=c?Wd(b,!0):b;a.f&&(a.f=a.f.replace(/:$/,""))};_.oe=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("i`"+b);a.l=b}else a.l=null};pe=function(a,b,c){b instanceof _.$d?(a.b=b,ee(a.b,a.h)):(c||(b=ke(b,ge)),a.b=new _.$d(b,0,a.h))};
_.R=function(a,b,c){a.b.set(b,c)};_.re=function(a,b,c){_.ma(c)||(c=[String(c)]);_.de(a.b,b,c)};_.se=function(a,b){return a.b.get(b)};_.te=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.ue=function(a,b){return 0<=(0,_.ua)(a,b)};
_.ve=function(a,b,c){if(_.ja(a))c&&(a=(0,_.q)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.q)(a.handleEvent,a);else throw Error("m");return 2147483647<b?-1:_.k.setTimeout(a,b||0)};_.we=function(a){_.k.clearTimeout(a)};_.xe=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.ye=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.la(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}}; _.ze=function(a,b){var c;a:{c=a.length;for(var d=_.t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:_.t(a)?a.charAt(c):a[c]};
var De,Be,Ce,Ee;_.Ae=function(){};De=function(a){var b=a.ja,c=function(a){c.C.constructor.call(this,a);var b=this.W.length;this.a=[];for(var d=0;d<b;++d)this.W[d].vd||(this.a[d]=new this.W[d](a))};_.p(c,b);for(var d=[];a;){if(b=a.ja){b.W&&_.ye(d,b.W);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ja(e[f])&&e[f]!==b){var g=!!e[f].Bc,l=Be(f,e,d,g);(g=Ce(f,e,l,g))&&(c.prototype[f]=g)}}a=a.C&&a.C.constructor}c.prototype.W=d;return c};
Be=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e};
Ce=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.W[c[0]].prototype[a].apply(this,arguments)}:b[a].Dc?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var r=this.a[c[e]];if(r=r?r[a].apply(r,d):this.W[c[e]].prototype[a].apply(this,d)){d=r;break a}}d=!1}return d}:b[a].Cc?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var r=this.a[c[e]],r=r?r[a].apply(r,
d):this.W[c[e]].prototype[a].apply(this,d);if(null!=r){d=r;break a}}d=void 0}return d}:b[a].dc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var r=this.a[c[e]];r?r[a].apply(r,d):this.W[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],r=0;r<c.length;++r){var D=this.a[c[r]];e.push(D?D[a].apply(D,d):this.W[c[r]].prototype[a].apply(this,d))}return e}:d||b[a].Dc||b[a].Cc||b[a].dc?e=null:e=Ee;return e};Ee=function(){return[]}; _.Ae.prototype.qb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var Fe;_.Ge=function(a){if(!a.nb){var b;for(b=a.constructor;b&&!b.ja;)b=b.C&&b.C.constructor;b.ja.Qb||(b.ja.Qb=De(b));b=new b.ja.Qb(a);a.nb=b;a.qb||(a.qb=Fe)}};Fe=function(a){return this.nb.qb(a)};var He=function(){};He.prototype.a=null;var Je=function(a){var b;(b=a.a)||(b={},Ie(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Ke,Le=function(){};_.p(Le,He);var Me=function(a){return(a=Ie(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},Ie=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("s");}return a.b};Ke=new Le;
var Oe,Re,We,Ye,Xe,Te;_.Ne=function(a){_.J.call(this);this.H=new _.B;this.u=a||null;this.b=!1;this.j=this.a=null;this.B="";this.f=0;this.c=this.A=this.g=this.v=!1;this.F=0;this.h=null;this.M="";this.G=this.da=!1};_.p(_.Ne,_.J);Oe=/^https?$/i;_.Pe=["POST","PUT"];_.Qe=[];_.Ne.prototype.V=function(){this.K();_.Aa(_.Qe,this)};
_.Ne.prototype.send=function(a,b,c,d){if(this.a)throw Error("t`"+this.B+"`"+a);b=b?b.toUpperCase():"GET";this.B=a;this.f=0;this.v=!1;this.b=!0;this.a=this.u?Me(this.u):Me(Ke);this.j=this.u?Je(this.u):Je(Ke);this.a.onreadystatechange=(0,_.q)(this.N,this);try{this.A=!0,this.a.open(b,String(a),!0),this.A=!1}catch(e){Re(this);return}a=c||"";var f=this.H.clone();d&&_.Ya(d,function(a,b){f.set(b,a)});d=_.ze(f.S(),Se);c=_.k.FormData&&a instanceof _.k.FormData;!_.ue(_.Pe,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.M&&(this.a.responseType=this.M);"withCredentials"in this.a&&(this.a.withCredentials=this.da);try{Te(this),0<this.F&&((this.G=Ue(this.a))?(this.a.timeout=this.F,this.a.ontimeout=(0,_.q)(this.O,this)):this.h=_.ve(this.O,this.F,this)),this.g=!0,this.a.send(a),this.g=!1}catch(g){Re(this)}};var Ue=function(a){return _.C&&_.ib(9)&&_.ka(a.timeout)&&_.n(a.ontimeout)},Se=function(a){return"content-type"==a.toLowerCase()};
_.Ne.prototype.O=function(){"undefined"!=typeof _.aa&&this.a&&(this.f=8,_.N(this,"timeout"),_.Ve(this,8))};Re=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.f=5;We(a);Xe(a)};We=function(a){a.v||(a.v=!0,_.N(a,"complete"),_.N(a,"error"))};_.Ve=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.f=b||7,_.N(a,"complete"),_.N(a,"abort"),Xe(a))};_.Ne.prototype.w=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Xe(this,!0));_.Ne.C.w.call(this)};
_.Ne.prototype.N=function(){this.J||(this.A||this.g||this.c?Ye(this):this.Z())};_.Ne.prototype.Z=function(){Ye(this)};Ye=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.j[1]||4!=(a.a?a.a.readyState:0)||2!=_.Ze(a)))if(a.g&&4==(a.a?a.a.readyState:0))_.ve(a.N,0,a);else if(_.N(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.$e(a)?(_.N(a,"complete"),_.N(a,"success")):(a.f=6,We(a))}finally{Xe(a)}}};
Xe=function(a,b){if(a.a){Te(a);var c=a.a,d=a.j[0]?_.oa:null;a.a=null;a.j=null;b||_.N(a,"ready");try{c.onreadystatechange=d}catch(e){}}};Te=function(a){a.a&&a.G&&(a.a.ontimeout=null);_.ka(a.h)&&(_.we(a.h),a.h=null)};
_.$e=function(a){var b=_.Ze(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=_.tb(String(a.B))[1]||null,!a&&window.self.location&&(a=window.self.location.protocol,a=a.substr(0,a.length-1)),b=!Oe.test(a?a.toLowerCase():"");c=b}return c};_.Ze=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};_.af=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
_.bf=function(a){_.x(this,a,"h_icr",null)};_.p(_.bf,_.w);_.z("h_icr",_.bf);_.cf=function(a){_.x(this,a,"h_cs",null)};_.p(_.cf,_.w);_.z("h_cs",_.cf);_.cf.prototype.getState=function(){return _.y(this,1)};_.df=new _.L("HwdKC");
}catch(e){_._DumpException(e)}
try{
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"}, chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"}};

}catch(e){_._DumpException(e)}
try{
_.mi=function(a){for(var b=a.a.S(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.L(),type:f.type(),multiple:f.wb,disabled:!f.ea,inverse:f.sb,changed:f.mb}}return c};_.ni=function(a,b){return _.t(b)?a.getElementById(b):b};_.S=function(a){return _.ni(window.document,a)};_.oi=new _.L("a");_.pi=new _.L("b");_.qi=new _.L("c");_.ri=new _.L("d");_.si=new _.L("e");_.ti=new _.L("f");_.ui=new _.L("g");_.vi=new _.L("h");_.Ed=new _.L("i");_.wi=new _.L("j");
_.T=function(a){var b;b=b||[];b.length||(b[0]="");var c=window.chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=_.k.ace_i18n[a.toLowerCase()])?c.message:_.k.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};
}catch(e){_._DumpException(e)}
try{
var xi,yi,zi,Ai,Bi,Di,Fi,Gi,Hi,Ii,Ji,Ki,Li,Mi,Ni,Oi,Pi,Ri,Si,Ti,Wi,Yi,bj;xi=function(a){return a.b[0]};yi=function(a){return(a=a.a.get("TopMost"))&&a.ea?a.L():!0};zi=function(){return!0};Ai={};Bi=0;_.Ci=function(a){a&&a!=window.chrome.windows.WINDOW_ID_NONE&&window.chrome.windows.update(a,{focused:!0})};Di=function(a){if(Ai[a])return Ai[a];a=String(a);if(!Ai[a]){var b=/function ([^\(]+)/.exec(a);Ai[a]=b?b[1]:"[Anonymous]"}return Ai[a]};_.Ei=function(a){return a[_.ba]||(a[_.ba]=++Bi)};
Fi=function(a){window.chrome.windows.getAll({populate:!0},function(b){for(var c=0;c<b.length;++c){var d=b[c].tabs;if(null!=d)for(var e=0;e<d.length;++e)if(d[e].selected&&d[e].url==a){_.Ci(b[c].id);return}}})};Gi=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};Hi=function(){return null!=window.navigator.platform.match(/Mac.*/)};Ii=function(){return!_.Qc()&&null!=window.navigator.platform.match(/Linux.*/)};Ji=function(a){this.a=a||_.k.document||window.document};
Ji.prototype.Vb=function(){var a=this.a;return a.parentWindow||a.defaultView};Ji.prototype.contains=_.te;
Ki=function(a,b){var c=[];if(_.ue(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Di(a)+"(");for(var d=a.arguments,e=0;d&&e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=Di(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(Ki(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")};Li=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+_.Ei(a):b.substr(0,1)+a};Mi=function(a){if(a instanceof _.La)return a;if("function"==typeof a.ia)return a.ia(!1);if(_.la(a)){var b=0,c=new _.La;c.next=function(){for(;;){if(b>=a.length)throw _.Ka;if(b in a)return a[b++];b++}};return c}throw Error("f");};Ni=function(a,b){return a>b?1:a<b?-1:0};
Oi=function(a,b){null!=a&&(window.open(a,"winid_"+(new Date).getTime(),b),_.ve((0,_.q)(Fi,null,a),1E3))};Pi=function(a){null!=a&&(a=window.chrome.runtime.getURL("images_4/"+a));return a};_.Qi=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};_.Qi.prototype.clone=function(){return new _.Qi(this.left,this.top,this.width,this.height)};
_.Qi.prototype.contains=function(a){return"undefined"!=typeof _.Qi&&a instanceof _.Qi?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};_.Qi.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.Qi.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.U=function(a){return _.U.b(a)};_.U.b=function(a){return a+"_"};_.U.h=function(){throw Error("n");};_.U.f=function(a){if(a&&a.constructor&&a.constructor.toString()===Object.toString()){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[_.U.b(c)]=a[c]);return b}throw Error("o");};_.U.c=!0;_.U.l=function(a){return a};_.U.g=function(){return!0};
Ri=[/^https?:\/\/.*.google.com(:[0-9]+)?\/talkgadget\/success/,/^https:\/\/accounts.google.com\/ServiceLogin/];Si=[1E4,12E4,144E5];Ti=[200,2E3,3E5];_.Ui=function(a,b){_.J.call(this);this.c=a||1;this.b=b||_.k;this.g=(0,_.q)(this.j,this);this.h=(0,_.m)()};_.p(_.Ui,_.J);_.Ui.prototype.f=!1;_.Ui.prototype.a=null;_.Ui.prototype.setInterval=function(a){this.c=a;this.a&&this.f?(this.stop(),_.Vi(this)):this.a&&this.stop()};
_.Ui.prototype.j=function(){if(this.f){var a=(0,_.m)()-this.h;0<a&&a<.8*this.c?this.a=this.b.setTimeout(this.g,this.c-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),_.N(this,"tick"),this.f&&(this.a=this.b.setTimeout(this.g,this.c),this.h=(0,_.m)()))}};_.Vi=function(a){a.f=!0;a.a||(a.a=a.b.setTimeout(a.g,a.c),a.h=(0,_.m)())};_.Ui.prototype.stop=function(){this.f=!1;this.a&&(this.b.clearTimeout(this.a),this.a=null)};_.Ui.prototype.w=function(){_.Ui.C.w.call(this);this.stop();delete this.b};
_.rg=function(a,b){this.width=a;this.height=b};_.rg.prototype.clone=function(){return new _.rg(this.width,this.height)};_.rg.prototype.T=function(){return!(this.width*this.height)};_.rg.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.rg.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};Wi=function(a){var b;b||(b=Ki(a||arguments.callee.caller,[]));return b};
_.Xi=function(a){this.a=new _.B;if(a){a=_.Xa(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}};_.h=_.Xi.prototype;_.h.Y=function(){return this.a.Y()};_.h.add=function(a){this.a.set(Li(a),a)};_.h.removeAll=function(a){a=_.Xa(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};_.h.remove=function(a){return this.a.remove(Li(a))};_.h.clear=function(){this.a.clear()};_.h.T=function(){return this.a.T()};_.h.contains=function(a){return _.Wa(this.a,Li(a))};_.h.I=function(){return this.a.I()};
_.h.clone=function(){return new _.Xi(this)};_.h.ia=function(){return this.a.ia(!1)};Yi=function(a,b){if(_.la(a))try{(0,_.v)(a,b,void 0)}catch(c){if(c!==_.Ka)throw c;}else{a=Mi(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(d){if(d!==_.Ka)throw d;}}};_.Zi=function(a,b,c){a.a||(a.a={});c=c||[];for(var d=[],e=0;e<c.length;e++)d[e]=c[e].P;a.a[b]=c;_.M(a,b,d)};
_.$i=function(a,b,c){a.a||(a.a={});if(!a.a[c]){for(var d=_.y(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.a[c]=e}b=a.a[c];b==_.Ga&&(b=a.a[c]=[]);return b};_.aj=function(a,b){a.sort(b||Ni)};bj=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};
var cj=function(a){_.x(this,a,"dpgi",null)};_.p(cj,_.w);_.z("dpgi",cj);var dj=function(a){_.x(this,a,"dri",null)};_.p(dj,_.w);_.z("dri",dj);_.fj=function(a){_.x(this,a,"di",ej)};_.p(_.fj,_.w);var ej=[6,7,10,11,12];_.z("di",_.fj);_.gj=function(a){_.x(this,a,"e",null)};_.p(_.gj,_.w);_.z("e",_.gj);_.hj=function(a){_.x(this,a,"f.ri",null)};_.p(_.hj,_.w);_.z("f.ri",_.hj);var ij=function(){_.E.call(this)},jj;_.p(ij,_.E);
_.lj=function(a,b){var c=jj;if(!(c.J||"undefined"!=typeof _.ud&&b instanceof _.ud))if(c.b){var c=c.b,d=kj();d["call-stack"]=Wi();a&&(d.message=a);var e;b instanceof Error?e=b:e=b||"";var f,g="";e&&(g=(e.lineNumber||"unknown")+":"+bj(e.fileName||"unknown")+":"+bj(e.message||"unknown"));var l="";for(f in d){var r;r="call-stack"==f?d[f].replace(/\(.*\)/g,""):d[f];l=l+f+":"+r+":"}f=g+"::"+l;g=c.c[f];g||(g={time:0,count:0},c.c[f]=g);if(1E4>(0,_.m)()-g.time)g.count++,1==g.count&&(d=kj(),d.message="Throttling: "+ f,c.a.a(e,d));else{g.count&&(d["dropped-instances"]=g.count);g.time=(0,_.m)();for(f=g.count=0;f<c.b.length;f++)c.b[f](e,d);c.a.a(e,d)}}else c.a&&10>c.a.length&&c.a.push([a,b])};jj=new ij;
_.mj=function(a){var b=window;if(!b.location){var c;try{c=_.Qd(b)}catch(d){c=_.Ea(b).toString()}_.lj(null,Error("x`"+c))}c=b.location&&b.location.ancestorOrigins;if(_.n(c))return c&&c.length?c[a?0:c.length-1]==b.location.origin:!0;try{return _.n((a?b.parent:b.top).location.href)}catch(e){return!1}};
var nj={},kj=function(){var a={};a.location=window.document.location.toString();if(_.mj(!1))try{a["top.location"]=window.top.location.toString()}catch(b){a["top.location"]="[external]"}else a["top.location"]="[external]";for(var c in nj)try{a[c]=nj[c].call()}catch(d){a[c]="[error] "+d.message}return a};
var pj=function(a,b,c){_.J.call(this);this.a=b.createElement("IFRAME");b.body.appendChild(this.a);this.a.src=a;c&&(this.a.id=c,this.a.name=c);a=new _.I(this);_.G(this,a);_.Sd(_.Sd(a,this.a,"load",this.c),this.a,"error",oj).listen(b.defaultView,"focus",this.b).listen(b.body,"focus",this.b)};_.p(pj,_.J);pj.prototype.b=function(){_.dc(this.a.focus,this.a)};pj.prototype.c=function(){this.b()};pj.prototype.w=function(){this.a.parentElement.removeChild(this.a);this.a=null;pj.C.w.call(this)};
var qj={},rj=function(){delete qj.$},oj=function(){qj.$(1)};_.sj=function(a){this.c=a;this.a=new _.$c;this.b=a.get(_.vi);this.a.setItem(new _.Wc("StartOnBrowserLaunch",!0,!1,!1));_.ad&&this.a.setItem(new _.Wc("TopMost",!0));a=new _.Wc("StopOnBrowserClose",!1,!1,!1);a.setEnabled(!1);this.a.setItem(a);a=new _.Wc("TrayIcon",!0,!1,!1);a.setEnabled(null!=window.navigator.platform.match(/Win.*/)||Ii()||Hi());this.a.setItem(a);(a=this.b.get("settings"))&&_.Zc(this.a,a);this.b.set("settings",_.mi(this.a))};_.ga("ace.core.SettingsManager",_.sj);
var tj=window.chrome.runtime&&window.chrome.runtime.getURL&&window.chrome.runtime.getURL("settingsdialog.html")||"";_.sj.prototype.f=function(){this.b.set("settings",_.mi(this.a));var a=_.V.f("setting");if(a&&0!=a.length)uj(a[0],"focus");else{var a=Math.floor((window.screen.height-200)/2),b=Math.floor((window.screen.width-520)/2),c=["width=520"];c.push("height=200");c.push("top="+a);c.push("left="+b);c.push("location=no");Oi(tj,c.join(","))}};_.sj.prototype.launchSettingsDialog=_.sj.prototype.f;
_.sj.prototype.g=function(){var a=new _.$c(_.mi(this.a)),b=this.b.get("settings");_.Zc(this.a,b);var c=new _.$c(b),b=c.getItem("StopOnBrowserClose"),a=a.getItem("TrayIcon"),c=c.getItem("TrayIcon");a.ea&&(c.L()||b.L()?(b=this.c.get(_.pi),vj(b),wj(b)):c.L()||b.L()||xj(this.c.get(_.pi)))};_.sj.prototype.updateSettingsFromStorage=_.sj.prototype.g;_.sj.prototype.l=function(){var a=_.V.f("setting");if(a)for(var b=0;b<a.length;++b)uj(a[b],"close")};_.sj.prototype.closeUI=_.sj.prototype.l; var uj=function(a,b){var c=new _.Rc;_.Uc(c,b);_.Vc(c,[]);_.V.b(a).sendMessage(c)};
var Dj=function(a,b){_.I.call(this);this.b=a;_.Pc("viewer",""+(new Date).getTime());this.f=this.g=null;this.v=_.V;this.D=(0,_.m)();this.u=a.get(_.pi);var c=a.get(_.ti),d=_.T("CHROME_EXT_SHORT_NAME"),e=Pi("viewer-14.png"),f=Pi("viewer-28.png"),d=yj(c,"viewer","viewer","viewer.html?viewer",d,e,f),e=b?_.P(b,_.zj,2).Fa():null,e=Aj(c,new _.rg(260,460),!0,e);Bj(c,d.id,e);this.a=d;this.a.onClosed.addListener((0,_.q)(this.K,this));Cj(this.a,(0,_.q)(this.A,this))};_.p(Dj,_.I);
Dj.prototype.w=function(){this.b.b(_.Ed)==this&&this.b.D();this.removeAll();Dj.C.w.call(this)};var Ej=function(a){_.F(a.g);a.g=null;_.F(a.f);a.f=null;_.ni(a.c.a,"retryInfo").style.display="none"};Dj.prototype.close=function(){_.F(this.a);this.b.b(_.Ed)==this&&this.b.D()};
Dj.prototype.A=function(){this.c=new Ji(Fj(this.a).document);this.a.setTitle(_.T("CHROME_EXT_SHORT_NAME"));_.ni(this.c.a,"retryMessage").textContent=_.T("CHROME_EXT_CANNOT_CONNECT");var a=_.ni(this.c.a,"retryLink");a.textContent=_.T("QUASAR_TRY_NOW");this.listen(a,"click",this.B);this.listen(this.v,"onStatusChange",this.j);this.j()};Dj.prototype.B=function(a){a.b();this.b.get(_.oi).g()};
Dj.prototype.j=function(){switch(this.u.a){case 3:if(!this.g){Ej(this);var a;a=this.b.get(_.ui).a;a=new _.me(a.b[0]);var b=new _.me("/talkgadget/qsignin");_.R(b,"passive","1");_.R(b,"hl",window.chrome.i18n.getMessage("@@ui_locale"));a=_.qe(a,b).toString();this.g=new pj(a,this.c.a)}break;case 2:Ej(this);break;case 6:Ej(this);_.ni(this.c.a,"retryInfo").style.display="block";break;default:Gj(this)}}; var Gj=function(a){a.f||(Ej(a),Hj(a.b.get(_.oi)).then(function(a){this.f=new pj(a,this.c.a,"popoutRoster")},void 0,a))};
var Ij=function(a,b){this.b=_.Yd(a);this.a=0;this.c=b||!1};Ij.prototype.reset=function(){this.a=0};Ij.prototype.L=function(a){var b=this.b[this.a],b=(.5+1*Math.random())*b;a&&Jj(this);return b};var Jj=function(a){a.c&&a.a==a.b.length-1||a.a++};var W=new _.fd("act"),Kj=new _.fd("impr"),Lj=new _.fd("tran"),Mj=new _.fd("perf");new _.K(W,1);new _.K(W,2);new _.K(W,3);new _.K(W,4);new _.K(W,5);new _.K(W,6);new _.K(W,7);new _.K(W,8);new _.K(W,9);new _.K(W,10);new _.K(W,11);new _.K(W,12);new _.K(W,25);new _.K(W,13);new _.K(W,14);new _.K(W,15);new _.K(W,22);new _.K(W,16);new _.K(W,17);new _.K(W,18);new _.K(W,19);new _.K(W,20);new _.K(W,21);new _.K(W,23);new _.K(W,24);new _.K(W,26);new _.K(W,27);new _.K(W,28);new _.K(W,29);new _.K(W,30); _.Nj=new _.K(Kj,1E3);new _.K(Lj,1001);new _.K(Mj,1002);
_.Oj=new _.L("k");var Pj=function(a,b,c){_.E.call(this);this.b=a;this.f=b||0;this.c=c;this.$=(0,_.q)(this.g,this)};_.p(Pj,_.E);Pj.prototype.a=0;Pj.prototype.w=function(){Pj.C.w.call(this);this.stop();delete this.b;delete this.c};var Qj=function(a,b){a.stop();a.a=_.ve(a.$,_.n(b)?b:a.f)};Pj.prototype.stop=function(){0!=this.a&&_.we(this.a);this.a=0};Pj.prototype.g=function(){this.a=0;this.b&&this.b.call(this.c)};
var Rj=function(a,b,c){_.E.call(this);this.c=a;this.b=b;this.a=c;this.$=(0,_.q)(this.Lc,this)};_.p(Rj,_.E);_.h=Rj.prototype;_.h.La=!1;_.h.ma=null;_.h.stop=function(){this.ma&&(_.we(this.ma),this.ma=null,this.La=!1)};_.h.w=function(){Rj.C.w.call(this);this.stop()};_.h.Lc=function(){this.ma=null;this.La&&(this.La=!1,Sj(this))};var Sj=function(a){a.ma=_.ve(a.$,a.b);a.c.call(a.a)};
_.X=function(a){_.I.call(this);this.a=a;this.c=a.get(_.pi);this.V=a.b(_.ti);this.R=_.wc();this.v=null;this.N=new Rj(this.g,6E4,this);_.G(this,this.N);a=(0,_.q)(this.Zc,this);qj.$=a;_.mb(this,rj);this.j=!1;this.B=new Ij(Si,!0);this.O=new Pj(this.md,this.B.L(),this);_.G(this,this.O);this.u=new Pj(this.ic,4E4,this);_.G(this,this.u);this.listen(window,"online",this.ed);this.G=this.H=0;this.b=new Ij(Ti);this.f=new Pj(this.xa,this.b.L(),this);_.G(this,this.f);window.chrome.cookies.onChanged.addListener((0,_.q)(this.ya,
this));this.F=(0,_.q)(this.da,this);this.D=(0,_.q)(this.Z,this);window.chrome.tabs.onUpdated.addListener(this.F);window.chrome.tabs.onCreated.addListener(this.D)};_.p(_.X,_.I);_.ga("ace.core.DataChannelManager",_.X);_.X.prototype.w=function(){window.chrome.tabs.onCreated.removeListener(this.D);window.chrome.tabs.onUpdated.removeListener(this.F);delete this.D;delete this.F;_.F(this.v);_.X.C.w.call(this)};
_.X.prototype.A=function(a,b){_.Tj(this);a:{var c=this.a,d=c.b(_.Ed);if(d){if(Uj(d.a)?!Vj(d.a):1E3>(0,_.m)()-d.D){d.a.focus();break a}d.close()}d=new Dj(c,b);c.a(_.Ed,d,!0)}};_.X.prototype.showViewer=_.X.prototype.A;_.X.prototype.Na=function(a,b){this.R.a(b||"")};_.X.prototype.setRosterUrl=_.X.prototype.Na;var Hj=function(a){return a.R.b};_.X.prototype.wa=function(){this.c.g(0,1);var a=this.a.b(_.Ed);a&&a.close();Wj(this);this.j=!1};_.X.prototype.terminateApplication=_.X.prototype.wa;
_.Tj=function(a){a.j||(a.listen(_.V,"onStatusChange",a.uc),a.g(),a.a.get(_.ui),a.j=!0)};_.X.prototype.g=function(){this.J||(this.c.g(0,2),Wj(this),this.v=new pj(window.chrome.runtime.getURL("datachannel.html"),window.document,"centralRoster"))};var Wj=function(a){a.V.g();a.a.get(_.si).b();_.F(a.v);a.v=null;a.R=_.wc()},Yj=function(a,b){var c=xi(a.a.get(_.ui).a);window.chrome.cookies.getAll({url:c},(0,_.q)(function(a){a=a&&Xj("SID",a)&&Xj("SSID",a)&&Xj("SAPISID",a);b(a)},a))};
_.X.prototype.za=function(a){var b=this.c.a;if(a){if(3==b){if(a=0==this.f.a)a=this.b,a=a.a<a.b.length;a&&Qj(this.f,this.b.L())}}else 3!=b&&this.g()};_.X.prototype.ya=function(a){"SSID"!=a.cookie.name&&"SAPISID"!=a.cookie.name||".google.com"!=a.cookie.domain||Yj(this,(0,_.q)(this.za,this))};var Xj=function(a,b){return(0,_.za)(b,function(b){var d=b.expirationDate&&b.expirationDate<(0,_.m)()/1E3;return b.name==a&&".google.com"==b.domain&&!d})};_.h=_.X.prototype;
_.h.uc=function(){this.O.stop();this.u.stop();switch(this.c.a){case 2:Qj(this.u);break;case 6:Qj(this.O,this.B.L());break;case 4:case 9:case 8:case 5:this.B.reset(),this.f.stop()}};_.h.ed=function(){if(4!=this.c.a){var a=this.N;a.ma?a.La=!0:Sj(a)}};_.h.md=function(){Jj(this.B);this.g()};_.h.Zc=function(a){Wj(this);switch(a){case 1:this.ic();break;case 2:a=this.N,a.ma?a.La=!0:Sj(a)}};_.h.ic=function(){this.J||(this.u.stop(),this.c.g(0,6))};
var Zj=function(a){a.G++;var b=a.a.get(_.Oj);1==a.G?b.a("qccro"):2==a.G?b.a("qccrt"):b.a("qccrm")};_.X.prototype.xa=function(){Jj(this.b);Zj(this);Yj(this,(0,_.q)(function(a){a&&this.g()},this))};_.X.prototype.da=function(a,b){b.url&&ak(this,b.url)};_.X.prototype.Z=function(a){a.url&&ak(this,a.url)}; var bk=function(a){a.H++;var b=a.a.get(_.Oj);1==a.H?b.a("qctro"):2==a.H?b.a("qctrt"):b.a("qctrm")},ak=function(a,b){(0,_.za)(Ri,function(a){return a.test(b)})&&0!=a.b.a&&(a.b.reset(),bk(a),0!=a.f.a&&Qj(a.f,a.b.L()))};
_.ck=function(a){this.v=a;this.B=a.get(_.ui);this.b=a.get(_.vi);this.a=1;this.f=this.u=null;this.h=this.c=!1;this.A=(0,_.q)(this.D,this);vj(this);wj(this);null!=this.b.a.get("UnreadIndicator")&&this.b.remove("UnreadIndicator");null!=this.b.a.get("app_status")&&this.b.remove("app_status");null!=this.b.a.get("user_id")&&this.b.remove("user_id");null!=this.b.a.get("client_state")&&this.b.remove("client_state")};_.p(_.ck,_.E);_.ga("ace.core.DesktopManager",_.ck);_.ck.prototype.w=function(){xj(this);_.ck.C.w.call(this)};
_.ck.prototype.g=function(a,b){this.a!=b&&(this.a=b,wj(this),dk(this),1==this.a&&(this.f=this.u=null,this.h=this.c=!1,xj(this),this.B.l(),this.v.get(_.si).b()),_.V.h())};_.ck.prototype.changeDesktop=_.ck.prototype.g;_.ck.prototype.F=function(a,b){this.c!=b&&(this.c=b,wj(this),dk(this))};_.ck.prototype.setMainUiShowing=_.ck.prototype.F;_.ck.prototype.j=function(){return this.c};
var vj=function(a){var b=a.B.a,c;if(c=null!=window.navigator.platform.match(/Win.*/)||Ii()||Hi())c=b.a.get("StopOnBrowserClose"),(c=c&&c.ea?c.L():!1)||(c=(b=b.a.get("TrayIcon"))&&b.ea?b.L():!1);c&&window.chrome.systemIndicator&&(window.chrome.systemIndicator.enable(),window.chrome.systemIndicator.onClicked.addListener(a.A))},xj=function(a){window.chrome.systemIndicator&&(window.chrome.systemIndicator.disable(),window.chrome.systemIndicator.onClicked.removeListener(a.A))},dk=function(a){var b;switch(a.a){case 2:b=
_.T("QUASAR_TIP_CONNECTING");break;case 3:b=_.T("QUASAR_TIP_NOT_LOGIN");break;case 4:case 9:case 8:b=a.c?a.h?_.T("CHROME_EXT_TIP_CONNECTED_MISSED_MESSAGES"):_.T("QUASAR_TIP_CONNECTED"):_.T("QUASAR_TIP_NOT_LOGIN");break;case 6:b=_.T("QUASAR_TIP_NOT_LOAD");break;default:b=_.T("QUASAR_TIP_DISCONNECTED")}a=a.f?"\n"+a.f:"";(b=_.T("CHROME_EXT_SHORT_NAME")+a+"\n"+b)&&window.chrome.browserAction.setTitle({title:b})};
_.ck.prototype.H=function(a,b,c){1!=this.a&&(a=b||_.T("QUASAR_MENUTEXT_UNKNOWN_USER"),a!=this.u&&(this.u=a),this.f=c)};_.ck.prototype.updateUserName=_.ck.prototype.H;_.ck.prototype.G=function(a,b){this.h!=b&&(this.h=b,wj(this),dk(this))};_.ck.prototype.setUnreadIndicator=_.ck.prototype.G;
var wj=function(a){window.chrome.browserAction.setIcon(ek(a,!0));window.chrome.systemIndicator&&window.chrome.systemIndicator.setIcon(ek(a))},fk=function(a){switch(a.a){case 2:return"offline_working";case 4:case 9:case 8:return a.c?a.h?"available_missed":"available":"offline";case 6:return"offline_unknown";default:return"offline"}},ek=function(a,b){var c=!b&&Hi()?"_mac_":"_",d=fk(a),e=window.chrome.runtime.getURL("images_4/presence/"+d+c+"19.png"),c=window.chrome.runtime.getURL("images_4/presence/"+ d+c+"38.png");return{path:{19:e,38:c}}};_.ck.prototype.D=function(){var a=_.V.a();this.v.get(_.Oj).a("qstcl");a.jb();a.b("onTrayClick",[1])};
var gk=function(a,b){this.a=a;this.j=b;this.u=window.chrome.runtime.getURL("images_4/icon-128x128.png");this.l=this.h=this.v="";this.f=0;this.b=[];this.g=""},hk=function(a){this.name=a;this.title=""};gk.prototype.setTitle=function(a){a&&(this.v=a)};
var ik=function(a){return a.replace(/^(\<br\>)+/,"")},jk=function(a){var b=a.v;a.h&&(b+=" "+a.h);var c=ik(a.l||7!=a.j?a.l||"":_.T("CHROME_EXT_ONEONONE_PLUS_HANGOUT_DETAILS")),d=(0,_.xa)(a.b,function(a){var b;if(!(b=a.title))a:{switch(a.name){case "join hangout":b=_.T("QUASAR_ANSWER_BUTTON_TEXT");break a;case "ignore":b=_.T("QUASAR_DECLINE_BUTTON_TEXT");break a}b=""}return{title:b}},a);return{type:"basic",iconUrl:a.u,title:b,message:c,buttons:d,priority:2}};
var kk=function(){this.b=new _.B;this.a=new _.Ui(18E5);_.Jb(this.a,"tick",(0,_.q)(this.c,this,this.b,0,200));_.Vi(this.a)};_.p(kk,_.E);kk.prototype.w=function(){this.a.K()};var lk=function(a,b){var c=null!=b.c?b.a+b.c:null;return null!=c?_.Wa(a.b,c):!1};kk.prototype.add=function(a){var b=null!=a.c?a.a+a.c:null;null!=b&&!lk(this,a)&&this.b.set(b,(0,_.m)()+18E5)};
kk.prototype.c=function(a,b,c){var d=a.Y();if(0!=d){var e=0;null!=b&&0<b&&(e=b<d?b:d);b=d;null!=c&&c<d&&(b=0<c?c:0);e>b&&(e=b);var f=[];c=a.ia(!0);Yi(c,function(b){f.push([b,a.get(b)])});f.sort(function(a,b){return a[1]-b[1]});if(31536E7<f[d-1][1]-f[0][1])a.clear();else{c=0;b=d-b;for(var d=d-e,e=(0,_.m)(),g=0;g<f.length;++g)if(c<b||c<d&&f[g][1]<=e)a.remove(f[g][0]),c+=1;else break}}};
var mk=function(a){_.x(this,a,"acr:bcr",null)};_.p(mk,_.w);_.z("acr:bcr",mk);var nk=function(a){_.x(this,a,"acr:srs",null)};_.p(nk,_.w);_.z("acr:srs",nk);var ok=function(a){_.x(this,a,"acr:rss",null)};_.p(ok,_.w);_.z("acr:rss",ok);var pk=function(a){_.x(this,a,"acr:rrs",null)};_.p(pk,_.w);_.z("acr:rrs",pk);var qk=function(a){_.x(this,a,"acr:rsr",null)};_.p(qk,_.w);_.z("acr:rsr",qk);_.sk=function(a){_.x(this,a,"acr:wrs",rk)};_.p(_.sk,_.w);var rk=[1];_.z("acr:wrs",_.sk); var tk=function(a){_.x(this,a,0,null)};_.p(tk,_.w);tk.prototype.ba=function(){return _.y(this,2)};tk.prototype.Ea=function(){return _.y(this,11)};
var xk;_.vk=function(a){_.x(this,a,"acq:rs",uk)};_.p(_.vk,_.w);var uk=[3];_.z("acq:rs",_.vk);var wk=function(a){_.x(this,a,0,null)};_.p(wk,_.w);wk.prototype.getState=function(){return _.y(this,6)};_.zj=function(a){_.x(this,a,0,null)};_.p(_.zj,_.w);_.zj.prototype.Fa=function(){return _.P(this,wk,1)};xk=function(a,b){_.Ud(a,1,b)};_.yk=function(a){_.x(this,a,0,null)};_.p(_.yk,_.w);_.yk.prototype.ba=function(){return _.y(this,1)};var zk=function(a,b){_.M(a,1,b)}; _.yk.prototype.Fa=function(){return _.P(this,wk,2)};var Ak=function(a,b){_.Ud(a,2,b)};_.yk.prototype.Ea=function(){return _.y(this,3)};var Bk=function(a,b){_.M(a,3,b)};
var Ck,Gk,Fk;Ck=function(a){this.c=a;this.a={};this.b=a.get(_.vi)};_.Dk=function(a,b){return(null!=a?a:"null")+"-"+(null!=b?b:"null")};
Gk=function(a,b){_.ve(a.reload,6E4,a);var c=[],d={},e=a.c.get(_.ti),f=_.$i(b,tk,1)||[];(0,_.v)(f,function(a){c.push(_.y(a,1));var b=_.Dk(a.ba(),a.Ea());d[b]=a});var g=c.length;c.push("viewer");Ek(e,c,(0,_.q)(function(a){for(var c=[],e=0;e<f.length;e++){var O=a[e];if(O){var fa=f[e],Q=new _.yk;Bk(Q,fa.Ea());zk(Q,fa.ba());Ak(Q,Fk(O));c.push(Q)}}_.aj(c,function(a,b){var c=b.Fa(),c=_.y(c,2),d;d=a.Fa();d=_.y(d,2);return c-d});(0,_.v)(c,function(a,b){var c=_.Dk(a.ba(),a.Ea());_.M(d[c],3,b)});a=a[g];e=new _.vk;
a&&(O=new _.zj,xk(O,Fk(a)),_.Ud(e,2,O));_.Zi(e,3,c);_.Zi(b,1,f);_.Ud(e,1,b);this.b.set("ReloadState",e.P);_.V.a().b("eventReloadStateSaved",[])},a))};Fk=function(a){var b=new wk;_.M(b,1,a.top);_.M(b,2,a.left);_.M(b,3,a.width);_.M(b,4,a.height);_.M(b,5,a.focused);_.M(b,6,a.state);_.M(b,7,a.alwaysOnTop);return b};Ck.prototype.read=function(){var a=this.l;this.l=null;_.V.a().b("eventReloadStateRead",[a&&a.P||null])};Ck.prototype.reload=function(){window.chrome.runtime.reload()};
_.Y=function(a){this.a=new Ck(a);this.b=a;window.chrome.runtime.onUpdateAvailable.addListener((0,_.q)(this.h,this))};_.ga("ace.core.ExtensionLibrary",_.Y);_.Y.prototype.h=function(){_.V.a().b("eventReloadClient",[]);_.ve(this.a.reload,864E5+288E5*Math.random(),this.a)};_.Y.prototype.B=function(a,b,c,d){a=_.V.b(b);null!=a&&_.n(d)&&d&&(d=a.j,null!=d&&null!=d.id&&(window.chrome.tabs.update(d.id,{selected:!0}),c&&window.chrome.tabs.get(d.id,function(a){_.Ci(a.windowId)})))};_.Y.prototype.selectTab=_.Y.prototype.B;
_.Y.prototype.j=function(a,b,c){c?Oi(b,"width=500,height=400"):window.chrome.tabs.create({url:b,selected:!0},function(a){null!=a?_.ve(function(){window.chrome.tabs.get(a.id,function(a){_.Ci(a.windowId)})},2E3):Oi(b)})};_.Y.prototype.openUrl=_.Y.prototype.j;_.Y.prototype.g=function(a,b){this.c=this.b.get(_.ti);this.c.focus(b)};_.Y.prototype.focusMoleByFrameId=_.Y.prototype.g;_.Y.prototype.f=function(){_.V.a().jb()};_.Y.prototype.showApplication=_.Y.prototype.f;
_.Y.prototype.A=function(a,b){var c=new _.sk(b);Gk(this.a,c)};_.Y.prototype.saveReloadState=_.Y.prototype.A;_.Y.prototype.u=function(){this.a.read()};_.Y.prototype.readReloadState=_.Y.prototype.u;_.Y.prototype.v=function(){this.a.reload()};_.Y.prototype.reloadExtension=_.Y.prototype.v;_.Y.prototype.l=function(){_.V.a().sc()};_.Y.prototype.onHostReady=_.Y.prototype.l;
var Hk=function(a,b){if(a)this.focused=a.focused,this.alwaysOnTop=a.alwaysOnTop,this.top=a.top,this.left=a.left,this.width=a.width,this.height=a.height,this.state=a.state;else if(b){this.focused=b.contentWindow.document.hasFocus();this.alwaysOnTop=b.isAlwaysOnTop();var c=b.getBounds();this.top=c.top;this.left=c.left;this.width=c.width;this.height=c.height;this.state=b.isMinimized()?"minimized":"normal"}else this.alwaysOnTop=this.focused=!1,this.height=this.width=this.left=this.top=0,this.state=""}; Hk.prototype.isMinimized=function(){return"minimized"==this.state};
var Ik=function(a,b,c){this.a=c||new Hk;c||(this.a.alwaysOnTop=yi(a.get(_.ui).a))};Ik.prototype.getProperties=function(){return this.a};var Kk=function(a,b,c){(b=b.g)?Jk(a.get(_.ti),b,function(b){c(new Ik(a,0,b))}):c(new Ik(a))};var Lk=function(){_.E.call(this);this.a=new _.Xi};_.p(Lk,_.E);Lk.prototype.ga=function(a){var b,c=Array.prototype.slice.call(arguments);(0,_.v)(this.a.I(),function(a){b=a.apply(null,c)});return b};Lk.prototype.addListener=function(a){this.a.add(a)};Lk.prototype.removeListener=function(a){this.a.remove(a)};Lk.prototype.w=function(){this.a.clear();Lk.C.w.call(this)};
var Ok=function(){_.E.call(this);this.b=[];this.j=new Lk;_.G(this,this.j);this.g=new Lk;_.G(this,this.g);this.onClosed=new Lk;this.h=!1;this.c=null;this.u=(0,_.q)(this.H,this);Mk.addListener(this.u);this.v=(0,_.q)(this.G,this);Nk.addListener(this.v)};_.p(Ok,_.E);Ok.prototype.w=function(){Vj(this)||void 0!=this.a&&window.chrome.windows.remove(this.a);Pk(this);this.u&&(Mk.removeListener(this.u),Nk.removeListener(this.v));_.F(this.onClosed);Ok.C.w.call(this)};
var Mk=window.chrome.windows&&window.chrome.windows.onRemoved,Nk=window.chrome.windows&&window.chrome.windows.onFocusChanged;Ok.prototype.create=function(a){window.chrome.windows.create(a,(0,_.q)(function(a){this.J?window.chrome.windows.remove(a.id):(this.a=a.id,Qk(this))},this))};
var Qk=function(a){if(null!=a.b&&Uj(a))if(Vj(a))Pk(a);else{for(;a.b.length&&!Vj(a);)a.b.shift()(a);a.b=null}},Uj=function(a){return!(!_.ka(a.a)||!a.f)},Cj=function(a,b){Vj(a)?Pk(a):null==a.b?b(a):a.b.push(b)},Vj=function(a){return!(!a.f||!a.f.closed)};Ok.prototype.H=function(){Vj(this)&&Pk(this)};var Pk=function(a){if(!a.h){var b=a.onClosed;a.onClosed=new Lk;_.ve((0,_.q)(function(){this.h||(this.h=!0,b.ga(this));_.F(b)},a))}};
Ok.prototype.G=function(a){if(a!=this.a){if(null===this.c||this.c)this.c&&(this.c=!1),this.g.ga(this)}else this.c=!0,this.j.ga(this)};var Fj=function(a){var b;b=a.a?a.f:null;return!b||Vj(a)?null:b};Ok.prototype.isMinimized=function(){return this.D.isMinimized()};Ok.prototype.isMaximized=function(){return this.D.isMaximized()};Ok.prototype.minimize=function(){Cj(this,(0,_.q)(function(){window.chrome.windows.update(this.a,{state:"minimized"})},this))};
Ok.prototype.focus=function(){Cj(this,(0,_.q)(function(){window.chrome.windows.update(this.a,{focused:!0})},this))};var Rk=function(a,b){Cj(a,(0,_.q)(function(){window.chrome.windows.update(this.a,{drawAttention:b})},a))};Ok.prototype.getProperties=function(a){Cj(this,_.ha(Sk,[this],function(b){a(b[0])}))}; var Sk=function(a,b){window.chrome.windows.getAll(function(c){var d={};(0,_.v)(c,function(a){d[a.id]=a});var e=[];(0,_.v)(a,function(a){var b;a&&Uj(a)&&!Vj(a)&&(b=d[a.a]);var c;b&&(c=new Hk(b));e.push(c)});b(e)})};
var Tk=function(){Ok.call(this)};_.p(Tk,Ok);Tk.prototype.setTitle=function(a){Cj(this,(0,_.q)(function(){Fj(this).document.title=a},this))};
var Vk=function(a,b){a.B=b;Cj(a,(0,_.q)(function(){Uk(this)},a))},Wk=function(a,b){a.F=b;Cj(a,(0,_.q)(function(){Uk(this)},a))},Uk=function(a){var b=Fj(a).document,c=b.querySelector("HEAD"),d=c.querySelectorAll("link[rel='shortcut icon']"),e=Pi("icon-24x24.png");a=[a.B||e,a.F];for(var e=_.Qc()?2:1,f="",g=0;g<e;++g)if(a[g]&&a!=f){var f=a[g],l=d[g];l||(l=b.createElement("LINK"),c.appendChild(l));l.rel="shortcut icon";var r=a[g];l.type=Gi(r,".ico")?"image/x-icon":Gi(r,".gif")?"image/gif":"image/png"; l.href=a[g]}};
var Zk,Xk,$k;_.Yk=function(a){this.a={};if(a)for(var b=0;b<a.length;b++)this.a[Xk(a[b])]=null;for(var c in Object.prototype);};Zk={};Xk=function(a){return a in Zk||32==String(a).charCodeAt(0)?" "+a:a};$k=function(a){return 32==a.charCodeAt(0)?a.substr(1):a};_.h=_.Yk.prototype;_.h.add=function(a){this.a[Xk(a)]=null};_.h.clear=function(){this.a={}};_.h.clone=function(){var a=new _.Yk,b;for(b in this.a)a.a[b]=null;return a};_.h.contains=function(a){return Xk(a)in this.a};
_.h.forEach=function(a,b){for(var c in this.a)a.call(b,$k(c),void 0,this)};_.h.Y=Object.keys?function(){return Object.keys(this.a).length}:function(){var a=0,b;for(b in this.a)a++;return a};_.h.I=Object.keys?function(){return Object.keys(this.a).map($k,this)}:function(){var a=[],b;for(b in this.a)a.push($k(b));return a};_.h.T=function(){for(var a in this.a)return!1;return!0};_.h.remove=function(a){a=Xk(a);return a in this.a?(delete this.a[a],!0):!1};_.h.ia=function(){return Mi(this.I())};
_.Z=function(a){_.E.call(this);this.j=a;this.a={};this.c={};this.b=new _.Yk;_.ga("__onPanelLoad",(0,_.q)(this.M,this));this.A=a.get(_.pi);a=new _.I(this);_.G(this,a);a.listen(_.V,"onStatusChange",this.D)};_.p(_.Z,_.E);_.ga("ace.core.PanelsManager",_.Z);_.Z.prototype.w=function(){for(var a in this.a)this.bb(this.a[a]);_.Z.C.w.call(this)};
_.Z.prototype.isMaximized=function(a,b){var c=function(a){a=a?!a.isMinimized():null;_.V.a().b("eventIsMinimizedResponse",[b,a])},d=this.a[b];d?d.getProperties(c):c(void 0)};_.Z.prototype.isMaximized=_.Z.prototype.isMaximized;
_.Z.prototype.N=function(a,b,c,d,e,f,g,l,r,D){a="panel.html?"+b;d=d||_.T("CHROME_EXT_SHORT_NAME");b=yj(this,b,l||b,a,d,e,g);Cj(b,(0,_.q)(this.u,this,c));c=new _.rg(280,420);r||D?(r=r||null,e=D||null,D=this.j.get(_.qi).a,r=_.Dk(r,e),(e=D.a[r])&&delete D.a[r],D=e?e.Fa():null):D=null;f=Aj(this,c,!!f,D);Bj(this,b.id,f)};_.Z.prototype.openPanel=_.Z.prototype.N;
_.Z.prototype.F=function(a,b,c,d,e,f,g){a="dialog.html?"+b;d=d||_.T("CHROME_EXT_SHORT_NAME");b=yj(this,b,b,a,d);Cj(b,(0,_.q)(this.u,this,c));c=Aj(this,new _.rg(f,g),e,null);c.Rc=!0;Bj(this,b.id,c);return b};_.Z.prototype.openDialog=_.Z.prototype.F;var yj=function(a,b,c,d,e,f,g){a.a[b]&&a.bb(a.a[b]);var l=new Tk;l.id=b;l.key=c;l.url=d;l.setTitle(e);Vk(l,f);Wk(l,g);a.a[b]=l;a.c[c]=b;return l};_.Z.prototype.u=function(a,b){b.A=new pj(a,Fj(b).document);_.G(b,b.A)};
var Aj=function(a,b,c,d){b={focus:c,va:null,width:b.width,height:b.height,minimize:!1};if(d){b.top=_.y(d,1);b.left=_.y(d,2);c=_.y(d,3);var e=_.y(d,4);_.y(d,7)?(b.width=Math.max(b.width,c),b.height=Math.max(b.height,e)):(b.width=c,b.height=e);"minimized"==d.getState()&&(b.minimize=!0);b.va=_.y(d,7);b.focus=_.y(d,5)}b.va="boolean"==typeof b.va?b.va:yi(a.j.get(_.ui).a);return b},Bj=function(a,b,c){var d=a.a[b];d.onClosed.addListener((0,_.q)(a.bb,a));d.j.addListener((0,_.q)(a.H,a));d.g.addListener((0,_.q)(a.G,
a));c.minimize&&d.minimize();b="panel";c.va||(b=Ii()?"popup":"detached_panel");c.Rc&&(b="popup");var e={type:b,url:d.url,focused:c.focus,width:c.width,height:c.height};if(b=null!=c.top&&null!=c.left)e.top=c.top,e.left=c.left;b||c.va?d.create(e):Ek(a,Object.keys(a.c),(0,_.q)(function(a){var b=window.screen,c;c=new _.rg(260,460);var r=new _.rg(280,420);c=new _.rg(Math.max(c.width,r.width),Math.max(c.height,r.height));for(var D=b.availWidth,O=b.availHeight-50,r=b.availTop+O%c.height,b=b.availLeft+D%
c.width,D=Math.floor(D/c.width),fa=Math.floor(O/c.height),O=Array(D*fa),Q=0;Q<a.length;Q++){var na=a[Q];if(na){for(var Mb=[na.left,na.left+na.width-1],na=[na.top,na.top+na.height-1],ra=0;2>ra;ra++)Mb[ra]=Math.floor(Math.max(0,Mb[ra]-b)/c.width),na[ra]=Math.floor(Math.max(0,na[ra]-r)/c.height);for(ra=Mb[0];ra<=Mb[1];ra++)for(var eb=na[0];eb<=na[1];eb++)ra<D&&eb<fa&&(O[ra+eb*D]=1)}}a=O.length-1;for(Q=O.length-1;0<=Q;Q--)if(!O[Q]){a=Q;break}O=a%D*c.width;e.top=r+Math.floor(a/D)*c.height+(c.height-e.height);
e.left=b+O+(c.width-e.width);d.create(e)},a))};_.Z.prototype.h=function(a,b){var c=this.a[b];c&&_.F(c)};_.Z.prototype.closePanel=_.Z.prototype.h;_.Z.prototype.g=function(){for(var a in this.a)0==this.a[a].url.indexOf("panel.html")&&this.h(0,a)};_.Z.prototype.closeAllPanels=_.Z.prototype.g;_.Z.prototype.setTitle=function(a,b,c){(a=this.a[b])&&a.setTitle(c)};_.Z.prototype.setTitle=_.Z.prototype.setTitle;_.Z.prototype.B=function(a,b,c){this.a[b]&&Rk(this.a[b],c)};_.Z.prototype.drawAttention=_.Z.prototype.B;
_.Z.prototype.focus=function(a){if(this.a[a]){var b=this.a[a];b.getProperties((0,_.q)(function(a){if(a&&(a=Fj(b),0==a.outerWidth&&0==a.outerHeight)){this.bb(b);return}b.focus()},this))}};_.Z.prototype.R=function(a,b,c){this.a[b]&&Vk(this.a[b],c)};_.Z.prototype.setPresence=_.Z.prototype.R;_.Z.prototype.O=function(a,b,c){this.a[b]&&Wk(this.a[b],c)};_.Z.prototype.setAvatar=_.Z.prototype.O;_.Z.prototype.f=function(a,b,c){for(var d in this.a)(b||this.b.contains(d))&&this.v(0,d,b,c);b||this.b.clear()};
_.Z.prototype.minimizeAllPanelsIfTopmost=_.Z.prototype.f;_.Z.prototype.v=function(a,b,c,d){var e=this.a[b];e&&e.getProperties((0,_.q)(function(a){if(a&&a.alwaysOnTop&&!this.J)if(c){var g;(g=!d)||(g=new _.Qi(a.left,a.top,a.width,a.height),g=g.left<=d.left+d.width&&d.left<=g.left+g.width&&g.top<=d.top+d.height&&d.top<=g.top+g.height);g&&!a.isMinimized()&&(e.minimize(),this.b.add(b))}else window.chrome.windows.update(e.a,{state:"normal"}),this.b.remove(b)},this))};
_.Z.prototype.minimizePanelIfTopmost=_.Z.prototype.v;_.Z.prototype.M=function(a){var b=this.a[a.location.search.substring(1)];b&&(b.f=a,Qk(b))};var Jk=function(a,b,c){a=a.a[a.c[b]];!a||Vj(a)?c(void 0):a.getProperties(c)},Ek=function(a,b,c){var d=[];(0,_.v)(b,(0,_.q)(function(a){d.push(this.a[this.c[a]])},a));Sk(d,c)};_.Z.prototype.bb=function(a){this.a[a.id]==a&&(this.b.remove(a.id),delete this.c[a.key],delete this.a[a.id],_.F(a))};_.Z.prototype.H=function(a){this.a[a.id]==a&&this.b.remove(a.id)}; _.Z.prototype.G=function(a){this.a[a.id]==a&&_.V.a().b("eventBlurred",[a.id])};_.Z.prototype.D=function(){3==this.A.a&&this.g()};
_.al=function(a){_.E.call(this);this.u=a;this.a=new _.B;this.j=new _.B;this.c=new kk;_.G(this,this.c);this.h=(0,_.q)(this.Vc,this);window.chrome.notifications.onClosed.addListener(this.h);this.f=(0,_.q)(this.vc,this);window.chrome.notifications.onClicked.addListener(this.f);this.g=(0,_.q)(this.Uc,this);window.chrome.notifications.onButtonClicked.addListener(this.g)};_.p(_.al,_.E);_.ga("ace.core.NotificationManager",_.al);
_.al.prototype.w=function(){_.v(this.a.I(),_.F);this.a.clear();window.chrome.notifications.onClosed.removeListener(this.h);window.chrome.notifications.onClicked.removeListener(this.f);window.chrome.notifications.onButtonClicked.removeListener(this.g);_.al.C.w.call(this)};
_.al.prototype.A=function(a,b){var c;if(b&&b.Content){c=[b.Id.ServiceUrl,b.Id.ServiceId].join(";");0==c.indexOf("bc")?c=new gk(c,2):0==c.indexOf("hangout")?(c=new gk(c,7),c.b.push(new hk("join hangout")),c.b.push(new hk("ignore"))):c=void 0;c.setTitle(b.Content.TitleText);c.h=b.Content.SubtitleText;c.l=b.Content.BodyText;c.c=b.Content.BodyTextId;var d=0;b.Content.EndTimeMs&&(d=b.Content.EndTimeMs,(0,window.isNaN)(d)||!(0,window.isFinite)(d))&&(d=0);d=d||(0,_.m)()+1E4;c.f=d;if(b.Content.ServiceIcon){var d=
c,e=b.Content.ServiceIcon;e&&(0==e.indexOf("images_4/")&&(e=window.chrome.runtime.getURL(e)),d.u=e)}b.Content.FrameId&&(c.g=b.Content.FrameId)}else c=null;c&&(_.V.a().b("eventLogImpression",["qnop"]),lk(this.c,c)||(this.c.add(c),bl(this,c)))};_.al.prototype.registerNotification=_.al.prototype.A;
var bl=function(a,b){2==b.j||b.g?Kk(a.u,b,function(c){c=c.getProperties();c.focused||c.alwaysOnTop||cl(a,b)}):cl(a,b)},cl=function(a,b){var c=b.a,d=b.f-(0,_.m)();0>=d?a.Yb(c):(a.a.set(c,b),window.chrome.notifications.create(c,jk(b),function(){_.V.a().b("eventLogImpression",["qtod"])}),_.we(a.j.get(c,null)),b.f!=Number.MAX_VALUE&&a.j.set(c,_.ve((0,_.q)(a.Yb,a,c),d)),_.V.a().b("eventLogImpression",["qnst"]))};_.al.prototype.b=function(){(0,_.v)((0,_.wa)(this.a.I(),zi),this.Ba,this)};
_.al.prototype.cleanAllNotifications=_.al.prototype.b;_.al.prototype.v=function(a,b){var c=this.a.get(b);c&&this.Ba(c)};_.al.prototype.cleanANotification=_.al.prototype.v;_.h=_.al.prototype;_.h.Ba=function(a){a=a.a;window.chrome.notifications.clear(a,_.oa);this.a.remove(a)};_.h.Vc=function(a,b){b&&this.a.get(a)&&(this.a.remove(a),dl(a,"toastEventOnClose"))};_.h.vc=function(a){var b=this.a.get(a);b&&(dl(a,"toastEventOnBody"),this.Ba(b))};
_.h.Uc=function(a,b){var c=this.a.get(a);c&&(dl(a,"toastEventOnButton",c.b[b].name),this.Ba(c))};_.h.Yb=function(a){var b=this.a.get(a);b&&(dl(a,"toastEventOnTimeout"),this.Ba(b))};var dl=function(a,b,c){var d=_.V;(d=d&&d.a())&&!d.J&&_.V.a().b(b,[a,c,"",!1])};
_.el=function(a){_.x(this,a,"f.mt",null)};_.p(_.el,_.w);_.z("f.mt",_.el);_.fl=function(a){_.x(this,a,"er",null)};_.p(_.fl,_.w);_.z("er",_.fl);_.fl.prototype.Ra=function(){return _.y(this,9)};_.fl.prototype.getData=function(){return _.y(this,4)};new _.Xi;_.C&&_.ib(8);var gl=function(){throw Error("y");};gl.prototype.a=null;gl.prototype.toString=function(){return this.content};var hl=function(){gl.call(this)};_.p(hl,gl);(function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=new b(String(a));void 0!==d&&(e.a=d);return e}})(hl);(function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=String(a);if(!e)return"";e=new b(e);void 0!==d&&(e.a=d);return e}})(hl);
var il=function(a,b){_.ed.call(this,a,b)};_.p(il,_.ed);_.jl=function(a){a?(this.a=_.y(a,1)||-1,_.y(a,2),_.y(a,3),_.y(a,4),_.y(a,13)):this.a=-1};_.kl=new _.jl;_.ll=function(){};_.p(_.ll,_.Ae);_.ll.prototype.b=function(){};_.ll.prototype.b.dc=!0;_.ll.C||_.p(_.ll,_.Ae);_.U.a={};_.U.a.hb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";_.U.a.fb=_.U.a.hb+"0123456789";_.U.a.ib=_.U.a.hb.length;_.U.a.gb=_.U.a.fb.length;_.U.a.Cb=-2147483648;_.U.a.nd=function(a){for(var b=0,c=a.length-1;0<=c;c--)b=b*(0==c?_.U.a.ib:_.U.a.gb)+_.U.a.fb.indexOf(a.charAt(c));return b+_.U.a.Cb};_.U.a.toString=function(a){var b=[],c=0;a-=_.U.a.Cb;b[c++]=_.U.a.hb.charAt(a%_.U.a.ib);for(a=Math.floor(a/_.U.a.ib);0<a;)b[c++]=_.U.a.fb.charAt(a%_.U.a.gb),a=Math.floor(a/_.U.a.gb);return b.join("")};
new il(_.gd,"f_req");
}catch(e){_._DumpException(e)}
try{
var $n=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=!0;if(b&&JSON&&JSON.stringify){var e=JSON.stringify(b);(d=1200>=e.length)&&(a.psdJson=e)}d=d||"help"!=a.flow;e={invalidPsd:!0};b=[a,d?b:e,c];c=c||_.k;c.GOOGLE_FEEDBACK_START_ARGUMENTS=b;d=a.serverUri||"//www.google.com/tools/feedback";if(e=c.GOOGLE_FEEDBACK_START)e.apply(c,b);else{b=d+"/load.js?";for(var f in a)d=a[f],null!=d&&!_.ia(d)&&(b+=(0,window.encodeURIComponent)(f)+"="+(0,window.encodeURIComponent)(d)+"&");a=c.document;f= a.createElement("script");f.src=b;a.body.appendChild(f)}};_.ga("userfeedback.api.startFeedback",$n);
var ao=function(){_.I.call(this);this.listen(window,"unload",this.K);window.document.title=_.T("CHROME_EXT_SHORT_NAME")+": "+_.T("CHROME_EXT_FEEDBACK_SUBTITLE");_.S("system-legend").innerText=_.T("QUASAR_FEEDBACK_SYSTEM_LEGEND");_.S("system-platform-label").innerText=_.T("QUASAR_FEEDBACK_PLATFORM_LABEL");_.S("system-platform-value").innerText=window.navigator.platform;_.S("system-user-agent-label").innerText=_.T("QUASAR_FEEDBACK_USER_AGENT_LABEL");_.S("system-user-agent-value").innerText=window.navigator.userAgent;
_.S("user-legend").innerText=_.T("CHROME_EXT_FEEDBACK_COMMENTS");_.S("privacy-legend").innerText=_.T("QUASAR_FEEDBACK_PRIVACY_LEGEND");_.S("privacy-text").innerText=_.T("QUASAR_FEEDBACK_PRIVACY_TEXT");var a=_.S("submit-button");a.innerText=_.T("QUASAR_FEEDBACK_SUBMIT_BUTTON");this.listen(a,"click",this.b);a=_.S("cancel-button");a.innerText=_.T("QUASAR_FEEDBACK_CANCEL_BUTTON");this.listen(a,"click",this.a);_.S("user-text-value").focus()};_.p(ao,_.I);
ao.prototype.b=function(){var a=_.S("user-text-value").value;if(a&&(a=a.trim())){var a={flow:"submit",serverUri:_.T("QUASAR_FEEDBACK_SERVER_URI"),productId:83052,locale:window.chrome.i18n.getMessage("@@ui_locale"),report:{description:a},callback:this.a},b={version:window.chrome.runtime.getManifest().version,build:window.chrome.runtime.id};_.S("submit-button").disabled=!0;$n(a,b)}};ao.prototype.a=function(){window.close()};window.addEventListener("load",function(){new ao},!1);

}catch(e){_._DumpException(e)}
}).call(this,this.default_feedback);
// Google Inc.
