"use strict";this.default_settings=this.default_settings||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da,ea;_.n=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ud=function(a,c,f){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[c].apply(a,g)}};
_.ga=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.q=function(a,b,c){_.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.q.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==ea(a)};_.ka=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.la=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ma=function(a){return"array"==ea(a)};_.oa=function(){};_.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}; _.p(_.pa,Error);_.pa.prototype.name="CustomError";
var qa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ta=function(a,b){for(var c=0,d=qa(String(a)).split("."),e=qa(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",r=e[g]||"",D=RegExp("(\\d*)(\\D*)","g"),O=RegExp("(\\d*)(\\D*)","g");do{var fa=D.exec(l)||["","",""],Q=O.exec(r)||["","",""];if(0==fa[0].length&&0==Q[0].length)break;c=sa(0==fa[1].length?0:(0,window.parseInt)(fa[1],10),0==Q[1].length?0:(0,window.parseInt)(Q[1], 10))||sa(0==fa[2].length,0==Q[2].length)||sa(fa[2],Q[2])}while(0==c)}return c},sa=function(a,b){return a<b?-1:a>b?1:0};
_.u=Array.prototype;_.ua=_.u.indexOf?function(a,b,c){return _.u.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.va=_.u.lastIndexOf?function(a,b,c){return _.u.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.v=_.u.forEach?function(a,b,c){_.u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.wa=_.u.filter?function(a,b,c){return _.u.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var r=g[l];b.call(c,r,l,a)&&(e[f++]=r)}return e};_.xa=_.u.map?function(a,b,c){return _.u.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.ya=_.u.reduce?function(a,b,c,d){d&&(b=(0,_.q)(b,d));return _.u.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.v)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.za=_.u.some?function(a,b,c){return _.u.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Aa=function(a,b){var c=(0,_.ua)(a,b),d;(d=0<=c)&&_.u.splice.call(a,c,1);return d};
_.Ba=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Da,Fa;_.Ca=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Da=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ea=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Fa=function(a){var b=arguments.length;if(1==b&&_.ma(arguments[0]))return Fa.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var Ha;_.w=function(){};_.x=function(a,b,c,d){a.a=null;b||(b=c?[c]:[]);a.A=c?String(c):void 0;a.c=0===c?-1:0;a.P=b;a:{if(a.P.length&&(b=a.P.length-1,(c=a.P[b])&&"object"==typeof c&&!_.ma(c))){a.l=b-a.c;a.b=c;break a}a.l=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.l?(c+=a.c,a.P[c]=a.P[c]||_.Ga):a.b[c]=a.b[c]||_.Ga};_.Ga=[];_.y=function(a,b){if(b<a.l){var c=b+a.c,d=a.P[c];return d===_.Ga?a.P[c]=[]:d}d=a.b[b];return d===_.Ga?a.b[b]=[]:d};_.w.prototype.toString=function(){return this.P.toString()}; _.z=function(a,b){Ha[a]=b;b.messageId=a};Ha={};
Fa("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));var Ia=function(){this.b="";this.a=null},Ja=function(a){var b=new Ia;b.b=a;b.a=0};Ja("<!DOCTYPE html>");Ja("");_.Ka="StopIteration"in _.k?_.k.StopIteration:{message:"StopIteration",stack:""};_.La=function(){};_.La.prototype.next=function(){throw _.Ka;};_.La.prototype.ia=function(){return this};a:{var Na=_.k.navigator;if(Na){var Oa=Na.userAgent;if(Oa){_.Ma=Oa;break a}}_.Ma=""}var A=function(a){return-1!=_.Ma.indexOf(a)};var Pa=function(){return A("Opera")||A("OPR")},Qa=function(){return A("Edge")||A("Trident")||A("MSIE")},Ra=function(){return(A("Chrome")||A("CriOS"))&&!Pa()&&!Qa()};var Sa=function(){return A("Edge")};var Ta=function(){return A("iPhone")&&!A("iPod")&&!A("iPad")};_.B=function(a,b){this.b={};this.a=[];this.l=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("g");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.B?(c=a.S(),d=a.I()):(c=_.Ea(a),d=Da(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.B.prototype.Y=function(){return this.c};_.B.prototype.I=function(){Ua(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.B.prototype.S=function(){Ua(this);return this.a.concat()};
_.Wa=function(a,b){return Va(a.b,b)};_.B.prototype.T=function(){return 0==this.c};_.B.prototype.clear=function(){this.b={};this.l=this.c=this.a.length=0};_.B.prototype.remove=function(a){return Va(this.b,a)?(delete this.b[a],this.c--,this.l++,this.a.length>2*this.c&&Ua(this),!0):!1};
var Ua=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Va(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Va(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.B.prototype;_.h.get=function(a,b){return Va(this.b,a)?this.b[a]:b};_.h.set=function(a,b){Va(this.b,a)||(this.c++,this.a.push(a),this.l++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.S(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.h.clone=function(){return new _.B(this)};_.h.ia=function(a){Ua(this);var b=0,c=this.l,d=this,e=new _.La;e.next=function(){if(c!=d.l)throw Error("h");if(b>=d.a.length)throw _.Ka;var e=d.a[b++];return a?e:d.b[e]};return e};var Va=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Xa=function(a){if("function"==typeof a.I)return a.I();if(_.t(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Da(a)};
_.Ya=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.la(a)||_.t(a))(0,_.v)(a,b,c);else{var d;if("function"==typeof a.S)d=a.S();else if("function"!=typeof a.I)if(_.la(a)||_.t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Ea(a);else d=void 0;for(var e=_.Xa(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};
var bb,db,fb,gb,hb,jb,kb,lb;_.Za=Pa();_.C=Qa();_.$a=A("Gecko")&&!(-1!=_.Ma.toLowerCase().indexOf("webkit")&&!Sa())&&!(A("Trident")||A("MSIE"))&&!Sa();_.ab=-1!=_.Ma.toLowerCase().indexOf("webkit")&&!Sa();bb=_.k.navigator||null;_.cb=bb&&bb.platform||"";db=function(){var a=_.Ma;if(_.$a)return/rv\:([^\);]+)(\)|;)/.exec(a);if(_.C&&Sa())return/Edge\/([\d\.]+)/.exec(a);if(_.C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.ab)return/WebKit\/(\S+)/.exec(a)};
fb=function(){var a=_.k.document;return a?a.documentMode:void 0};gb=function(){if(_.Za&&_.k.opera){var a=_.k.opera.version;return _.ja(a)?a():a}var a="",b=db();b&&(a=b?b[1]:"");return _.C&&!Sa()&&(b=fb(),b>(0,window.parseFloat)(a))?String(b):a}();hb={};_.ib=function(a){return hb[a]||(hb[a]=0<=ta(gb,a))};jb=_.k.document;kb=fb();lb=!jb||!_.C||!kb&&Sa()?void 0:kb||("CSS1Compat"==jb.compatMode?(0,window.parseInt)(gb,10):5);
_.E=function(){this.J=this.J;this.l=this.l};_.E.prototype.J=!1;_.E.prototype.ub=function(){return this.J};_.E.prototype.K=function(){this.J||(this.J=!0,this.w())};_.G=function(a,b){_.mb(a,_.ha(_.F,b))};_.mb=function(a,b){a.J?b.call(void 0):(a.l||(a.l=[]),a.l.push(_.n(void 0)?(0,_.q)(b,void 0):b))};_.E.prototype.w=function(){if(this.l)for(;this.l.length;)this.l.shift()()};_.F=function(a){a&&"function"==typeof a.K&&a.K()};
_.nb=!_.C||_.C&&(Sa()||9<=lb);!_.$a&&!_.C||_.C&&_.C&&(Sa()||9<=lb)||_.$a&&_.ib("1.9.1");_.C&&_.ib("9");var ob=function(a){ob[" "](a);return a};ob[" "]=_.oa;_.pb=function(a,b){try{return ob(a[b]),!0}catch(c){}return!1};var qb,rb;qb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.tb=function(a){if(rb){rb=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.sb(c))&&c!=b.hostname)throw rb=!0,Error();}}return a.match(qb)};rb=_.ab;_.sb=function(a){return(a=_.tb(a)[3]||null)?(0,window.decodeURI)(a):a};
var ub=!_.C||_.C&&(Sa()||9<=lb),vb=_.C&&!_.ib("9");!_.ab||_.ib("528");_.$a&&_.ib("1.9b")||_.C&&_.ib("8")||_.Za&&_.ib("9.5")||_.ab&&_.ib("528");_.$a&&!_.ib("8")||_.C&&_.ib("9");_.H=function(a,b){this.type=a;this.a=this.target=b;this.jc=!0};_.H.prototype.b=function(){this.jc=!1};var wb=function(a,b){_.H.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&_.$a&&_.pb(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};_.p(wb,_.H); wb.prototype.b=function(){wb.C.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,vb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var xb,zb;xb="closure_listenable_"+(1E6*Math.random()|0);_.yb=function(a){return!(!a||!a[xb])};zb=0;var Ab=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.Qa=!!d;this.Xa=e;this.key=++zb;this.removed=this.Pa=!1},Bb=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Xa=null};var Cb=function(a){this.src=a;this.a={};this.b=0};Cb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Db(a,b,d,e);-1<g?(b=a[g],c||(b.Pa=!1)):(b=new Ab(b,this.src,f,!!d,e),b.Pa=c,a.push(b));return b};Cb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Db(e,b,c,d);return-1<b?(Bb(e[b]),_.u.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Eb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.Aa(a.a[c],b);d&&(Bb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};Cb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Bb(d[e]);delete this.a[c];this.b--}return b}; var Fb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Db(a,c,d,e));return-1<b?a[b]:null},Db=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.Qa==!!c&&f.Xa==d)return e}return-1};
var Gb,Hb,Ib,Ob,Pb,Ub,Tb,Qb,Nb,Vb;Gb="closure_lm_"+(1E6*Math.random()|0);Hb={};Ib=0;_.Jb=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.Jb(a,b[f],c,d,e);return null}c=_.Kb(c);return _.yb(a)?a.listen(b,c,d,e):_.Lb(a,b,c,!1,d,e)};
_.Lb=function(a,b,c,d,e,f){if(!b)throw Error("k");var g=!!e,l=Nb(a);l||(a[Gb]=l=new Cb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Ob();c.proxy=d;d.src=a;d.listener=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Pb(b.toString()),d);Ib++;return c};Ob=function(){var a=Qb,b=ub?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.Rb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)_.Rb(a,b[f],c,d,e);else c=_.Kb(c),_.yb(a)?a.Bb(b,c,d,e):a&&(a=Nb(a))&&(b=Fb(a,b,c,!!d,e))&&_.Sb(b)};_.Sb=function(a){if(_.ka(a)||!a||a.removed)return!1;var b=a.src;if(_.yb(b))return Eb(b.X,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Qa):b.detachEvent&&b.detachEvent(Pb(c),d);Ib--;(c=Nb(b))?(Eb(c,a),0==c.b&&(c.src=null,b[Gb]=null)):Bb(a);return!0};Pb=function(a){return a in Hb?Hb[a]:Hb[a]="on"+a};
Ub=function(a,b,c,d){var e=!0;if(a=Nb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Qa==c&&!f.removed&&(f=Tb(f,d),e=e&&!1!==f)}return e};Tb=function(a,b){var c=a.listener,d=a.Xa||a.src;a.Pa&&_.Sb(a);return c.call(d,b)};
Qb=function(a,b){if(a.removed)return!0;if(!ub){var c;if(!(c=b))a:{c=["window","event"];for(var d=_.k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new wb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--){c.a=e[l];var r=Ub(e[l],f,!0,c),d=d&&r}for(l=0;l<e.length;l++)c.a=e[l],r=Ub(e[l],
f,!1,c),d=d&&r}return d}return Tb(a,new wb(b,this))};Nb=function(a){a=a[Gb];return a instanceof Cb?a:null};Vb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Kb=function(a){if(_.ja(a))return a;a[Vb]||(a[Vb]=function(b){return a.handleEvent(b)});return a[Vb]};
_.Wb=function(a){_.x(this,a,"h_cc",null)};_.p(_.Wb,_.w);_.z("h_cc",_.Wb);_.Wb.prototype.ba=function(){return _.y(this,19)};_.I=function(a){_.E.call(this);this.M=a;this.h={}};_.p(_.I,_.E);var Xb=[];_.I.prototype.listen=function(a,b,c,d){return _.Yb(this,a,b,c,d)};_.Yb=function(a,b,c,d,e,f){_.ma(c)||(c&&(Xb[0]=c.toString()),c=Xb);for(var g=0;g<c.length;g++){var l=_.Jb(b,c[g],d||a.handleEvent,e||!1,f||a.M||a);if(!l)break;a.h[l.key]=l}return a};
_.I.prototype.Bb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)this.Bb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.M||this,c=_.Kb(c),d=!!d,b=_.yb(a)?Fb(a.X,String(b),c,d,e):a?(a=Nb(a))?Fb(a,b,c,d,e):null:null,b&&(_.Sb(b),delete this.h[b.key]);return this};_.I.prototype.removeAll=function(){_.Ca(this.h,_.Sb);this.h={}};_.I.prototype.w=function(){_.I.C.w.call(this);this.removeAll()};_.I.prototype.handleEvent=function(){throw Error("l");};
var Zb=function(a,b,c){this.l=c;this.c=a;this.f=b;this.b=0;this.a=null};Zb.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var $b=function(a,b){a.f(b);a.b<a.l&&(a.b++,b.next=a.a,a.a=b)};var ac,bc,cc;ac=function(a){_.k.setTimeout(function(){throw a;},0)};_.dc=function(a,b){var c=a;b&&(c=(0,_.q)(a,b));!_.ja(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(bc||(bc=cc()),bc(c)):_.k.setImmediate(c)};
cc=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!A("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.q)(function(a){if(("*"==d||
a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Qa()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Nb;c.Nb=null;a()}};return function(a){d.next={Nb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT"); b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};
var ec=function(){this.b=this.a=null},gc=new Zb(function(){return new fc},function(a){a.reset()},100);ec.prototype.add=function(a,b){var c=gc.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};ec.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var fc=function(){this.next=this.b=this.a=null};fc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};fc.prototype.reset=function(){this.next=this.b=this.a=null};
var lc=function(a,b){hc||ic();jc||(hc(),jc=!0);kc.add(a,b)},hc,ic=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve();hc=function(){a.then(mc)}}else hc=function(){_.dc(mc)}},jc=!1,kc=new ec,mc=function(){for(var a=null;a=kc.remove();){try{a.a.call(a.b)}catch(b){ac(b)}$b(gc,a)}jc=!1};
_.J=function(){_.E.call(this);this.X=new Cb(this);this.R=this;this.D=null};_.p(_.J,_.E);_.J.prototype[xb]=!0;_.h=_.J.prototype;_.h.addEventListener=function(a,b,c,d){_.Jb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Rb(this,a,b,c,d)};_.h.w=function(){_.J.C.w.call(this);this.X&&this.X.removeAll(void 0);this.D=null};_.h.listen=function(a,b,c,d){return this.X.add(String(a),b,!1,c,d)};_.h.Bb=function(a,b,c,d){return this.X.remove(String(a),b,c,d)}; _.h.ga=function(a,b,c){a=this.X.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Qa==b){var g=f.listener,l=f.Xa||f.src;f.Pa&&Eb(this.X,f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.jc};
var nc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},oc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var rc=function(a,b){this.a=0;this.h=void 0;this.l=this.b=this.c=null;this.f=this.g=!1;if(a==pc)qc(this,2,b);else try{var c=this;a.call(b,function(a){qc(c,2,a)},function(a){qc(c,3,a)})}catch(d){qc(this,3,d)}},sc=function(){this.next=this.c=this.b=this.l=this.a=null;this.f=!1},tc,uc,pc;sc.prototype.reset=function(){this.c=this.b=this.l=this.a=null;this.f=!1};tc=new Zb(function(){return new sc},function(a){a.reset()},100);uc=function(a,b,c){var d=tc.get();d.l=a;d.b=b;d.c=c;return d};pc=function(){};
_.wc=function(){var a,b=new rc(function(b){a=b});return new vc(b,a)};rc.prototype.then=function(a,b,c){return xc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};nc(rc);
var Ac=function(a){0==a.a&&lc(function(){var a=new yc(void 0);zc(this,a)},a)},zc=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.f||(d++,g.a==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.a&&1==d?zc(c,b):(f?(d=f,d.next==c.l&&(c.l=d),d.next=d.next.next):Bc(c),Cc(c,e,3,b)))}a.c=null}else qc(a,3,b)},Ec=function(a,b){a.b||2!=a.a&&3!=a.a||Dc(a);a.l?a.l.next=b:a.b=b;a.l=b},xc=function(a,b,c,d){var e=uc(null,null,null);e.a=new rc(function(a,g){e.l=b?function(c){try{var e=
b.call(d,c);a(e)}catch(D){g(D)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.n(e)&&b instanceof yc?g(b):a(e)}catch(D){g(D)}}:g});e.a.c=a;Ec(a,e);return e.a};rc.prototype.j=function(a){this.a=0;qc(this,2,a)};rc.prototype.u=function(a){this.a=0;qc(this,3,a)};
var qc=function(a,b,c){if(0==a.a){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(oc(c)){a.a=1;b=c;c=a.j;var d=a.u;b instanceof rc?Ec(b,uc(c||_.oa,d||null,a)):b.then(c,d,a);return}if(_.ia(c))try{if(d=c.then,_.ja(d)){Fc(a,c,d);return}}catch(e){b=3,c=e}}a.h=c;a.a=b;a.c=null;Dc(a);3!=b||c instanceof yc||Gc(a,c)}},Fc=function(a,b,c){a.a=1;var d=!1,e=function(b){d||(d=!0,a.j(b))},f=function(b){d||(d=!0,a.u(b))};try{c.call(b,e,f)}catch(g){f(g)}},Dc=function(a){a.g||(a.g=!0,lc(a.v,
a))},Bc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.l=null);return b};rc.prototype.v=function(){for(var a=null;a=Bc(this);)Cc(this,a,this.a,this.h);this.g=!1};
var Cc=function(a,b,c,d){if(3==c&&b.b&&!b.f)for(;a&&a.f;a=a.c)a.f=!1;if(b.a)b.a.c=null,Hc(b,c,d);else try{b.f?b.l.call(b.c):Hc(b,c,d)}catch(e){Ic.call(null,e)}$b(tc,b)},Hc=function(a,b,c){2==b?a.l.call(a.c,c):a.b&&a.b.call(a.c,c)},Gc=function(a,b){a.f=!0;lc(function(){a.f&&Ic.call(null,b)})},Ic=ac,yc=function(a){_.pa.call(this,a)};_.p(yc,_.pa);yc.prototype.name="cancel";var vc=function(a,b){this.b=a;this.a=b};
var Kc,Lc,Mc,Nc,Oc;_.Jc=A("Firefox");Kc=Ta()||A("iPod");Lc=A("iPad");Mc=A("Android")&&!(Ra()||A("Firefox")||Pa()||A("Silk"));Nc=Ra();Oc=A("Safari")&&!(Ra()||A("Coast")||Pa()||Qa()||A("Silk")||A("Android"))&&!(Ta()||A("iPad")||A("iPod"));_.Pc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Qc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.Rc=function(a,b){this.l=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.f=null;this.j=b||"u";this.a=this.h=null;this.g=[]};_.Rc.prototype.message=function(){var a={};a.i=this.a;a.m=this.g;a.r=this.j;a.o=this.h;a.s=this.b;a.st=this.c;a.d=this.f;a.dt=this.l;return a};_.Rc.prototype.message=_.Rc.prototype.message;
_.Sc=function(a,b){for(var c in b)switch(c){case "r":a.j=b[c];break;case "i":a.a=b[c];break;case "m":a.g=b[c];break;case "o":a.h=b[c];break;case "s":a.b=b[c];break;case "d":a.f=b[c];break;case "st":a.c=b[c];break;case "dt":a.l=b[c]}return a};_.Tc=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))};_.Uc=function(a,b){null!=b&&(a.a=b)};_.Vc=function(a,b){"object"==typeof b?a.g=b:a.g=[b]};_.Rc.prototype.source=function(){return this.b};_.Rc.prototype.target=function(){return this.f}; _.Rc.prototype.content=function(){return this.g};
_.Wc=function(a,b,c,d,e){_.E.call(this);this.b=a;this.Ma=b;this.a=typeof b;this.wb=c?c:!1;this.ea=!0;this.sb=d?d:!1;this.mb=e?e:!1};_.p(_.Wc,_.E);_.h=_.Wc.prototype;_.h.w=function(){_.Wc.C.w.call(this);this.b="";this.Ma=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.L=function(){return this.Ma};_.h.setEnabled=function(a){this.ea=a};
var Xc=function(a){return(a=a.exec(_.Ma))?a[1]:""},Yc=function(){if(_.Jc)return Xc(/Firefox\/([0-9.]+)/);if(_.C||_.Za)return gb;if(Nc)return Xc(/Chrome\/([0-9.]+)/);if(Oc&&!(Ta()||A("iPad")||A("iPod")))return Xc(/Version\/([0-9.]+)/);if(Kc||Lc){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Ma))return a[1]+"."+a[2]}else if(Mc)return(a=Xc(/Android\s+([0-9.]+)/))?a:Xc(/Version\/([0-9.]+)/);return""}();
_.$c=function(a){_.E.call(this);this.a=new _.B;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&_.Zc(this,a)};_.p(_.$c,_.E);_.ad=0<=ta(Yc,"23.0.1262.0")&&!_.Qc();_.$c.prototype.w=function(){_.$c.C.w.call(this);for(var a=this.a.S(),b=0;b<a.length;++b)_.F(this.a.get(a[b]));delete this.a};_.$c.prototype.getItem=function(a){return _.Wa(this.a,a)?this.a.get(a):null};
_.$c.prototype.setItem=function(a){this.a.set(a.id(),a)};_.Zc=function(a,b){for(var c in b){var d=b[c],e=null;_.Wa(a.a,c)?(e=a.a.get(c),e.Ma=d.value,d.changed&&(e.mb=d.changed)):(e=new _.Wc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.dd=function(){this.c=new _.B;this.a=null;this.b=!1;this.a=new bd;this.b=!0;_.cd(this)};_.dd.ra=function(){return _.dd.a?_.dd.a:_.dd.a=new _.dd};_.cd=function(a,b){var c=b||_.oa;a.b?c():window.chrome.storage.local.get((0,_.q)(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};_.dd.prototype.get=function(a){return this.a.get(a)};_.dd.prototype.set=function(a,b){var c=_.wc();this.a.set(a,b);c.a(void 0);return c.b};_.dd.prototype.remove=function(a){this.a.remove(a)};
_.dd.prototype.clear=function(){this.a.clear()};var bd=function(){this.a=window.localStorage};bd.prototype.clear=function(){this.a.clear()};bd.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ha[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};bd.prototype.set=function(a,b){var c=null;b instanceof _.w&&(b=b.P,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}}; bd.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
_.ed=function(a,b){this.b=a;this.a=b;this.constructor.Lb||(this.constructor.Lb={});this.constructor.Lb[this.toString()]=this};_.ed.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};_.K=function(a,b){_.ed.call(this,a,b)};_.p(_.K,_.ed);_.fd=function(a){this.a=a};_.gd=new _.fd("lib");_.L=function(a){this.a=a};_.L.prototype.toString=function(){return this.a};_.hd=new _.L("fJuxOc");_.id=new _.L("ZtVrH");_.jd=new _.L("zZa4xc");_.kd=new _.L("pVbxBc");_.ld=new _.L("byfTOb");_.md=new _.L("LEikZe");_.nd=new _.L("rJmJrc");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.od=function(a,b){this.l=[];this.D=b||null;this.b=this.a=!1;this.c=void 0;this.v=this.A=this.g=!1;this.f=0;this.j=null;this.B=0};_.od.prototype.u=function(a,b){this.g=!1;_.pd(this,a,b)};_.pd=function(a,b,c){a.a=!0;a.c=c;a.b=!b;qd(a)};_.sd=function(a){if(a.a){if(!a.v)throw new rd;a.v=!1}};_.od.prototype.h=function(a){_.sd(this);_.pd(this,!0,a)};_.td=function(a,b,c,d){a.l.push([b,c,d]);a.a&&qd(a)};
_.od.prototype.then=function(a,b,c){var d,e,f=new rc(function(a,b){d=a;e=b});_.td(this,d,function(a){"undefined"!=typeof _.ud&&a instanceof _.ud?Ac(f):e(a)});return f.then(a,b,c)};nc(_.od);
var vd=function(a){return(0,_.za)(a.l,function(a){return _.ja(a[1])})},qd=function(a){if(a.f&&a.a&&vd(a)){var b=a.f,c=wd[b];c&&(_.k.clearTimeout(c.Ta),delete wd[b]);a.f=0}a.j&&(a.j.B--,delete a.j);for(var b=a.c,d=c=!1;a.l.length&&!a.g;){var e=a.l.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var l=f.call(e||a.D,b);_.n(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);if(oc(b)||"function"===typeof _.k.Promise&&b instanceof _.k.Promise)d=!0,a.g=!0}catch(r){b=r,a.b=!0,vd(a)||(c=!0)}}a.c=b;d&&(l=(0,_.q)(a.u,
a,!0),d=(0,_.q)(a.u,a,!1),b instanceof _.od?(_.td(b,l,d),b.A=!0):b.then(l,d));c&&(b=new xd(b),wd[b.Ta]=b,a.f=b.Ta)},rd=function(){_.pa.call(this)};_.p(rd,_.pa);rd.prototype.message="Deferred has already fired";rd.prototype.name="AlreadyCalledError";var xd=function(a){this.Ta=_.k.setTimeout((0,_.q)(this.b,this),0);this.a=a};xd.prototype.b=function(){delete wd[this.Ta];throw this.a;};var wd={};

}catch(e){_._DumpException(e)}
try{
var zd;_.yd=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};zd=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.Bd=function(a){_.E.call(this);this.c={};this.j={};this.u={};this.f={};this.v={};this.B={};this.A=a?a.qa():new _.J;this.G=!a;this.g=null;a?(this.g=a,this.u=a.u,this.f=a.f,this.j=a.j,this.v=a.v):(0,_.m)();a=Ad(this);this!=a&&(a.h?a.h.push(this):a.h=[this])};_.p(_.Bd,_.E);var Ad=function(a){for(;a.g;)a=a.g;return a};_.Bd.prototype.get=function(a){var b=this.b(a);if(null==b)throw new Cd(a);return b};
_.Bd.prototype.b=function(a){for(var b=this;b;b=b.g){if(b.J)throw Error("p");if(b.c[a])return b.c[a][0];if(b.B[a])break}if(b=this.u[a]){b=b(this);if(null==b)throw Error("q`"+a);this.a(a,b);return b}return null};_.Bd.prototype.a=function(a,b,c){if(this.J)c||_.F(b);else{this.c[a]=[b,!c];b=Dd(this,this,a);for(c=0;c<b.length;c++)b[c].h(null);delete this.j[a]}};_.Bd.prototype.D=function(){var a=_.Ed;if(!this.c[a])throw Error("r`"+a);var b=this.c[a];delete this.c[a];b[1]&&_.F(b[0])};
var Dd=function(a,b,c){var d=[],e=a.f[c];e&&(zd(e,function(a){var c;a:{for(c=a.Mb;c;){if(c==b){c=!0;break a}c=c.g}c=!1}c&&(d.push(a.d),_.Aa(e,a))}),0==e.length&&delete a.f[c]);return d},Fd=function(a,b){a.f&&_.Ya(a.f,function(a,d,e){zd(a,function(d){d.Mb==b&&_.Aa(a,d)});0==a.length&&delete e[d]})};
_.Bd.prototype.w=function(){if(Ad(this)==this){var a=this.h;if(a)for(;a.length;)a[0].K()}else for(var a=Ad(this).h,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].K&&a[0].K();this.c=null;this.G&&this.A.K();Fd(this,this);this.f=null;_.F(this.F);this.B=this.F=null;_.Bd.C.w.call(this)};_.Bd.prototype.qa=function(){return this.A};var Cd=function(a){_.pa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'}; _.p(Cd,_.pa);var Gd=new _.fd("fva");new _.K(Gd,1);

}catch(e){_._DumpException(e)}
try{
_.ef=function(){return window.chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_._DumpException(e)}
try{
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"}, chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"}};

}catch(e){_._DumpException(e)}
try{
_.mi=function(a){for(var b=a.a.S(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.L(),type:f.type(),multiple:f.wb,disabled:!f.ea,inverse:f.sb,changed:f.mb}}return c};_.ni=function(a,b){return _.t(b)?a.getElementById(b):b};_.S=function(a){return _.ni(window.document,a)};_.oi=new _.L("a");_.pi=new _.L("b");_.qi=new _.L("c");_.ri=new _.L("d");_.si=new _.L("e");_.ti=new _.L("f");_.ui=new _.L("g");_.vi=new _.L("h");_.Ed=new _.L("i");_.wi=new _.L("j");
_.T=function(a){var b;b=b||[];b.length||(b[0]="");var c=window.chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=_.k.ace_i18n[a.toLowerCase()])?c.message:_.k.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};
}catch(e){_._DumpException(e)}
try{
var bo=function(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")},co=function(a){_.E.call(this);this.f=_.Pc("setting",""+(0,_.m)());this.c=null;this.b=new _.I;_.G(this,this.b);this.a=new _.B;this.g=a.get(_.vi);this.b.listen(window,"unload",this.K)};_.p(co,_.E);_.ga("ace.ui.SettingsDialog",co);_.ga("ace.ui.SettingsDialog",co);
co.prototype.j=function(){window.document.title=_.T("CHROME_EXT_SHORT_NAME");this.c=window.chrome.runtime.connect({name:this.f});var a=this;this.c.onMessage.addListener(function(b){switch(_.Sc(new _.Rc,b).a){case "focus":eo(a);a.sendMessage("extensionLibrary",["selectTab",a.f,!0,!0]);window.focus();break;case "close":a.h()}});this.a.set("StartOnBrowserLaunch",["BrowserStartup",1]);this.a.set("StopOnBrowserClose",["Shutdown",1]);this.a.set("TopMost",["TopMost",1]);this.a.set("TrayIcon",["TrayIcon",
1]);_.yd(_.S("fieldsetDestPage"));go("legendApp",_.T("QUASAR_LEGEND_STARTUP_SHUTDOWN"));go("legendNotice",_.T("QUASAR_LEGEND_NOTIFICATIONS"));ho(this,"StartOnBrowserLaunch",_.T("CHROME_EXT_RUN_AT_BROWSER_START"));ho(this,"StopOnBrowserClose",_.T("CHROME_EXT_RUN_AFTER_BROWSER_CLOSE"));ho(this,"TrayIcon",_.T("QUASAR_LABEL_TRAY_ICON"));_.ad?ho(this,"TopMost",_.T("CHROME_EXT_NEW_WINDOWS_TOPMOST")):io(this,"TopMost");_.Qc()&&io(this,"TrayIcon");eo(this);var b=_.S("feedbackLink");b.innerText=_.T("CHROME_EXT_MENUTEXT_FEEDBACK");
b.href=_.ef();b=_.S("helpLink");b.innerText=_.T("QUASAR_HELP");b.href=bo("https://support.google.com/hangouts?p=help&hl=%s",window.chrome.i18n.getMessage("@@ui_locale"));this.v=_.S("buttonSave");this.v.innerText=_.T("QUASAR_BUTTON_SAVE");this.b.listen(this.v,"click",(0,_.q)(this.A,this),!1);this.u=_.S("buttonCancel");this.u.innerText=_.T("QUASAR_BUTTON_CANCEL");this.b.listen(this.u,"click",(0,_.q)(this.h,this),!1)};co.prototype.init=co.prototype.j;
var jo=function(a,b,c){var d=[];b=b+a.a.get(c)[0];a=a.a.get(c)[1];if(1<a)for(c=0;c<a;c++)d.push(_.S(b+c));else d.push(_.S(b));return d},eo=function(a){for(var b=new _.$c(a.g.get("settings")),c=a.a.S(),d=0;d<c.length;d++){var e=b.getItem(c[d]);if(e){var f=jo(a,"field",c[d]);if(e.wb){var g=e.L();0<=g&&f[g]&&(f[g].checked=!0)}else f[0]&&("boolean"==e.a?e.sb?f[0].checked=!e.L():f[0].checked=e.L():f[0].value=e.L());if(!e.ea)for(e=jo(a,"label",c[d]),g=0;g<e.length;g++)e[g]&&(e[g].disabled=!0),f[g]&&(f[g].disabled=
!0)}}},go=function(a,b){var c=_.S(a);c&&(c.innerText=b)},ho=function(a,b,c){var d=a.a.get(b)[0];a=a.a.get(b)[1];if(1<a)for(b=0;b<a;b++){var e=_.S("label"+d+b);e&&c&&(e.innerText=c[b])}else(e=_.S("label"+d))&&c&&(e.innerText=c)},io=function(a,b){var c=a.a.get(b)[0],d=_.S("field"+c);(d=(c=(c=_.S("label"+c)||d)&&c.parentNode)&&c.parentNode)&&d.removeChild(c)};
co.prototype.A=function(){for(var a=new _.$c(this.g.get("settings")),b=this.a.S(),c=0;c<b.length;c++){var d=a.getItem(b[c]);if(d){var e=jo(this,"field",b[c]),f=d.L();if(d.wb){for(var g=-1,l=0;l<e.length;l++)if(e[l]&&e[l].checked){g=l;break}-1==g&&(g=0);d.Ma=g}else e[0]&&(d.Ma="boolean"==d.a?d.sb?!e[0].checked:e[0].checked:e[0].value);f!=d.L()&&(d.mb=!0,a.setItem(d))}}this.g.set("settings",_.mi(a));this.h()};
co.prototype.h=function(){this.sendMessage("settingsManager",["updateSettingsFromStorage"]);window.close()};co.prototype.sendMessage=function(a,b,c){c=c?c:""+(0,_.m)();var d=new _.Rc;_.Tc(d,this.f,"p");null!=a&&(d.h=a);_.Uc(d,c);_.Vc(d,b);this.c&&this.c.postMessage(d.message())};
window.addEventListener("load",function(){_.cd(_.dd.ra(),function(){var a=new _.Bd;a.a(_.vi,_.dd.ra());(new co(a)).j()})},!1);
}catch(e){_._DumpException(e)}
}).call(this,this.default_settings);
// Google Inc.
